#include "CORE.H"
#include "GAMELOOP.H"
#include "MENUFACE.H"
#include "DRAW.H"
#include "STRMLOAD.H"
#include "MEMPACK.H"

int hack_initialized;
struct menuface_t MenuFaces[8] = { 236, 49,  48, 48, 2, 65535, 0, 0, 0, 
								   268, 97,  48, 48, 2, 65535, 0, 0, 0,
								   273, 156, 48, 48, 2, 65535, 0, 0, 0,
								   326, 49,  48, 48, 2, 65535, 0, 0, 0,
								   342, 114, 48, 48, 2, 65535, 0, 0, 0,
								   409, 14,  64, 64, 2, 65535, 0, 0, 0,
								   383, 78,  48, 48, 2, 65535, 0, 0, 0,
								   400, 150, 48, 48, 2, 65535, 0, 0, 0 };
struct _ButtonTexture* FaceButtons;

char * NextTimAddr(char *addr, int w, int h, enum bdepth bpp)
{ 
	long addtl;

	if (bpp == TIM_4BIT)
	{
		addtl = ((w * h) >> 1) + 44;
	}
	else if (bpp == TIM_8BIT)
	{
		addtl = (w * h) + 524;
	}
	else
	{
		addtl = (w * h) << 1;
	}

	addtl += 20;

	return addr + addtl;
}

void menuface_initialize()
{
	char *addr;
	char *buttonAddr;
	int i;
	int j;

	if (hack_initialized == 0)
	{
		addr = (char*)LOAD_ReadFile("\\kain2\\game\\psx\\frontend\\faces.tim", 11);
		buttonAddr = addr;
		
		if (addr != NULL)
		{
			FaceButtons = (_ButtonTexture*)MEMPACK_Malloc(sizeof(_ButtonTexture) * 56, 0x2D);
			
			if (FaceButtons == NULL)
			{
				MEMPACK_Free(addr);
			}
			else
			{
				for (i = 0; i < 8; i++)
				{
					MenuFaces[i].curFrame = -1;
					MenuFaces[i].transitionDir = 0;
					MenuFaces[i].loaded = 0;
					MenuFaces[i].delay = 0;

					for (j = 0; j < 7; j++)
					{
						DRAW_LoadButton((long*)buttonAddr, &FaceButtons[(i * 7) + j]);
						buttonAddr = NextTimAddr(buttonAddr, MenuFaces[i].w, MenuFaces[i].h, TIM_4BIT);
						MenuFaces[i].loaded |= 1 << j;
					}
				}

				MEMPACK_Free(addr);
				hack_initialized = 1;
			}
		}
	}
}


// autogenerated function stub: 
// void /*$ra*/ menuface_terminate()
void menuface_terminate()
{ // line 141, offset 0x800b96ac
	/* begin block 1 */
		// Start line: 142
		// Start offset: 0x800B96AC
		// Variables:
			int i; // $s3
			int j; // $s0
	/* end block 1 */
	// End offset: 0x800B973C
	// End Line: 158

	/* begin block 2 */
		// Start line: 329
	/* end block 2 */
	// End Line: 330

	/* begin block 3 */
		// Start line: 332
	/* end block 3 */
	// End Line: 333

}


// autogenerated function stub: 
// void /*$ra*/ MENUFACE_ChangeStateRandomly(int index /*$a0*/)
void MENUFACE_ChangeStateRandomly(int index)
{ // line 163, offset 0x800b9758
	/* begin block 1 */
		// Start line: 164
		// Start offset: 0x800B9758
		// Variables:
			struct menuface_t *face; // $s1
			struct menuface_t *lastFace; // $s3

		/* begin block 1.1 */
			// Start line: 177
			// Start offset: 0x800B97B0
		/* end block 1.1 */
		// End offset: 0x800B9808
		// End Line: 182
	/* end block 1 */
	// End offset: 0x800B9860
	// End Line: 195

	/* begin block 2 */
		// Start line: 381
	/* end block 2 */
	// End Line: 382

	/* begin block 3 */
		// Start line: 384
	/* end block 3 */
	// End Line: 385

}

void MENUFACE_RefreshFaces()
{
	int i;
	struct menuface_t *face;

	if (hack_initialized != 0)
	{
		for (i = 0; i < 8; i++)
		{
			face = &MenuFaces[i];

			if (MenuFaces[i].curFrame >= MenuFaces[i].frames)
			{
				DRAW_DrawButton(&FaceButtons[((i * 7) + (MenuFaces[i].curFrame / MenuFaces[i].frames))], face->x, face->y, gameTrackerX.drawOT);
			}
		}
	}
}




