version: 1.0.{build}

branches:
  only:
  - main
  
skip_tags: true

image: Visual Studio 2022

configuration:
- Debug
- Release

clone_folder: c:/projects/KAIN2

build:
  project: c:/projects/KAIN2/Build/Build_Win32/Soul Reaver.sln
  verbosity: minimal
  
platform:
  - Win32
  #- x64
  
before_build:
  - cmd: cd %clone_folder%
  - ps:  $env:GIT_COMMIT_COUNT = $(git rev-list --count HEAD)
  - cmd: git submodule update --init --recursive
  - cmd: cd External
  - cmd: cd libValkyrie
  - cmd: cd Platform
  - cmd: cd Win32
  #- cmd: cd Win64
  - cmd: Generate-Project-Files.bat
  
artifacts:
   - path: Binaries/%configuration%/*.zip
     name: Binaries
  
after_build:
  - cmd: cd ../
  - cmd: cd ../
  - cmd: cd Binaries
  - cmd: cd %configuration%
  - 7z a KAIN2-B%GIT_COMMIT_COUNT%-Win32-%configuration%.zip

deploy:
  release: B$(GIT_COMMIT_COUNT)
  description: 'Auto build B$(GIT_COMMIT_COUNT)'
  provider: GitHub
  auth_token:
    secure: hLaU+617bEqExNi+kqicDsNM11QyKeMGYCSuchk7QCjHckEGZl8lmgON8tPsqztp
  artifact: /.*\.zip/
  draft: false
  prerelease: true
  on:
    branch: main
