#include "../CORE.H"
#include "AADLIB.H"
#include "AADSFX.H"
#include "AADVOICE.H"

struct AadProgramAtr aadDummySfxProgram = { 0x0001, 0x0000, 0x7F, 0x40, 0x00 };

static void(*sfxCmdFunction[])(struct AadSfxCommand*) =
{
	sfxCmdPlayTone,
	sfxCmdStopTone,
	sfxCmdSetToneVolumeAndPan,
	sfxCmdSetToneVolPanPitch,
	sfxCmdStopAllTones,
	sfxCmdLockVoice,
	sfxCmdSetVoiceAttr,
	sfxCmdSetVoiceKeyOn,
	sfxCmdSetVoiceKeyOff
};

unsigned long aadPlaySfx(unsigned int toneID, int volume, int pan, int pitchOffset)
{
	unsigned long handle;

	handle = createSfxHandle(toneID);
	
	aadPutSfxCommand(0, volume, pan, handle, pitchOffset);
	
	return handle;
}

unsigned long aadStopSfx(unsigned long handle)
{
	aadPutSfxCommand(1, 0, 0, handle, 0);

	return handle;
}

void aadStopAllSfx()
{
	aadPutSfxCommand(4, 0, 0, 0, 0);
}


// autogenerated function stub: 
// int /*$ra*/ aadIsSfxPlaying(unsigned long handle /*$a0*/)
int aadIsSfxPlaying(unsigned long handle)
{ // line 53, offset 0x80056aac
	UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ aadIsSfxPlayingOrRequested(unsigned long handle /*$s0*/)
int aadIsSfxPlayingOrRequested(unsigned long handle)
{ // line 72, offset 0x80056b1c
	UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ aadIsSfxTypePlaying(unsigned int toneID /*$a0*/)
int aadIsSfxTypePlaying(unsigned int toneID)
{ // line 93, offset 0x80056bd4
	UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ aadIsSfxTypePlayingOrRequested(unsigned int sfxToneID /*$s0*/)
int aadIsSfxTypePlayingOrRequested(unsigned int sfxToneID)
{ // line 111, offset 0x80056c48
	UNIMPLEMENTED();
	return 0;
}

unsigned long aadSetSfxVolPanPitch(unsigned long handle, int volume, int pan, int pitch)
{
	aadPutSfxCommand(3, volume & 0xFF, pan & 0xFF, handle, pitch);

	return handle;
}

unsigned long createSfxHandle(unsigned int toneID)//Matching - 99.44%
{
	aadMem->sfxSlot.handleCounter++;

	if (aadMem->sfxSlot.handleCounter == 0)
	{
		aadMem->sfxSlot.handleCounter += 1;
	}

	return (aadMem->sfxSlot.handleCounter << 16) | (toneID & 0xFFFF);
}

void aadPutSfxCommand(int statusByte, int dataByte0, int dataByte1, unsigned long ulongParam, int shortParam)
{
	struct AadSfxCommand* sfxCmd;

	if (aadMem->sfxSlot.commandsInQueue < 30)
	{
		EnterCriticalSection();

		sfxCmd = &aadMem->sfxSlot.commandQueue[aadMem->sfxSlot.commandIn];
		sfxCmd->statusByte = statusByte;
		sfxCmd->dataByte[0] = dataByte0;
		sfxCmd->dataByte[1] = dataByte1;
		sfxCmd->ulongParam = ulongParam;
		sfxCmd->shortParam = shortParam;

		if (++aadMem->sfxSlot.commandIn == 32)
		{
			aadMem->sfxSlot.commandIn = 0;
		}

		aadMem->sfxSlot.commandsInQueue++;

		ExitCriticalSection();
	}
	else if (aadMem->sfxSlot.commandsInQueue < 31)
	{
		EnterCriticalSection();

		sfxCmd = &aadMem->sfxSlot.commandQueue[aadMem->sfxSlot.commandIn];
		sfxCmd->statusByte = 4;
		sfxCmd->dataByte[0] = dataByte0;
		sfxCmd->dataByte[1] = dataByte1;
		sfxCmd->ulongParam = ulongParam;
		sfxCmd->shortParam = shortParam;

		if (++aadMem->sfxSlot.commandIn == 32)
		{
			aadMem->sfxSlot.commandIn = 0;
		}

		aadMem->sfxSlot.commandsInQueue++;

		ExitCriticalSection();
	}
}

void aadExecuteSfxCommand(struct AadSfxCommand *sfxCmd)
{
	if (sfxCmd->statusByte < 9)
	{
		sfxCmdFunction[sfxCmd->statusByte](sfxCmd);
	}
}

void sfxCmdPlayTone(struct AadSfxCommand* sfxCmd)//Matching - 88.08%
{
	unsigned long handle;
	struct AadProgramAtr* progAtr;
	struct AadToneAtr* toneAtr;
	struct AadSynthVoice* voice;
	unsigned short midiNote;
	unsigned long waveAddr;
	struct AadLoadedSfxToneAttr* sfxToneAttr;
	struct AadLoadedSfxWaveAttr* sfxWaveAttr;
	int i;

	handle = sfxCmd->ulongParam;

	i = aadMem->sfxToneMasterList[handle & 0xFFFF];

	if (i < 0xFE)
	{
		sfxToneAttr = &aadMem->sfxToneAttrTbl[i];
		i = aadMem->sfxWaveMasterList[sfxToneAttr->waveID];

		if (i < 0xFE)
		{
			sfxWaveAttr = &aadMem->sfxWaveAttrTbl[i];//+3
			waveAddr = aadGetSramBlockAddr(sfxWaveAttr->sramHandle);
			toneAtr = &sfxToneAttr->toneAttr;
			midiNote = toneAtr->minNote;
			voice = aadAllocateVoice(sfxToneAttr->toneAttr.priority);
			progAtr = &aadDummySfxProgram;

			if (voice != NULL)
			{
				aadPlayTone(toneAtr, waveAddr, progAtr, midiNote, 0x7F, sfxCmd->dataByte[0], sfxCmd->dataByte[1], aadMem->sfxSlot.sfxVolume, aadMem->sfxMasterVol, voice, sfxCmd->shortParam);

				voice->volume = 127;
				voice->voiceID = 208;
				voice->note = (unsigned char)midiNote;
				voice->program = 1;
				voice->updateVol = sfxCmd->dataByte[0];
				voice->priority = sfxToneAttr->toneAttr.priority;
				voice->progAtr = progAtr;
				voice->toneAtr = toneAtr;
				voice->pan = sfxCmd->dataByte[1];
				voice->handle = handle;
			}
		}
	}
}


// autogenerated function stub: 
// void /*$ra*/ sfxCmdStopTone(struct AadSfxCommand *sfxCmd /*$a0*/)
void sfxCmdStopTone(struct AadSfxCommand *sfxCmd)
{ // line 344, offset 0x80057038
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ sfxCmdStopAllTones(struct AadSfxCommand *sfxCmd /*$a0*/)
void sfxCmdStopAllTones(struct AadSfxCommand *sfxCmd)
{ // line 372, offset 0x800570f0
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ sfxCmdSetToneVolumeAndPan(struct AadSfxCommand *sfxCmd /*$a0*/)
void sfxCmdSetToneVolumeAndPan(struct AadSfxCommand *sfxCmd)
{ 
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ sfxCmdSetToneVolPanPitch(struct AadSfxCommand *sfxCmd /*$s2*/)
void sfxCmdSetToneVolPanPitch(struct AadSfxCommand *sfxCmd)
{ // line 439, offset 0x80057508
	UNIMPLEMENTED();
}

void sfxCmdLockVoice(struct AadSfxCommand* sfxCmd)
{
	typedef void* (*func)(unsigned long);
	func callbackProc;
	struct AadSynthVoice* voice;

	callbackProc = (func)sfxCmd->ulongParam;

	voice = aadAllocateVoice(255);

	if (voice != NULL)
	{
		voice->flags |= 0x1;

		callbackProc(voice->voiceMask);
	}
	else
	{
		callbackProc(voice->voiceMask);
	}
}


// autogenerated function stub: 
// void /*$ra*/ sfxCmdSetVoiceAttr(struct AadSfxCommand *sfxCmd /*$a0*/)
void sfxCmdSetVoiceAttr(struct AadSfxCommand *sfxCmd)
{ // line 516, offset 0x800579c0
	UNIMPLEMENTED();
}

void sfxCmdSetVoiceKeyOn(struct AadSfxCommand* sfxCmd)
{
	aadMem->voiceKeyOnRequest |= sfxCmd->ulongParam;
}

void sfxCmdSetVoiceKeyOff(struct AadSfxCommand* sfxCmd)
{
	aadMem->voiceKeyOffRequest |= sfxCmd->ulongParam;
	aadMem->voiceKeyOnRequest &= ~sfxCmd->ulongParam;
}
