#include "CORE.H"
#include "MEMCARD.H"
#include "GAMELOOP.H"
#include "MEMPACK.H"
#include "STRMLOAD.H"
#include "RELMOD.H"
#include "MENU/MENU.H"
#include "PSX/MAIN.H"

#if defined(PSXPC_VERSION)
#include "OVERLAYS/MCARDX.H"
#endif

struct memcard_t gMemcard;
int the_header_size;
struct SavedInfoTracker savedInfoTracker;
struct mcmenu gMcmenu;

int MEMCARD_IsWrongVersion(struct memcard_t *memcard)
{
	int result = 1;
	if (memcard != NULL)
	{
		result = memcard->wrongVerison;
	}

	return result;
}

void load(struct memcard_t* memcard)
{
	struct Object* object;
	
	if ((gameTrackerX.gameFlags & 0x8000000))
	{
		object = (Object*)&gameTrackerX.primPool->prim[0];
	}
	else
	{
		object = (Object*)MEMPACK_Malloc(40000, 0x2B);
	}

	LOAD_LoadToAddress("\\kain2\\object\\mcardx\\mcardx.drm", object, 1);

	memcard->table = (mcmenu_table_t*)object->relocModule;
	RELMOD_InitModulePointers((int)object->relocModule, (int*)object->relocList);
	memcard->object = object;

#if !defined(PSXPC_VERSION)
	if (memcard->table->versionID != "Jun 30 1999")
	{
		if (!(gameTrackerX.gameFlags & 0x8000000))
		{
			MEMPACK_Free((char*)object);
		}

		memcard->table = NULL;
	}
#elif defined(PSXPC_VERSION)
	//PSXPC version we have to override this stuff now.
	memcard->table->data_size = NULL;
	memcard->table->initialize = MCARDX_initialize;
	memcard->table->terminate = NULL;
	memcard->table->begin = MCARDX_begin;
	memcard->table->end = MCARDX_end;
	memcard->table->set_buffer = MCARDX_set_buffer;
	memcard->table->main = MCARDX_main;
	memcard->table->pause = MCARDX_pause;
#endif
}

void unload(struct memcard_t* memcard)
{
	if (memcard->object != NULL)
	{
		if ((char*)memcard != (char*)&gameTrackerX.primPool->prim)
		{
			MEMPACK_Free((char*)memcard->object);
		}

		memcard->object = NULL;
	}

	memcard->table = NULL;
}


// autogenerated function stub: 
// int /*$ra*/ memcard_data_size()
int memcard_data_size()
{ // line 133, offset 0x800b9a58
	/* begin block 1 */
		// Start line: 285
	/* end block 1 */
	// End Line: 286

	/* begin block 2 */
		// Start line: 286
	/* end block 2 */
	// End Line: 287
	UNIMPLEMENTED();
	return 0;
}

int memcard_initialize(struct memcard_t *memcard, void *gt, int nblocks, void *buffer, int nbytes)
{
	int header_size;
	
	memset(memcard, 0, sizeof(memcard_t));

	load(memcard);
	
	header_size = 0;
	memcard->wrongVerison = 0;

	if (memcard->table != NULL)
	{
		memcard->mcmenu = &gMcmenu.dummy1;
		memcard->table->initialize(memcard->mcmenu, memcard, nblocks);
		header_size = memcard->table->set_buffer(memcard->mcmenu, buffer, nbytes);
		unload(memcard);
	}
	else
	{
		memcard->wrongVerison = 1;
	}

	return header_size;
}

void memcard_end(struct memcard_t* memcard)
{ 
	memcard->table->end(memcard->mcmenu);

	unload(memcard);

	memcard->running = 0;
}

int maybe_start(struct memcard_t *memcard)
{
	if (memcard->running == 0)
	{
		if (memcard->object == NULL)
		{
			load(memcard);
		}
		memcard->running = 1;
		memcard->table->begin(memcard->mcmenu);
	}
	
	return 1;
}

int memcard_main_menu(void *gt, int index)
{
	struct memcard_t *memcard;
	
	memcard = ((GameTracker*)gt)->memcard;
	
	if (maybe_start(memcard) != 0)
	{
		memcard->table->main(memcard->mcmenu, index);
	}
	
	return -1;
}

int memcard_pause_menu(void *gt, int index)
{ 
	struct memcard_t *memcard;

	memcard = ((struct GameTracker*)gt)->memcard;

	if (maybe_start(memcard))
	{
		return memcard->table->pause(memcard->mcmenu, index);
	}

	return -1;
}

void* gt2mcmenu(void* gt)
{
	struct memcard_t* memcard;
	
	memcard = ((struct GameTracker*)gt)->memcard;

	return memcard->mcmenu;
}


// autogenerated function stub: 
// void /*$ra*/ memcard_pop(void *opaque /*$a0*/)
void memcard_pop(void *opaque)
{ // line 235, offset 0x800b9c8c
	/* begin block 1 */
		// Start line: 509
	/* end block 1 */
	// End Line: 510
	UNIMPLEMENTED();
}

void memcard_start(void *opaque)
{
	gameTrackerX.streamFlags |= 0x1000000;

	MAIN_StartGame();

	memcard_end(gameTrackerX.memcard);
}


// autogenerated function stub: 
// void /*$ra*/ memcard_load(void *opaque /*$a0*/)
void memcard_load(void *opaque)
{ // line 252, offset 0x800b9d0c
	/* begin block 1 */
		// Start line: 549
	/* end block 1 */
	// End Line: 550
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ memcard_save(void *opaque /*$a0*/)
void memcard_save(void *opaque)
{ // line 261, offset 0x800b9d58
	/* begin block 1 */
		// Start line: 569
	/* end block 1 */
	// End Line: 570
	UNIMPLEMENTED();
}

void memcard_item(void *opaque, int (*fn)(void*, long, enum menu_ctrl_t), long parameter, long flags, char *text)
{
	if (flags != 0)
	{
		menu_item_flags(gameTrackerX.menu, fn, parameter, flags, text);
	}
	else
	{
		menu_item(gameTrackerX.menu, fn, parameter, text);
	}
}




