#include "CORE.H"
#include "INSTNCG2.H"
#include "G2/ANIMG2.H"

void G2Instance_BuildTransformsForList(struct _Instance* listHead)//Matching - 99.74%
{
	struct _Instance* instance;

	instance = listHead;

	while (instance != NULL)
	{
		if (instance->LinkParent == NULL)
		{
			if ((instance->flags2 & 0x1) || ((instance->flags & 0x100000) &&
				(instance->oldPos.x == instance->position.x) &&
				(instance->oldPos.y == instance->position.y) &&
				(instance->oldPos.z == instance->position.z) &&
				(instance->oldRotation.x == instance->rotation.x) &&
				(instance->oldRotation.y == instance->rotation.y) &&
				(instance->oldRotation.z == instance->rotation.z) &&
				(instance->matrix != NULL) && (((instance->object->animList == NULL)) ||
				(instance->object->oflags2 & 0x40000000) || !(instance->anim.flags & 0x1))))
			{

				_G2Instance_BuildDeactivatedTransforms(instance);
			}
			else
			{
				G2Instance_BuildTransforms(instance);
			}
		}

		instance = instance->next;
	}

	instance = listHead;

	while (instance != NULL)
	{
		if (instance->rebuildCallback != NULL)
		{
			if (instance->rebuildCallback(instance) != FALSE)
			{
				G2Anim_UpdateStoredFrame(&instance->anim);

				G2Instance_RebuildTransforms(instance);
			}
		}

		instance = instance->next;
	}
}

void G2Instance_BuildTransforms(struct _Instance* instance)
{
	if (instance->object->animList != NULL && !(instance->object->oflags2 & 0x40000000))
	{
		_G2Instance_BuildAnimatedTransforms(instance);
	}
	else
	{
		_G2Instance_BuildNonAnimatedTransforms(instance);
	}
}


// autogenerated function stub: 
// void /*$ra*/ G2Instance_RebuildTransforms(struct _Instance *instance /*$a0*/)
void G2Instance_RebuildTransforms(struct _Instance *instance)
{ // line 169, offset 0x80094f68
	struct Object *object; // eax
#if defined(PC_VERSION)
  object = instance->object;
  if ( !object->animList || (object->oflags2 & 0x40000000) != 0 )
    G2Instance_RebuildNonAnimatedTransforms(instance);
  else
    G2Instance_RebuildAnimatedTransforms(instance);
#endif
}

struct _G2AnimKeylist_Type * G2Instance_GetKeylist(struct _Instance *instance, int id)
{
	return instance->object->animList[id];
}


// autogenerated function stub: 
// void /*$ra*/ _G2Instance_RebuildAnimatedTransforms(struct _Instance *instance /*$s3*/)
void _G2Instance_RebuildAnimatedTransforms(struct _Instance *instance)
{ // line 196, offset 0x80094fe4
	/* begin block 1 */
		// Start line: 197
		// Start offset: 0x80094FE4
		// Variables:
			struct _Model *model; // $s7
			struct _G2Matrix_Type *rootMatrix; // $s4
			struct _Rotation pre_facade_rot; // stack offset -120
			struct _G2Matrix_Type *segMatrix; // $a2
			struct _G2Matrix_Type seg1RotMatrix; // stack offset -112
			struct _G2Matrix_Type seg2RotMatrix; // stack offset -80
			struct _G2SVector3_Type rotVector; // stack offset -48
			long otx; // $s6
			long oty; // $s5
			long otz; // $s2
			long segIndex; // $s1

		/* begin block 1.1 */
			// Start line: 220
			// Start offset: 0x80095048
		/* end block 1.1 */
		// End offset: 0x80095094
		// End Line: 229

		/* begin block 1.2 */
			// Start line: 283
			// Start offset: 0x80095244
			// Variables:
				//struct VECTOR *ins_scale; // $v1
		/* end block 1.2 */
		// End offset: 0x80095278
		// End Line: 291
	/* end block 1 */
	// End offset: 0x800953EC
	// End Line: 346

	/* begin block 2 */
		// Start line: 415
	/* end block 2 */
	// End Line: 416
UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ G2Instance_ClearMatrices(struct _Instance *instance /*$s0*/)
void G2Instance_ClearMatrices(struct _Instance* instance)
{ // line 348, offset 0x80095418
	/* begin block 1 */
		// Start line: 756
	/* end block 1 */
	// End Line: 757
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ _G2Instance_BuildAnimatedTransforms(struct _Instance *instance /*$s0*/)
void _G2Instance_BuildAnimatedTransforms(struct _Instance* instance)
{ // line 359, offset 0x8009546c
	/* begin block 1 */
		// Start line: 360
		// Start offset: 0x8009546C
		// Variables:
			//MATRIX *rootMatrix; // $v0
	struct _Model* model; // $v0
	/* end block 1 */
	// End offset: 0x80095518
	// End Line: 388

	/* begin block 2 */
		// Start line: 774
	/* end block 2 */
	// End Line: 775

	/* begin block 3 */
		// Start line: 780
	/* end block 3 */
	// End Line: 781
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ _G2Instance_RebuildNonAnimatedTransforms(struct _Instance *instance /*$s0*/)
void _G2Instance_RebuildNonAnimatedTransforms(struct _Instance* instance)
{ // line 392, offset 0x80095528
	/* begin block 1 */
		// Start line: 393
		// Start offset: 0x80095528
		// Variables:
			//struct VECTOR *scale; // $s5
			//MATRIX *introTransform; // $s7
			//MATRIX *segMatrix; // $s1
	struct _Model* model; // $fp
	struct _Segment* segment; // $s3
	short scale_flag; // stack offset -48
	long i; // $s4
	/* end block 1 */
	// End offset: 0x80095784
	// End Line: 511

	/* begin block 2 */
		// Start line: 847
	/* end block 2 */
	// End Line: 848
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ _G2Instance_BuildDeactivatedTransforms(struct _Instance *instance /*$s0*/)
void _G2Instance_BuildDeactivatedTransforms(struct _Instance* instance)
{ // line 515, offset 0x800957b4
	/* begin block 1 */
		// Start line: 516
		// Start offset: 0x800957B4
		// Variables:
			//MATRIX *segMatrix; // $a0
			//MATRIX *startOldMatrix; // $a1
	int numMatrices; // $s1
	struct _Model* model; // $a0
	/* end block 1 */
	// End offset: 0x80095920
	// End Line: 578

	/* begin block 2 */
		// Start line: 1276
	/* end block 2 */
	// End Line: 1277
	UNIMPLEMENTED();
}

void _G2Instance_BuildNonAnimatedTransforms(struct _Instance* instance)
{
	MATRIX* segMatrix;
	struct _Model* model;

	if ((instance->flags2 & 0x10000000) && (instance->flags2 & 0x4000000) && (instance->flags2 & 0x20000000) && (instance->flags & 0x800))
	{
		G2Instance_ClearMatrices(instance);
	}
	else
	{
		model = instance->object->modelList[instance->currentModel];

		segMatrix = GAMELOOP_GetMatrices(model->numSegments);

		if (segMatrix == NULL)
		{
			instance->matrix = NULL;
		}
		else
		{
			instance->oldMatrix = instance->matrix;
			instance->matrix = segMatrix;

			_G2Instance_RebuildNonAnimatedTransforms(instance);
		}
	}
}


// autogenerated function stub: 
// void /*$ra*/ _G2Instance_BuildFacadeTransforms(struct _Instance *instance /*$s0*/, struct _Segment *segment /*$s1*/, MATRIX *segMatrix /*$s5*/, MATRIX *matrixPool /*$s6*/, long scale_flag /*stack 16*/)
void _G2Instance_BuildFacadeTransforms(struct _Instance *instance, struct _Segment *segment, MATRIX *segMatrix, MATRIX *matrixPool, long scale_flag)
{ // line 619, offset 0x800959f0
	/* begin block 1 */
		// Start line: 620
		// Start offset: 0x800959F0
		// Variables:
			_Position *cameraPos; // $s7
			SVECTOR*segmentPos; // $s3
			SVECTOR*segmentRot; // $s4
			//struct VECTOR *scale; // $fp

		/* begin block 1.1 */
			// Start line: 644
			// Start offset: 0x80095B1C
			// Variables:
				SVECTOR*zvec; // $s1
				SVECTOR*camWorldPos; // $s2
				SVECTOR*camLocPos; // $s6
				long sqrt; // $s0
		/* end block 1.1 */
		// End offset: 0x80095C38
		// End Line: 676

		/* begin block 1.2 */
			// Start line: 683
			// Start offset: 0x80095C98
			// Variables:
				//struct VECTOR *xy; // $s0
		/* end block 1.2 */
		// End offset: 0x80095D5C
		// End Line: 702
	/* end block 1 */
	// End offset: 0x80095D5C
	// End Line: 703

	/* begin block 2 */
		// Start line: 1488
	/* end block 2 */
	// End Line: 1489
				UNIMPLEMENTED();
}




