#include "CORE.H"
#include "POOLMMG2.H"
#include "MEMPACK.H"

// autogenerated function stub: 
// void /*$ra*/ G2PoolMem_InitPool(void *voidPool /*$s1*/, int blockCount /*$s0*/, int blockSize /*$s2*/)
void G2PoolMem_InitPool(void *voidPool, int blockCount, int blockSize)
{ // line 9, offset 0x80095d9c
#if defined(PC_VERSION)
	int v3; // eax
	struct _G2PoolMemPool_Type* pool = (struct _G2PoolMemPool_Type*)voidPool; // $a0

	pool->blockPool = (struct _G2PoolMem_Type*)MEMPACK_Malloc(blockCount * blockSize, 0x19u);
	pool->stack = (unsigned __int16*)MEMPACK_Malloc(2 * blockCount, 0x19u);
	v3 = 0;
	pool->blockSize = blockSize;
	pool->stackSize = blockCount;
	pool->stackTop = 0;
	if ((WORD)blockCount)
	{
		do
		{
			pool->stack[v3] = v3;
			++v3;
		} while (v3 < pool->stackSize);
	}
#endif
}

void G2PoolMem_ResetPool(void *voidPool)
{ 
#if defined(PSX_VERSION)

	struct _G2PoolMemPool_Type* pool;
	int blockIndex;

	pool = (struct _G2PoolMemPool_Type*)voidPool;

	blockIndex = 0;
	pool->stackTop = 0;

	if (pool->stackSize != 0)
	{
		do
		{
		
			pool->stack[blockIndex++] = 0;
	
		} while (blockIndex < pool->stackSize);
	}

#elif defined(PC_VERSION)
	struct _G2PoolMemPool_Type *pool = (struct _G2PoolMemPool_Type*)voidPool; // $a0

	int v1; // eax
	bool v2; // zf

	v1 = 0;
	v2 = pool->stackSize == 0;
	pool->stackTop = 0;
	if (!v2)
	{
		do
		{
			pool->stack[v1] = v1;
			++v1;
		} while (v1 < pool->stackSize);
	}
#endif
}


// autogenerated function stub: 
// void * /*$ra*/ G2PoolMem_Allocate(void *voidPool /*$a1*/)
void * G2PoolMem_Allocate(void *voidPool)
{ // line 64, offset 0x80095e44
#if defined(PC_VERSION)
	struct _G2PoolMemPool_Type* pool = (struct _G2PoolMemPool_Type*)voidPool;
	unsigned __int16 stackTop; // ax
	unsigned __int16 v3; // dx

	stackTop = pool->stackTop;
	if (stackTop >= pool->stackSize)
		return 0;
	v3 = pool->stack[stackTop];
	pool->stackTop = stackTop + 1;
	return (char*)pool->blockPool + v3 * pool->blockSize;
#else
	return NULL;
#endif
}


// autogenerated function stub: 
// void /*$ra*/ G2PoolMem_Free(void *voidPool /*$a0*/, void *block /*$a1*/)
void G2PoolMem_Free(void *voidPool, void *block)
{ // line 87, offset 0x80095ea0
#if defined(PC_VERSION)
	struct _G2PoolMemPool_Type* pool = (struct _G2PoolMemPool_Type*)voidPool;
	int v2; // eax

	v2 = (signed int)((int)block - (unsigned int)pool->blockPool) / pool->blockSize;
	pool->stack[--pool->stackTop] = v2;
#endif
}




