#include "THISDUST.H"
#include "LIGHT3D.H"


// autogenerated function stub: 
// void /*$ra*/ LIGHT_GetLightMatrix(struct _Instance *instance /*$a0*/, struct Level *level /*$a1*/, struct MATRIX *lightM /*$a2*/, struct MATRIX *colorM /*$a3*/)
void LIGHT_GetLightMatrix(struct _Instance *instance, struct Level *level, struct MATRIX *lightM, struct MATRIX *colorM)
{ // line 70, offset 0x80035824
	/* begin block 1 */
		// Start line: 72
		// Start offset: 0x80035824
		// Variables:
			struct MATRIX *lightGroup; // $t0
			struct LightList *lightList; // $v1
			int lightGrp; // $t1

		/* begin block 1.1 */
			// Start line: 120
			// Start offset: 0x800358F4
			// Variables:
				struct MATRIX *tlightGroup; // $t2
				struct LightList *tlightList; // $t3
				int tlightGrp; // $t1
				struct MATRIX *start; // $t4
				struct MATRIX *end; // $t3
				int i; // $t1
				int j; // $a2
				long ratio; // $t2
		/* end block 1.1 */
		// End offset: 0x80035AB8
		// End Line: 186
	/* end block 1 */
	// End offset: 0x80035B90
	// End Line: 195

	/* begin block 2 */
		// Start line: 140
	/* end block 2 */
	// End Line: 141

	/* begin block 3 */
		// Start line: 141
	/* end block 3 */
	// End Line: 142

	/* begin block 4 */
		// Start line: 145
	/* end block 4 */
	// End Line: 146

}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_PresetInstanceLight(struct _Instance *instance /*$s0*/, short attenuate /*$a1*/, struct MATRIX *lm /*$s1*/)
void LIGHT_PresetInstanceLight(struct _Instance *instance, short attenuate, struct MATRIX *lm)
{ // line 200, offset 0x80035b98
	int currentStreamUnitID; // eax
	struct Level* LevelWithID; // edi
	int v5; // eax
	__int16* p_TODRedScale; // eax
	MATRIX* p_colorM; // ecx
	int* v8; // ebp
	__int16* v9; // ebx
	int v10; // edi
	int v11; // esi
	int v12; // eax
	int v13; // edx
	__int16 v14[4]; // [esp+10h] [ebp-34h] BYREF
	int v15[3]; // [esp+18h] [ebp-2Ch] BYREF
	MATRIX colorM; // [esp+24h] [ebp-20h] BYREF
	int attenuatea; // [esp+4Ch] [ebp+8h]

	currentStreamUnitID = instance->currentStreamUnitID;
	v14[0] = 4096;
	v14[1] = 4096;
	v14[2] = 4096;
	LevelWithID = STREAM_GetLevelWithID(currentStreamUnitID);
	LIGHT_GetLightMatrix(instance, LevelWithID, lm, &colorM);
	v5 = 4096;
	if ((instance->flags & 0x200000) != 0)
		v5 = 2048;
	if (attenuate != 4096)
		v5 = (v5 * attenuate) >> 12;
	v15[0] = v5;
	v15[1] = v5;
	v15[2] = v5;
	p_TODRedScale = &LevelWithID->TODRedScale;
	if (!LevelWithID)
		p_TODRedScale = v14;
	p_colorM = &colorM;
	v8 = v15;
	v9 = p_TODRedScale;
	attenuatea = 3;
	do
	{
		v10 = (__int16)((*v8 * *v9) >> 12);
		v11 = 3;
		do
		{
			v12 = (v10 * p_colorM->m[0][0]) >> 12;
			v13 = v12;
			if (v12 <= -32768)
				v13 = -32768;
			if (v13 >= 32767)
			{
				v12 = 32767;
			}
			else if (v12 <= -32768)
			{
				v12 = 0x8000;
			}
			p_colorM->m[0][0] = v12;
			p_colorM = (MATRIX*)((char*)p_colorM + 2);
			--v11;
		} while (v11);
		++v9;
		++v8;
		--attenuatea;
	} while (attenuatea);
	SetColorMatrix(&colorM);
}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_GetAmbient(struct _ColorType *color /*$a0*/, struct _Instance *instance /*$a1*/)
void LIGHT_GetAmbient(struct _ColorType *color, struct _Instance *instance)
{ // line 290, offset 0x80035d14
	uchar v2; // al

	v2 = (instance->object->oflags2 & 0x800) != 0 ? 0 : 48;
	color->b = v2;
	color->g = v2;
	color->r = v2;
}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_CalcLightValue(struct _TFace *tface /*$t2*/, struct _Instance *instance /*$fp*/, struct _Terrain *terrain /*$t3*/)
void LIGHT_CalcLightValue(struct _TFace *tface, struct _Instance *instance, struct _Terrain *terrain)
{ // line 336, offset 0x80035d44
	/* begin block 1 */
		// Start line: 337
		// Start offset: 0x80035D44
		// Variables:
			struct _ColorType color; // stack offset -88
			short fadespeed; // $a2

		/* begin block 1.1 */
			// Start line: 348
			// Start offset: 0x80035DA4
			// Variables:
				struct _ColorType color1; // stack offset -80
				struct _ColorType color2; // stack offset -72
				long n; // $v1
				long count; // $a0
				long edge; // $a2
				int x1; // $v1
				int x2; // $a0
				int interp1; // $s3
				int interp2; // $s2
				int interp; // $a3
				short *temp; // $v0
				short *vertex0; // $s6
				short *vertex1; // $s5
				short *vertex2; // $s4
				short position[3]; // stack offset -64
				struct _SVector normal; // stack offset -56
				struct BSPTree *bsp; // $a1
				int major; // $a3
				int minor; // $s7

			/* begin block 1.1.1 */
				// Start line: 457
				// Start offset: 0x80036194
				// Variables:
					long r; // $v0
					long g; // $a1
					long b; // $v1
					int lum; // $a0
			/* end block 1.1.1 */
			// End offset: 0x80036244
			// End Line: 478
		/* end block 1.1 */
		// End offset: 0x80036244
		// End Line: 478

		/* begin block 1.2 */
			// Start line: 493
			// Start offset: 0x80036264
			// Variables:
				int i; // $t0
				struct LightInstance *li; // $t4
				long dist; // $t3
				struct LightInstance *tli; // $t2

			/* begin block 1.2.1 */
				// Start line: 500
				// Start offset: 0x80036274
				// Variables:
					struct _Instance *inst; // $a1

				/* begin block 1.2.1.1 */
					// Start line: 503
					// Start offset: 0x8003629C
					// Variables:
						short tdist; // $a3
						struct _Position pos; // stack offset -64
						struct MATRIX *mat; // $a1
				/* end block 1.2.1.1 */
				// End offset: 0x80036384
				// End Line: 520
			/* end block 1.2.1 */
			// End offset: 0x80036384
			// End Line: 521
		/* end block 1.2 */
		// End offset: 0x80036450
		// End Line: 545
	/* end block 1 */
	// End offset: 0x80036468
	// End Line: 553

	/* begin block 2 */
		// Start line: 740
	/* end block 2 */
	// End Line: 741

}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_SetAmbientInstance(struct _Instance *instance /*$v0*/, struct Level *level /*$a1*/)
void LIGHT_SetAmbientInstance(struct _Instance *instance, struct Level *level)
{ // line 555, offset 0x80036498
	/* begin block 1 */
		// Start line: 556
		// Start offset: 0x80036498
	/* end block 1 */
	// End offset: 0x80036498
	// End Line: 556

	/* begin block 2 */
		// Start line: 1247
	/* end block 2 */
	// End Line: 1248

}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_SetMatrixForLightGroupInstance(struct _Instance *instance /*$s0*/, struct Level *level /*$a1*/)
void LIGHT_SetMatrixForLightGroupInstance(struct _Instance *instance, struct Level *level)
{ // line 569, offset 0x800364c8
	/* begin block 1 */
		// Start line: 570
		// Start offset: 0x800364C8
		// Variables:
			struct MATRIX lgt_cat; // stack offset -40
			struct LightList *lightList; // $v0
			int lightGrp; // $v1
	/* end block 1 */
	// End offset: 0x80036634
	// End Line: 682

	/* begin block 2 */
		// Start line: 1275
	/* end block 2 */
	// End Line: 1276

}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_DrawShadow(struct MATRIX *wcTransform /*$s2*/, struct _Instance *instance /*$s1*/, struct _PrimPool *primPool /*$s3*/, unsigned long **ot /*$s4*/)
void LIGHT_DrawShadow(struct MATRIX *wcTransform, struct _Instance *instance, struct _PrimPool *primPool, unsigned long **ot)
{ // line 730, offset 0x80036644
	/* begin block 1 */
		// Start line: 731
		// Start offset: 0x80036644
		// Variables:
			struct SVECTOR face_orient; // stack offset -112
			struct MATRIX rot; // stack offset -104
			struct MATRIX scTransform; // stack offset -72
			struct _Vector scale; // stack offset -40
			struct _Instance *playerInstance; // $s0
	/* end block 1 */
	// End offset: 0x80036908
	// End Line: 804

	/* begin block 2 */
		// Start line: 1460
	/* end block 2 */
	// End Line: 1461

}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_CalcShadowPositions(struct GameTracker *gameTracker /*$a0*/)
void LIGHT_CalcShadowPositions(struct GameTracker *gameTracker)
{ // line 806, offset 0x80036928
	/* begin block 1 */
		// Start line: 807
		// Start offset: 0x80036928
		// Variables:
			struct _InstanceList *instanceList; // $v0
			struct _Instance *instance; // $s0
			struct _PCollideInfo pcollideInfo; // stack offset -72
			struct _Position newPos; // stack offset -24
			struct _Position oldPos; // stack offset -16
			struct Level *level; // $v0
	/* end block 1 */
	// End offset: 0x80036C18
	// End Line: 910

	/* begin block 2 */
		// Start line: 1734
	/* end block 2 */
	// End Line: 1735

}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_Restore(struct LightInfo *lightInfo /*$a0*/)
void LIGHT_Restore(struct LightInfo *lightInfo)
{ // line 1361, offset 0x80036c28
	/* begin block 1 */
		// Start line: 2722
	/* end block 1 */
	// End Line: 2723

	/* begin block 2 */
		// Start line: 2405
	/* end block 2 */
	// End Line: 2406

}


// autogenerated function stub: 
// void /*$ra*/ LIGHT_CalcDQPTable(struct Level *level /*$a3*/)
void LIGHT_CalcDQPTable(struct Level *level)
{ // line 1600, offset 0x80036c30
	/* begin block 1 */
		// Start line: 1601
		// Start offset: 0x80036C30
		// Variables:
			long dqa; // $a1
			long limit; // $t0

		/* begin block 1.1 */
			// Start line: 1614
			// Start offset: 0x80036C78
		/* end block 1.1 */
		// End offset: 0x80036CA0
		// End Line: 1621

		/* begin block 1.2 */
			// Start line: 1624
			// Start offset: 0x80036CB0
		/* end block 1.2 */
		// End offset: 0x80036CE4
		// End Line: 1631
	/* end block 1 */
	// End offset: 0x80036D3C
	// End Line: 1661

	/* begin block 2 */
		// Start line: 3200
	/* end block 2 */
	// End Line: 3201

}




