#include "THISDUST.H"
#include "LOAD3D.H"


// autogenerated function stub: 
// void /*$ra*/ LOAD_InitCd()
void LOAD_InitCd()
{ // line 231, offset 0x80036d44
	/* begin block 1 */
		// Start line: 279
	/* end block 1 */
	// End Line: 280

	/* begin block 2 */
		// Start line: 462
	/* end block 2 */
	// End Line: 463

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_CdSeekCallback(unsigned char intr /*$a0*/, unsigned char *result /*$a1*/)
void LOAD_CdSeekCallback(unsigned char intr, unsigned char *result)
{ // line 255, offset 0x80036d74
	/* begin block 1 */
		// Start line: 327
	/* end block 1 */
	// End Line: 328

	/* begin block 2 */
		// Start line: 328
	/* end block 2 */
	// End Line: 329

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_CdDataReady()
void LOAD_CdDataReady()
{ // line 267, offset 0x80036d90
	/* begin block 1 */
		// Start line: 268
		// Start offset: 0x80036D90

		/* begin block 1.1 */
			// Start line: 275
			// Start offset: 0x80036DCC
			// Variables:
				struct _ReadQueueEntry *currentQueueFile; // $s0
				long actualReadSize; // $a1

			/* begin block 1.1.1 */
				// Start line: 292
				// Start offset: 0x80036E30
				// Variables:
					int status; // $s1
			/* end block 1.1.1 */
			// End offset: 0x80036E9C
			// End Line: 324
		/* end block 1.1 */
		// End offset: 0x80036E9C
		// End Line: 325
	/* end block 1 */
	// End offset: 0x80036E9C
	// End Line: 330

	/* begin block 2 */
		// Start line: 351
	/* end block 2 */
	// End Line: 352

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_CdReadReady(unsigned char intr /*$a0*/, unsigned char *result /*$a1*/)
void LOAD_CdReadReady(unsigned char intr, unsigned char *result)
{ // line 333, offset 0x80036eb0
	/* begin block 1 */
		// Start line: 334
		// Start offset: 0x80036EB0

		/* begin block 1.1 */
			// Start line: 344
			// Start offset: 0x80036EDC
			// Variables:
				long crap[3]; // stack offset -40
				int bytes; // $s0

			/* begin block 1.1.1 */
				// Start line: 367
				// Start offset: 0x80036F50
				// Variables:
					struct CdlLOC loc; // stack offset -24
			/* end block 1.1.1 */
			// End offset: 0x80036F50
			// End Line: 370
		/* end block 1.1 */
		// End offset: 0x80036F50
		// End Line: 370
	/* end block 1 */
	// End offset: 0x80036F88
	// End Line: 396

	/* begin block 2 */
		// Start line: 488
	/* end block 2 */
	// End Line: 489

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_UpdateCheckSum(long bytes /*$a1*/)
void LOAD_UpdateCheckSum(long bytes)
{ // line 398, offset 0x80036f9c
	/* begin block 1 */
		// Start line: 632
	/* end block 1 */
	// End Line: 633

	/* begin block 2 */
		// Start line: 635
	/* end block 2 */
	// End Line: 636

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_DoCDReading()
void LOAD_DoCDReading()
{ // line 413, offset 0x80036fe0
	/* begin block 1 */
		// Start line: 414
		// Start offset: 0x80036FE0
		// Variables:
			long bytesLoaded; // $a0
			long readSoFar; // $v0
			long state; // $s0
			long lastCheck; // $v1
	/* end block 1 */
	// End offset: 0x8003707C
	// End Line: 509

	/* begin block 2 */
		// Start line: 665
	/* end block 2 */
	// End Line: 666

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_DoCDBufferedReading()
void LOAD_DoCDBufferedReading()
{ // line 516, offset 0x8003708c
	/* begin block 1 */
		// Start line: 879
	/* end block 1 */
	// End Line: 880

	/* begin block 2 */
		// Start line: 881
	/* end block 2 */
	// End Line: 882

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_SetupFileToDoCDReading()
void LOAD_SetupFileToDoCDReading()
{ // line 527, offset 0x800370a8
	/* begin block 1 */
		// Start line: 528
		// Start offset: 0x800370A8

		/* begin block 1.1 */
			// Start line: 528
			// Start offset: 0x800370A8
			// Variables:
				struct CdlLOC loc; // stack offset -16
		/* end block 1.1 */
		// End offset: 0x800370E4
		// End Line: 543
	/* end block 1 */
	// End offset: 0x800370E4
	// End Line: 544

	/* begin block 2 */
		// Start line: 901
	/* end block 2 */
	// End Line: 902

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_SetupFileToDoBufferedCDReading()
void LOAD_SetupFileToDoBufferedCDReading()
{ // line 602, offset 0x80037124
	/* begin block 1 */
		// Start line: 603
		// Start offset: 0x80037124

		/* begin block 1.1 */
			// Start line: 603
			// Start offset: 0x80037124
			// Variables:
				struct CdlLOC loc; // stack offset -16
		/* end block 1.1 */
		// End offset: 0x80037158
		// End Line: 619
	/* end block 1 */
	// End offset: 0x80037158
	// End Line: 620

	/* begin block 2 */
		// Start line: 1093
	/* end block 2 */
	// End Line: 1094

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_ProcessReadQueue()
void LOAD_ProcessReadQueue()
{ // line 627, offset 0x80037198
	/* begin block 1 */
		// Start line: 628
		// Start offset: 0x80037198

		/* begin block 1.1 */
			// Start line: 668
			// Start offset: 0x80037248
			// Variables:
				long cdWaitTimeDiff; // $v0

			/* begin block 1.1.1 */
				// Start line: 674
				// Start offset: 0x80037298
				// Variables:
					struct CdlLOC loc; // stack offset -16
			/* end block 1.1.1 */
			// End offset: 0x80037298
			// End Line: 675
		/* end block 1.1 */
		// End offset: 0x80037304
		// End Line: 699
	/* end block 1 */
	// End offset: 0x80037304
	// End Line: 701

	/* begin block 2 */
		// Start line: 1179
	/* end block 2 */
	// End Line: 1180

}


// autogenerated function stub: 
// char * /*$ra*/ LOAD_ReadFileFromCD(char *filename /*$s1*/, int memType /*$s2*/)
char * LOAD_ReadFileFromCD(char *filename, int memType)
{ // line 705, offset 0x80037314
	/* begin block 1 */
		// Start line: 706
		// Start offset: 0x80037314
		// Variables:
			struct CdlFILE fp; // stack offset -40
			int i; // $s0
			char *readBuffer; // $s0
	/* end block 1 */
	// End offset: 0x800373DC
	// End Line: 750

	/* begin block 2 */
		// Start line: 1336
	/* end block 2 */
	// End Line: 1337

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_CdReadFromBigFile(long fileOffset /*$a0*/, unsigned long *loadAddr /*$a1*/, long bytes /*$a2*/, long chksumLevel /*$a3*/, long checksum /*stack 16*/)
void LOAD_CdReadFromBigFile(long fileOffset, unsigned long *loadAddr, long bytes, long chksumLevel, long checksum)
{ // line 752, offset 0x800373f4
	/* begin block 1 */
		// Start line: 1449
	/* end block 1 */
	// End Line: 1450

}


// autogenerated function stub: 
// struct _BigFileDir * /*$ra*/ LOAD_ReadDirectory(struct _BigFileDirEntry *dirEntry /*$s0*/)
struct _BigFileDir * LOAD_ReadDirectory(struct _BigFileDirEntry *dirEntry)
{ // line 765, offset 0x80037420
	/* begin block 1 */
		// Start line: 766
		// Start offset: 0x80037420
		// Variables:
			struct _BigFileDir *dir; // $s2
			long sizeOfDir; // $s1
	/* end block 1 */
	// End offset: 0x80037420
	// End Line: 766

	/* begin block 2 */
		// Start line: 1479
	/* end block 2 */
	// End Line: 1480

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_InitCdLoader(char *bigFileName /*$s0*/, char *voiceFileName /*$a1*/)
void LOAD_InitCdLoader(char *bigFileName, char *voiceFileName)
{ // line 828, offset 0x80037488
	/* begin block 1 */
		// Start line: 829
		// Start offset: 0x80037488
		// Variables:
			struct CdlFILE fp; // stack offset -40
			long i; // $s1

		/* begin block 1.1 */
			// Start line: 896
			// Start offset: 0x80037538
			// Variables:
				char *ptr; // $s0
		/* end block 1.1 */
		// End offset: 0x800375A0
		// End Line: 920
	/* end block 1 */
	// End offset: 0x800375C8
	// End Line: 932

	/* begin block 2 */
		// Start line: 1607
	/* end block 2 */
	// End Line: 1608

}


// autogenerated function stub: 
// int /*$ra*/ LOAD_SetupFileInfo(struct _NonBlockLoadEntry *loadEntry /*$s0*/)
int LOAD_SetupFileInfo(struct _NonBlockLoadEntry *loadEntry)
{ // line 934, offset 0x800375dc
	/* begin block 1 */
		// Start line: 935
		// Start offset: 0x800375DC
		// Variables:
			struct _BigFileEntry *fileInfo; // $v1
	/* end block 1 */
	// End offset: 0x80037654
	// End Line: 958

	/* begin block 2 */
		// Start line: 1869
	/* end block 2 */
	// End Line: 1870

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_CD_ReadPartOfFile(struct _NonBlockLoadEntry *loadEntry /*$s0*/)
void LOAD_CD_ReadPartOfFile(struct _NonBlockLoadEntry *loadEntry)
{ // line 963, offset 0x80037664
	/* begin block 1 */
		// Start line: 964
		// Start offset: 0x80037664
		// Variables:
			struct _ReadQueueEntry *currentQueueReq; // $v1
	/* end block 1 */
	// End offset: 0x800376F4
	// End Line: 989

	/* begin block 2 */
		// Start line: 1928
	/* end block 2 */
	// End Line: 1929

}


// autogenerated function stub: 
// long /*$ra*/ LOAD_HashName(char *string /*stack 0*/)
long LOAD_HashName(char *string)
{ // line 1002, offset 0x80037704
	/* begin block 1 */
		// Start line: 1003
		// Start offset: 0x80037704
		// Variables:
			long sum; // $s5
			long xor; // $s6
			long length; // $s4
			long ext; // $s7
			char c; // $v1
			long strl; // $s2
			long endPos; // $fp
			long i; // $s0
			char *pos; // $s3
	/* end block 1 */
	// End offset: 0x80037814
	// End Line: 1046

	/* begin block 2 */
		// Start line: 2014
	/* end block 2 */
	// End Line: 2015

	return 0;
}


// autogenerated function stub: 
// long /*$ra*/ LOAD_HashUnit(char *name /*$a0*/)
long LOAD_HashUnit(char *name)
{ // line 1049, offset 0x80037858
	/* begin block 1 */
		// Start line: 1051
		// Start offset: 0x80037858
		// Variables:
			int val; // $v1
			int last; // $t0
			int hash; // $a2
			int num; // $a3
			int flag; // $t1
			char *c; // $a0
	/* end block 1 */
	// End offset: 0x800378EC
	// End Line: 1085

	/* begin block 2 */
		// Start line: 2121
	/* end block 2 */
	// End Line: 2122

	/* begin block 3 */
		// Start line: 2122
	/* end block 3 */
	// End Line: 2123

	/* begin block 4 */
		// Start line: 2123
	/* end block 4 */
	// End Line: 2124

	return 0;
}


// autogenerated function stub: 
// struct _BigFileEntry * /*$ra*/ LOAD_GetBigFileEntryByHash(long hash /*$a0*/)
struct _BigFileEntry * LOAD_GetBigFileEntryByHash(long hash)
{ // line 1090, offset 0x800378fc
	/* begin block 1 */
		// Start line: 1092
		// Start offset: 0x800378FC
		// Variables:
			int i; // $a1
			struct _BigFileEntry *entry; // $v1
	/* end block 1 */
	// End offset: 0x8003797C
	// End Line: 1111

	/* begin block 2 */
		// Start line: 2226
	/* end block 2 */
	// End Line: 2227

	/* begin block 3 */
		// Start line: 2227
	/* end block 3 */
	// End Line: 2228

	/* begin block 4 */
		// Start line: 2230
	/* end block 4 */
	// End Line: 2231

	return null;
}


// autogenerated function stub: 
// struct _BigFileEntry * /*$ra*/ LOAD_GetBigFileEntry(char *fileName /*$a0*/)
struct _BigFileEntry * LOAD_GetBigFileEntry(char *fileName)
{ // line 1113, offset 0x80037984
	/* begin block 1 */
		// Start line: 1114
		// Start offset: 0x80037984
	/* end block 1 */
	// End offset: 0x80037984
	// End Line: 1114

	/* begin block 2 */
		// Start line: 2277
	/* end block 2 */
	// End Line: 2278

	return null;
}


// autogenerated function stub: 
// long /*$ra*/ LOAD_DoesFileExist(char *fileName /*$a0*/)
long LOAD_DoesFileExist(char *fileName)
{ // line 1169, offset 0x800379ac
	/* begin block 1 */
		// Start line: 1170
		// Start offset: 0x800379AC
		// Variables:
			struct _BigFileEntry *entry; // $v0
	/* end block 1 */
	// End offset: 0x800379D0
	// End Line: 1175

	/* begin block 2 */
		// Start line: 2338
	/* end block 2 */
	// End Line: 2339

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_NonBlockingReadFile(struct _NonBlockLoadEntry *loadEntry /*$s0*/)
void LOAD_NonBlockingReadFile(struct _NonBlockLoadEntry *loadEntry)
{ // line 1181, offset 0x800379e0
	/* begin block 1 */
		// Start line: 2363
	/* end block 1 */
	// End Line: 2364

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_LoadTIM(long *addr /*$a1*/, long x_pos /*$t0*/, long y_pos /*$a2*/, long clut_x /*$s1*/, long clut_y /*stack 16*/)
void LOAD_LoadTIM(long *addr, long x_pos, long y_pos, long clut_x, long clut_y)
{ // line 1226, offset 0x80037a9c
	/* begin block 1 */
		// Start line: 1227
		// Start offset: 0x80037A9C
		// Variables:
			struct RECT rect; // stack offset -24
			long *clutAddr; // $s0
	/* end block 1 */
	// End offset: 0x80037B28
	// End Line: 1256

	/* begin block 2 */
		// Start line: 2453
	/* end block 2 */
	// End Line: 2454

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_LoadTIM2(long *addr /*$a1*/, long x_pos /*$a1*/, long y_pos /*$a2*/, long width /*$a3*/, long height /*stack 16*/)
void LOAD_LoadTIM2(long *addr, long x_pos, long y_pos, long width, long height)
{ // line 1258, offset 0x80037b3c
	/* begin block 1 */
		// Start line: 1259
		// Start offset: 0x80037B3C
		// Variables:
			struct RECT rect; // stack offset -16
	/* end block 1 */
	// End offset: 0x80037B3C
	// End Line: 1259

	/* begin block 2 */
		// Start line: 2525
	/* end block 2 */
	// End Line: 2526

}


// autogenerated function stub: 
// long /*$ra*/ LOAD_RelocBinaryData(long *data /*$s0*/, long fileSize /*$s1*/)
long LOAD_RelocBinaryData(long *data, long fileSize)
{ // line 1296, offset 0x80037b84
	/* begin block 1 */
		// Start line: 1297
		// Start offset: 0x80037B84
		// Variables:
			long *lastMoveDest; // $v1
			long tableSize; // $s3
			struct RedirectList redirectListX; // stack offset -32
			struct RedirectList *redirectList; // $a0
	/* end block 1 */
	// End offset: 0x80037C1C
	// End Line: 1317

	/* begin block 2 */
		// Start line: 2592
	/* end block 2 */
	// End Line: 2593

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_CleanUpBuffers()
void LOAD_CleanUpBuffers()
{ // line 1389, offset 0x80037c3c
	/* begin block 1 */
		// Start line: 2778
	/* end block 1 */
	// End Line: 2779

	/* begin block 2 */
		// Start line: 2711
	/* end block 2 */
	// End Line: 2712

}


// autogenerated function stub: 
// void * /*$ra*/ LOAD_InitBuffers()
void * LOAD_InitBuffers()
{ // line 1403, offset 0x80037c84
	/* begin block 1 */
		// Start line: 2739
	/* end block 1 */
	// End Line: 2740

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_InitCdStreamMode()
void LOAD_InitCdStreamMode()
{ // line 1418, offset 0x80037cd4
	/* begin block 1 */
		// Start line: 1419
		// Start offset: 0x80037CD4
		// Variables:
			unsigned char cdMode; // stack offset -16
	/* end block 1 */
	// End offset: 0x80037CD4
	// End Line: 1419

	/* begin block 2 */
		// Start line: 2772
	/* end block 2 */
	// End Line: 2773

}


// autogenerated function stub: 
// void /*$ra*/ LOAD_DumpCurrentDir()
void LOAD_DumpCurrentDir()
{ // line 1428, offset 0x80037d1c
	/* begin block 1 */
		// Start line: 2795
	/* end block 1 */
	// End Line: 2796

	/* begin block 2 */
		// Start line: 2796
	/* end block 2 */
	// End Line: 2797

}


// autogenerated function stub: 
// int /*$ra*/ LOAD_ChangeDirectoryByID(int id /*$s1*/)
int LOAD_ChangeDirectoryByID(int id)
{ // line 1444, offset 0x80037d6c
	/* begin block 1 */
		// Start line: 1445
		// Start offset: 0x80037D6C

		/* begin block 1.1 */
			// Start line: 1449
			// Start offset: 0x80037D84
			// Variables:
				int i; // $v1

			/* begin block 1.1.1 */
				// Start line: 1456
				// Start offset: 0x80037DA4
				// Variables:
					struct _BigFileDir *dir; // $a0
			/* end block 1.1.1 */
			// End offset: 0x80037DC4
			// End Line: 1462
		/* end block 1.1 */
		// End offset: 0x80037E5C
		// End Line: 1481
	/* end block 1 */
	// End offset: 0x80037E60
	// End Line: 1484

	/* begin block 2 */
		// Start line: 2828
	/* end block 2 */
	// End Line: 2829

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_SetSearchDirectory(long id /*$a0*/)
void LOAD_SetSearchDirectory(long id)
{ // line 1491, offset 0x80037e74
	/* begin block 1 */
		// Start line: 2982
	/* end block 1 */
	// End Line: 2983

	/* begin block 2 */
		// Start line: 2937
	/* end block 2 */
	// End Line: 2938

}


// autogenerated function stub: 
// long /*$ra*/ LOAD_GetSearchDirectory()
long LOAD_GetSearchDirectory()
{ // line 1496, offset 0x80037e80
	/* begin block 1 */
		// Start line: 2946
	/* end block 1 */
	// End Line: 2947

	/* begin block 2 */
		// Start line: 2947
	/* end block 2 */
	// End Line: 2948

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ LOAD_ChangeDirectoryFlag()
int LOAD_ChangeDirectoryFlag()
{ // line 1501, offset 0x80037e8c
	/* begin block 1 */
		// Start line: 2956
	/* end block 1 */
	// End Line: 2957

	/* begin block 2 */
		// Start line: 2957
	/* end block 2 */
	// End Line: 2958

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_UpdateBigFilePointers(struct _BigFileDir *oldDir /*$a0*/, struct _BigFileDir *newDir /*$a1*/)
void LOAD_UpdateBigFilePointers(struct _BigFileDir *oldDir, struct _BigFileDir *newDir)
{ // line 1506, offset 0x80037e98
	/* begin block 1 */
		// Start line: 2966
	/* end block 1 */
	// End Line: 2967

	/* begin block 2 */
		// Start line: 2967
	/* end block 2 */
	// End Line: 2968

}


// autogenerated function stub: 
// int /*$ra*/ LOAD_IsFileLoading()
int LOAD_IsFileLoading()
{ // line 1521, offset 0x80037ec8
	/* begin block 1 */
		// Start line: 2996
	/* end block 1 */
	// End Line: 2997

	/* begin block 2 */
		// Start line: 3002
	/* end block 2 */
	// End Line: 3003

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ LOAD_StopLoad()
void LOAD_StopLoad()
{ // line 1563, offset 0x80037ed4
	/* begin block 1 */
		// Start line: 3126
	/* end block 1 */
	// End Line: 3127

	/* begin block 2 */
		// Start line: 3048
	/* end block 2 */
	// End Line: 3049

}




