if(WINDOWS_STORE AND DEFINED PLATFORM_DURANGO)

target_link_directories(${PROJECT_NAME} PUBLIC ${ROOT_DIR}/Build_Durango/Emulator/$(Configuration))
target_link_libraries(${PROJECT_NAME} xaudio2.lib)
set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${LINK_FLAGS} /LARGEADDRESSAWARE:NO")

set(CMAKE_C_FLAGS           "${CMAKE_C_FLAGS} /ZW")
set(CMAKE_C_FLAGS_DEBUG     "${CMAKE_C_FLAGS_DEBUG} /ZW")
set(CMAKE_C_FLAGS_RELEASE   "${CMAKE_C_FLAGS_RELEASE} /ZW")
set(CMAKE_CXX_FLAGS         "${CMAKE_CXX_FLAGS} /ZW")
set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG} /ZW")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /ZW")

add_definitions(-D_CRT_SECURE_NO_WARNINGS)

set(PSX_LIB Valkyrie.lib)

endif()