#include "CORE.H"
#include "AADSEQEV.H"
#include "AADLIB.H"


char midiDataByteCount[8];

int aadQueueNextEvent(struct _AadSequenceSlot *slot, int track)
{
	struct AadSeqEvent seqEvent;
	unsigned char* seqData;
	unsigned long deltaTime;
	int c;
	int n;
	int i;
	
	if ((slot->trackFlags[track] & 0x18))
	{
		return -1;
	}
	
	if ((slot->trackFlags[track] & 0x20))
	{
		deltaTime = slot->tempo.currentTick;
		slot->eventsInQueue[track] = deltaTime;
		slot->trackFlags[track] &= 0xDF;
	}
	
	seqData = slot->sequencePosition[track];

	if (*seqData++ & 0x80)
	{
		deltaTime &= 0x7F;

		do
		{
			deltaTime = (deltaTime << 7) | (*seqData & 0x7F);

		} while (*seqData++ & 0x80);
	}

	seqEvent.track = track;
	seqEvent.deltaTime = deltaTime;

	if (*seqData == 0xFF)
	{
		seqData++;
		seqEvent.statusByte = *seqData++;
		
		if (seqEvent.statusByte == 0x44)
		{
			slot->trackFlags[track] |= 0x8;
		}
		else if (seqEvent.statusByte == 0x2E)
		{
			slot->trackFlags[track] |= 0x10;
		}
	}
	else 
	{
		if (*seqData & 0x80)
		{
			seqEvent.statusByte = *seqData;
			slot->runningStatus[track] = *seqData++;
		}
		else
		{
			seqEvent.statusByte = slot->runningStatus[track];
		}
		
		n = midiDataByteCount[(seqEvent.statusByte << 4) & 0x7];
	}

	i = 0;
	while (--n != -1)
	{
		seqEvent.dataByte[i++] = *seqData++;
	}

	slot->sequencePosition[track] = seqData;
	c = slot->eventIn[track];

	slot->eventQueue[c][track] = seqEvent;
	slot->eventsInQueue[track]++;
	slot->eventIn[track]++;

	if (slot->eventIn[track] == 4)
	{
		slot->eventIn[track] = 0;
	}

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ aadExecuteEvent(struct AadSeqEvent *event /*$s0*/, struct _AadSequenceSlot *slot /*$s1*/)
void aadExecuteEvent(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 103, offset 0x80054adc
#if defined(PC_VERSION)
	if ((event->statusByte & 0x80u) == 0)
	{
		aadSubstituteVariables(event, slot);
		if (event->statusByte < 0x4Eu)
			//((void(__cdecl*)(struct AadSeqEvent*))funcs_4351D4[event->statusByte & 0x7F])(event)
			;
	}
	else
	{
		//((void(__cdecl*)(struct AadSeqEvent*, struct _AadSequenceSlot*))funcs_4351A9[(v2 >> 4) & 7])(event, slot);
	}
#endif
}


// autogenerated function stub: 
// void /*$ra*/ midiNoteOff(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiNoteOff(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 127, offset 0x80054b74
	/* begin block 1 */
		// Start line: 258
	/* end block 1 */
	// End Line: 259

	/* begin block 2 */
		// Start line: 262
	/* end block 2 */
	// End Line: 263

}


// autogenerated function stub: 
// void /*$ra*/ midiNoteOn(struct AadSeqEvent *event /*$fp*/, struct _AadSequenceSlot *slot /*$s5*/)
void midiNoteOn(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 139, offset 0x80054b7c
	/* begin block 1 */
		// Start line: 140
		// Start offset: 0x80054B7C
		// Variables:
			struct AadProgramAtr *progAtr; // $s4
			struct AadToneAtr *toneAtrTbl; // $v1
			struct AadSynthVoice *voice; // $s0
			int channel; // $s7
			int midiNote; // $s6
			int transposedNote; // stack offset -56
			int t; // $s2
			int dynBank; // stack offset -52

		/* begin block 1.1 */
			// Start line: 220
			// Start offset: 0x80054D5C
			// Variables:
				unsigned long waveStartAddr; // $a1
		/* end block 1.1 */
		// End offset: 0x80054EA4
		// End Line: 245
	/* end block 1 */
	// End offset: 0x80054EC0
	// End Line: 249

	/* begin block 2 */
		// Start line: 282
	/* end block 2 */
	// End Line: 283

}


// autogenerated function stub: 
// void /*$ra*/ aadUpdateChannelVolPan(struct _AadSequenceSlot *slot /*$s4*/, int channel /*$s5*/)
void aadUpdateChannelVolPan(struct _AadSequenceSlot *slot, int channel)
{ // line 253, offset 0x80054ef0
	/* begin block 1 */
		// Start line: 254
		// Start offset: 0x80054EF0
		// Variables:
			struct AadSynthVoice *voice; // $s0
			int i; // $s2
			//struct AadVolume newVoiceVol; // stack offset -40

		/* begin block 1.1 */
			// Start line: 267
			// Start offset: 0x80054F90
			// Variables:
				unsigned long tmp; // $v0
		/* end block 1.1 */
		// End offset: 0x80054F90
		// End Line: 267

		/* begin block 1.2 */
			// Start line: 268
			// Start offset: 0x80054FF8
			// Variables:
				unsigned long masterVolumeSquared; // $v1
		/* end block 1.2 */
		// End offset: 0x80054FF8
		// End Line: 268

		/* begin block 1.3 */
			// Start line: 269
			// Start offset: 0x80055078
			// Variables:
				//unsigned long tmp; // $v0
		/* end block 1.3 */
		// End offset: 0x80055078
		// End Line: 269

		/* begin block 1.4 */
			// Start line: 270
			// Start offset: 0x800550E4
			// Variables:
				//unsigned long masterVolumeSquared; // $v1
		/* end block 1.4 */
		// End offset: 0x800550E4
		// End Line: 270

		/* begin block 1.5 */
			// Start line: 270
			// Start offset: 0x800550E4
			// Variables:
				//unsigned long masterVolumeSquared; // $v0
		/* end block 1.5 */
		// End offset: 0x800550E4
		// End Line: 270

		/* begin block 1.6 */
			// Start line: 270
			// Start offset: 0x800550E4
			// Variables:
				//unsigned long masterVolumeSquared; // $v0
		/* end block 1.6 */
		// End offset: 0x800550E4
		// End Line: 270

		/* begin block 1.7 */
			// Start line: 270
			// Start offset: 0x800550E4
			// Variables:
				//unsigned long masterVolumeSquared; // $v0
		/* end block 1.7 */
		// End offset: 0x800550E4
		// End Line: 270
	/* end block 1 */
	// End offset: 0x80055250
	// End Line: 282

	/* begin block 2 */
		// Start line: 583
	/* end block 2 */
	// End Line: 584

}


// autogenerated function stub: 
// void /*$ra*/ aadUpdateSlotVolPan(struct _AadSequenceSlot *slot /*$s1*/)
void aadUpdateSlotVolPan(struct _AadSequenceSlot *slot)
{ // line 286, offset 0x80055274
	/* begin block 1 */
		// Start line: 287
		// Start offset: 0x80055274
		// Variables:
			struct AadSynthVoice *voice; // $t0
			int channel; // $t1
			int i; // $s0
			//struct AadVolume newVoiceVol; // stack offset -24

		/* begin block 1.1 */
			// Start line: 302
			// Start offset: 0x80055308
			// Variables:
				unsigned long tmp; // $v0
		/* end block 1.1 */
		// End offset: 0x80055308
		// End Line: 302

		/* begin block 1.2 */
			// Start line: 303
			// Start offset: 0x80055374
			// Variables:
				unsigned long masterVolumeSquared; // $v1
		/* end block 1.2 */
		// End offset: 0x80055374
		// End Line: 303

		/* begin block 1.3 */
			// Start line: 304
			// Start offset: 0x800553F4
			// Variables:
				//unsigned long tmp; // $v0
		/* end block 1.3 */
		// End offset: 0x800553F4
		// End Line: 304

		/* begin block 1.4 */
			// Start line: 305
			// Start offset: 0x80055460
			// Variables:
				//unsigned long masterVolumeSquared; // $v1
		/* end block 1.4 */
		// End offset: 0x80055460
		// End Line: 305

		/* begin block 1.5 */
			// Start line: 305
			// Start offset: 0x80055460
			// Variables:
				//unsigned long masterVolumeSquared; // $v0
		/* end block 1.5 */
		// End offset: 0x80055460
		// End Line: 305

		/* begin block 1.6 */
			// Start line: 305
			// Start offset: 0x80055460
			// Variables:
				//unsigned long masterVolumeSquared; // $v0
		/* end block 1.6 */
		// End offset: 0x80055460
		// End Line: 305

		/* begin block 1.7 */
			// Start line: 305
			// Start offset: 0x80055460
			// Variables:
				//unsigned long masterVolumeSquared; // $v0
		/* end block 1.7 */
		// End offset: 0x80055460
		// End Line: 305
	/* end block 1 */
	// End offset: 0x800555B8
	// End Line: 314

	/* begin block 2 */
		// Start line: 686
	/* end block 2 */
	// End Line: 687

}


// autogenerated function stub: 
// void /*$ra*/ aadUpdateChannelPitchBend(struct _AadSequenceSlot *slot /*$s5*/, int channel /*$s6*/)
void aadUpdateChannelPitchBend(struct _AadSequenceSlot *slot, int channel)
{ // line 318, offset 0x800555d0
	/* begin block 1 */
		// Start line: 319
		// Start offset: 0x800555D0
		// Variables:
			struct AadSynthVoice *voice; // $a0
			int i; // $s0
			int finePitch; // $a1
			int newPitch; // $a1
			int pitchWheelPos; // $s2
			int pitchIndex; // $a0
			long pitchValueBendAmount; // $a2
	/* end block 1 */
	// End offset: 0x80055758
	// End Line: 366

	/* begin block 2 */
		// Start line: 785
	/* end block 2 */
	// End Line: 786

}


// autogenerated function stub: 
// void /*$ra*/ midiPolyphonicAftertouch(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiPolyphonicAftertouch(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 369, offset 0x80055780
	/* begin block 1 */
		// Start line: 974
	/* end block 1 */
	// End Line: 975

	/* begin block 2 */
		// Start line: 975
	/* end block 2 */
	// End Line: 976

}


// autogenerated function stub: 
// void /*$ra*/ midiControlChange(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiControlChange(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 374, offset 0x80055788
	/* begin block 1 */
		// Start line: 375
		// Start offset: 0x80055788
		// Variables:
			int controlNumber; // $v0
	/* end block 1 */
	// End offset: 0x80055788
	// End Line: 375

	/* begin block 2 */
		// Start line: 984
	/* end block 2 */
	// End Line: 985

}


// autogenerated function stub: 
// void /*$ra*/ midiProgramChange(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiProgramChange(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 385, offset 0x800557c4
#if defined(PC_VERSION)
	slot->currentProgram[event->statusByte & 0xF] = event->dataByte[0];
#endif
}


// autogenerated function stub: 
// void /*$ra*/ midiChannelAftertouch(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiChannelAftertouch(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 396, offset 0x800557dc
	/* begin block 1 */
		// Start line: 1030
	/* end block 1 */
	// End Line: 1031

	/* begin block 2 */
		// Start line: 1031
	/* end block 2 */
	// End Line: 1032

}


// autogenerated function stub: 
// void /*$ra*/ midiPitchWheelControl(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a3*/)
void midiPitchWheelControl(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 401, offset 0x800557e4
#if defined(PC_VERSION)
	int v2; // [esp-4h] [ebp-4h]

	v2 = event->statusByte & 0xF;
	slot->pitchWheel[v2] = event->dataByte[0] | ((BYTE)event->dataByte[1] << 7);
	aadUpdateChannelPitchBend(slot, v2);
#endif
}


// autogenerated function stub: 
// void /*$ra*/ midiMetaEvent(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiMetaEvent(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 413, offset 0x8005582c
	/* begin block 1 */
		// Start line: 1067
	/* end block 1 */
	// End Line: 1068

	/* begin block 2 */
		// Start line: 1070
	/* end block 2 */
	// End Line: 1071

}


// autogenerated function stub: 
// void /*$ra*/ midiControlBankSelect(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiControlBankSelect(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 421, offset 0x80055834
	/* begin block 1 */
		// Start line: 1083
	/* end block 1 */
	// End Line: 1084

	/* begin block 2 */
		// Start line: 1104
	/* end block 2 */
	// End Line: 1105

}


// autogenerated function stub: 
// void /*$ra*/ midiControlVolume(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a2*/)
void midiControlVolume(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 446, offset 0x8005583c
#if defined(PC_VERSION)
	int v2 = event->statusByte & 0xF;
	slot->volume[v2] = event->dataByte[1];
	if (((1 << v2) & slot->enableSustainUpdate) != 0)
		aadUpdateChannelVolPan(slot, v2);
#endif
}


// autogenerated function stub: 
// void /*$ra*/ midiControlPan(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a2*/)
void midiControlPan(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 461, offset 0x8005588c
#if defined(PC_VERSION)
	int v2; // ecx

	v2 = event->statusByte & 0xF;
	slot->panPosition[v2] = event->dataByte[1];
	if (((1 << v2) & slot->enableSustainUpdate) != 0)
		aadUpdateChannelVolPan(slot, v2);
#endif
}


// autogenerated function stub: 
// void /*$ra*/ midiControlCallback(struct AadSeqEvent *event /*$a3*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiControlCallback(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 476, offset 0x800558dc
#if defined(PC_VERSION)
	void(__cdecl * v2)(int, DWORD, int, DWORD); // eax

	v2 = *(void(__cdecl**)(int, DWORD, int, DWORD)) & aadMem[3].loadRequestQueue[12].fileName[8];
	if (v2)
		v2(aadMem[3].loadRequestQueue[13].handle, slot->thisSlotNumber, event->statusByte & 0xF, event->dataByte[1]);
#endif
}


// autogenerated function stub: 
// void /*$ra*/ midiControlDummy(struct AadSeqEvent *event /*$a0*/, struct _AadSequenceSlot *slot /*$a1*/)
void midiControlDummy(struct AadSeqEvent *event, struct _AadSequenceSlot *slot)
{ // line 491, offset 0x80055920
	/* begin block 1 */
		// Start line: 1228
	/* end block 1 */
	// End Line: 1229

	/* begin block 2 */
		// Start line: 1229
	/* end block 2 */
	// End Line: 1230

}




