#include "THISDUST.H"
#include "MAIN.H"
#include "G2/MAING2.H"
#include "MEMPACK.H"
#include "LOAD3D.H"

#include <stddef.h>

// autogenerated function stub: 
// void /*$ra*/ ClearDisplay()
void ClearDisplay()
{ // line 136, offset 0x80037ef8
	/* begin block 1 */
		// Start line: 272
	/* end block 1 */
	// End Line: 273

	/* begin block 2 */
		// Start line: 274
	/* end block 2 */
	// End Line: 275

}


// autogenerated function stub: 
// void /*$ra*/ screen_to_vram(long *screen /*$a0*/, int buffer /*$a1*/)
void screen_to_vram(long *screen, int buffer)
{ // line 150, offset 0x80037fb4
	/* begin block 1 */
		// Start line: 302
	/* end block 1 */
	// End Line: 303

}


// autogenerated function stub: 
// void /*$ra*/ show_screen(char *name /*$a0*/)
void show_screen(char *name)
{ // line 159, offset 0x80037fe4
	/* begin block 1 */
		// Start line: 160
		// Start offset: 0x80037FE4
		// Variables:
			long *screen; // $s0
	/* end block 1 */
	// End offset: 0x80038018
	// End Line: 167

	/* begin block 2 */
		// Start line: 324
	/* end block 2 */
	// End Line: 325

}


// autogenerated function stub: 
// void /*$ra*/ play_movie(char *name /*$s0*/)
void play_movie(char *name)
{ // line 214, offset 0x80038028
	/* begin block 1 */
		// Start line: 435
	/* end block 1 */
	// End Line: 436

}


// autogenerated function stub: 
// void /*$ra*/ InitMainTracker(struct MainTracker *mainTracker /*$a0*/)
void InitMainTracker(struct MainTracker *mainTracker)
{ // line 236, offset 0x80038070
	/* begin block 1 */
		// Start line: 479
	/* end block 1 */
	// End Line: 480

	/* begin block 2 */
		// Start line: 480
	/* end block 2 */
	// End Line: 481

}


// autogenerated function stub: 
// char * /*$ra*/ FindTextInLine(char *search_match /*$a0*/, char *search_str /*$a1*/)
char * FindTextInLine(char *search_match, char *search_str)
{ // line 243, offset 0x80038080
	/* begin block 1 */
		// Start line: 245
		// Start offset: 0x80038080
		// Variables:
			char *match_pos; // $a2
	/* end block 1 */
	// End offset: 0x800380F8
	// End Line: 259

	/* begin block 2 */
		// Start line: 493
	/* end block 2 */
	// End Line: 494

	/* begin block 3 */
		// Start line: 494
	/* end block 3 */
	// End Line: 495

	/* begin block 4 */
		// Start line: 496
	/* end block 4 */
	// End Line: 497

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ ExtractWorldName(char *worldName /*$a0*/, char *levelName /*$a1*/)
void ExtractWorldName(char *worldName, char *levelName)
{ // line 261, offset 0x80038108
	/* begin block 1 */
		// Start line: 529
	/* end block 1 */
	// End Line: 530

	/* begin block 2 */
		// Start line: 530
	/* end block 2 */
	// End Line: 531

}


// autogenerated function stub: 
// void /*$ra*/ ExtractLevelNum(char *levelNum /*$a0*/, char *levelName /*$a1*/)
void ExtractLevelNum(char *levelNum, char *levelName)
{ // line 270, offset 0x80038154
	/* begin block 1 */
		// Start line: 547
	/* end block 1 */
	// End Line: 548

	/* begin block 2 */
		// Start line: 548
	/* end block 2 */
	// End Line: 549

}


// autogenerated function stub: 
// void /*$ra*/ ProcessArgs(char *baseAreaName /*$s3*/, struct GameTracker *gameTracker /*$s2*/)
void ProcessArgs(char *baseAreaName, struct GameTracker *gameTracker)
{ // line 368, offset 0x800381c0
	/* begin block 1 */
		// Start line: 369
		// Start offset: 0x800381C0
		// Variables:
			char levelNum[32]; // stack offset -88
			char worldName[32]; // stack offset -56
			long *argData; // $s1
	/* end block 1 */
	// End offset: 0x800383BC
	// End Line: 586

	/* begin block 2 */
		// Start line: 736
	/* end block 2 */
	// End Line: 737

}


// autogenerated function stub: 
// void /*$ra*/ InitDisplay()
void InitDisplay()
{ // line 588, offset 0x800383d8
	/* begin block 1 */
		// Start line: 589
		// Start offset: 0x800383D8
		// Variables:
			int i; // $a1
			struct RECT r; // stack offset -16
	/* end block 1 */
	// End offset: 0x80038510
	// End Line: 650

	/* begin block 2 */
		// Start line: 1134
	/* end block 2 */
	// End Line: 1135

}

void StartTimer()
{
#ifdef PSX_VERSION
	EnterCriticalSection();
	__timerEvent = OpenEvent(0xF2000000, 2, 0x1000, &TimerTick);
	EnableEvent(__timerEvent);
	SetRCnt(0xF2000000, 0xFFFF, 0x1001);
	StartRCnt(0xF2000000);
	ExitCriticalSection();
	gTimerEnabled = 1;
#endif
}


// autogenerated function stub: 
// void /*$ra*/ VblTick()
void VblTick()
{ // line 739, offset 0x800385c0
	/* begin block 1 */
		// Start line: 1473
	/* end block 1 */
	// End Line: 1474

	/* begin block 2 */
		// Start line: 1476
	/* end block 2 */
	// End Line: 1477

}


// autogenerated function stub: 
// void /*$ra*/ DrawCallback()
void DrawCallback()
{ // line 759, offset 0x8003862c
	/* begin block 1 */
		// Start line: 1520
	/* end block 1 */
	// End Line: 1521

	/* begin block 2 */
		// Start line: 1521
	/* end block 2 */
	// End Line: 1522

}


// autogenerated function stub: 
// void /*$ra*/ FadeOutSayingLoading(struct GameTracker *gameTracker /*$s1*/)
void FadeOutSayingLoading(struct GameTracker *gameTracker)
{ // line 770, offset 0x80038684
	/* begin block 1 */
		// Start line: 771
		// Start offset: 0x80038684
		// Variables:
			struct POLY_F4_SEMITRANS *transPrim; // $s2
			unsigned long **drawot; // $s3
			long fadeTime; // $s0
	/* end block 1 */
	// End offset: 0x800387B4
	// End Line: 804

	/* begin block 2 */
		// Start line: 1544
	/* end block 2 */
	// End Line: 1545

}

void CheckForDevStation()
{
	long* a1 = (long*)0x80180000;
	long* a2 = (long*)0x80380000;

	a1[0] = 0x12340000;
	a2[0] = 0x12345678;

	if (a1[0] == a2[0])
	{
		devstation = 0;
	}
	else
	{
		devstation = 1;
	}
}


// autogenerated function stub: 
// void /*$ra*/ MAIN_ShowLoadingScreen()
void MAIN_ShowLoadingScreen()
{ // line 834, offset 0x80038834
	/* begin block 1 */
		// Start line: 835
		// Start offset: 0x80038834
		// Variables:
			long *loadingScreen; // $s0
			char langChar[5]; // stack offset -88
			int lang; // $v0

		/* begin block 1.1 */
			// Start line: 856
			// Start offset: 0x8003887C
			// Variables:
				char filename[64]; // stack offset -80
		/* end block 1.1 */
		// End offset: 0x8003887C
		// End Line: 857
	/* end block 1 */
	// End offset: 0x800388D0
	// End Line: 877

	/* begin block 2 */
		// Start line: 1695
	/* end block 2 */
	// End Line: 1696

}


// autogenerated function stub: 
// long * /*$ra*/ MAIN_LoadTim(char *name /*$a0*/)
long * MAIN_LoadTim(char *name)
{ // line 879, offset 0x800388e4
	/* begin block 1 */
		// Start line: 880
		// Start offset: 0x800388E4
	/* end block 1 */
	// End offset: 0x800388E4
	// End Line: 880

	/* begin block 2 */
		// Start line: 1804
	/* end block 2 */
	// End Line: 1805

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ init_menus(struct GameTracker *gt /*$s1*/)
void init_menus(struct GameTracker *gt)
{ // line 890, offset 0x80038904
	/* begin block 1 */
		// Start line: 891
		// Start offset: 0x80038904
		// Variables:
			struct menu_t *menu; // $s0
	/* end block 1 */
	// End offset: 0x80038904
	// End Line: 891

	/* begin block 2 */
		// Start line: 1826
	/* end block 2 */
	// End Line: 1827

}


// autogenerated function stub: 
// void /*$ra*/ MAIN_DoMainInit()
void MAIN_DoMainInit()
{ // line 902, offset 0x80038950
	/* begin block 1 */
		// Start line: 1850
	/* end block 1 */
	// End Line: 1851

}


// autogenerated function stub: 
// void /*$ra*/ MAIN_InitVolume()
void MAIN_InitVolume()
{ // line 949, offset 0x80038a44
	/* begin block 1 */
		// Start line: 1898
	/* end block 1 */
	// End Line: 1899

}


// autogenerated function stub: 
// void /*$ra*/ MAIN_ResetGame()
void MAIN_ResetGame()
{ // line 957, offset 0x80038a84
	/* begin block 1 */
		// Start line: 1944
	/* end block 1 */
	// End Line: 1945

}


// autogenerated function stub: 
// void /*$ra*/ MAIN_MainMenuInit()
void MAIN_MainMenuInit()
{ // line 967, offset 0x80038ad4
	/* begin block 1 */
		// Start line: 968
		// Start offset: 0x80038AD4

		/* begin block 1.1 */
			// Start line: 968
			// Start offset: 0x80038AD4
			// Variables:
				char sfxFileName[64]; // stack offset -72
		/* end block 1.1 */
		// End offset: 0x80038C18
		// End Line: 990
	/* end block 1 */
	// End offset: 0x80038C18
	// End Line: 995

	/* begin block 2 */
		// Start line: 1965
	/* end block 2 */
	// End Line: 1966

}


// autogenerated function stub: 
// void /*$ra*/ MAIN_FreeMainMenuStuff()
void MAIN_FreeMainMenuStuff()
{ // line 1009, offset 0x80038c6c
	/* begin block 1 */
		// Start line: 2066
	/* end block 1 */
	// End Line: 2067

}


// autogenerated function stub: 
// void /*$ra*/ MAIN_StartGame()
void MAIN_StartGame()
{ // line 1044, offset 0x80038cdc
	/* begin block 1 */
		// Start line: 2136
	/* end block 1 */
	// End Line: 2137

	/* begin block 2 */
		// Start line: 2137
	/* end block 2 */
	// End Line: 2138

}


// autogenerated function stub: 
// long /*$ra*/ MAIN_DoMainMenu(struct GameTracker *gameTracker /*$s0*/, struct MainTracker *mainTracker /*$a1*/, long menuPos /*$a2*/)
long MAIN_DoMainMenu(struct GameTracker *gameTracker, struct MainTracker *mainTracker, long menuPos)
{ // line 1083, offset 0x80038d48
	/* begin block 1 */
		// Start line: 1084
		// Start offset: 0x80038D48
		// Variables:
			unsigned long **drawot; // $s1
	/* end block 1 */
	// End offset: 0x80038E04
	// End Line: 1172

	/* begin block 2 */
		// Start line: 2220
	/* end block 2 */
	// End Line: 2221

	return 0;
}

int MainG2(void *appData)
{ 
	return 0;
}




