#ifndef SNMAIN_H
#define SNMAIN_H


extern void __SN_ENTRY_POINT() ; // 0x800B6D2C

extern void __main() ; // 0x800B6DD4

extern void __initialised() ; // 0x800CAD6C

extern void __heapbase() ; // 0x800CAD70

extern void __heapsize() ; // 0x800CAD74

extern void __text() ; // 0x800CAD78

extern void __textlen() ; // 0x800CAD7C

extern void __data() ; // 0x800CAD80

extern void __datalen() ; // 0x800CAD84

extern void __bss() ; // 0x800CAD88

extern void __bsslen() ; // 0x800CAD8C

extern void the_cine_table() ; // 0x800CAD90

extern void __ra_temp() ; // 0x800D5AD0

extern void voiceTracker() ; // 0x800D5AD4


#endif
