#include "Game/CORE.H"
#include "PLANPOOL.H"


int PLANPOOL_NumNodesInPlan(struct PlanningNode* goalNode, struct PlanningNode* planningPool)//Matching - 93.42%
{
	struct PlanningNode* currentNode;
	int i;

	for (i = 0, currentNode = &planningPool[goalNode->parent]; goalNode != currentNode; i++)
	{
		goalNode = &planningPool[currentNode->parent];

		currentNode = &planningPool[goalNode->parent];
	}

	return i + 1;
}

int PLANPOOL_CountBitsSetInLong(long mylong)//Matching - 100%
{
	int numBitsSet;

	for (numBitsSet = 0; mylong; numBitsSet++)
	{
		mylong &= (mylong - 1);
	}

	return numBitsSet;
}

int PLANPOOL_NumConnectionsExaminedForNode(struct PlanningNode* node)
{
	return PLANPOOL_CountBitsSetInLong(node->connectionStatus);
}

int PLANPOOL_NumConnectionsForNode(struct PlanningNode* node)
{
	return PLANPOOL_CountBitsSetInLong(node->connections);
}


// autogenerated function stub: 
// struct PlanningNode * /*$ra*/ PLANPOOL_GetFirstNodeOfSource(struct PlanningNode *planningPool /*$a0*/, char nodeSource /*$a1*/)
struct PlanningNode * PLANPOOL_GetFirstNodeOfSource(struct PlanningNode *planningPool, char nodeSource)
{ // line 177, offset 0x800992bc
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x800992BC
		// Variables:
			int i; // $v1
	/* end block 1 */
	// End offset: 0x80099304
	// End Line: 186

	/* begin block 2 */
		// Start line: 354
	/* end block 2 */
	// End Line: 355

	/* begin block 3 */
		// Start line: 342
	/* end block 3 */
	// End Line: 343
			UNIMPLEMENTED();
	return null;
}


// autogenerated function stub: 
// int /*$ra*/ PLANPOOL_NumberOfNodesOfType(struct PlanningNode *planningPool /*$a0*/, char nodeType /*$a1*/)
int PLANPOOL_NumberOfNodesOfType(struct PlanningNode *planningPool, char nodeType)
{ // line 189, offset 0x8009930c
	/* begin block 1 */
		// Start line: 190
		// Start offset: 0x8009930C
		// Variables:
			int i; // $a2
			int numNodesOfType; // $v1
	/* end block 1 */
	// End offset: 0x80099350
	// End Line: 197

	/* begin block 2 */
		// Start line: 364
	/* end block 2 */
	// End Line: 365

	/* begin block 3 */
		// Start line: 367
	/* end block 3 */
	// End Line: 368
			UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ PLANPOOL_NumberOfNodesOfSource(struct PlanningNode *planningPool /*$a0*/, char nodeSource /*$a1*/)
int PLANPOOL_NumberOfNodesOfSource(struct PlanningNode *planningPool, char nodeSource)
{ // line 201, offset 0x80099358
	/* begin block 1 */
		// Start line: 202
		// Start offset: 0x80099358
		// Variables:
			int i; // $a2
			int numNodesOfSource; // $v1
	/* end block 1 */
	// End offset: 0x800993A0
	// End Line: 209

	/* begin block 2 */
		// Start line: 389
	/* end block 2 */
	// End Line: 390

	/* begin block 3 */
		// Start line: 392
	/* end block 3 */
	// End Line: 393
			UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// struct PlanningNode * /*$ra*/ PLANPOOL_GetNodeWithID(struct PlanningNode *planningPool /*$a0*/, int type /*$a1*/, int id /*$a2*/, long suID /*$a3*/)
struct PlanningNode * PLANPOOL_GetNodeWithID(struct PlanningNode *planningPool, int type, int id, long suID)
{ // line 213, offset 0x800993a8
	/* begin block 1 */
		// Start line: 215
		// Start offset: 0x800993A8
		// Variables:
			int i; // $v1
	/* end block 1 */
	// End offset: 0x8009940C
	// End Line: 224

	/* begin block 2 */
		// Start line: 414
	/* end block 2 */
	// End Line: 415

	/* begin block 3 */
		// Start line: 415
	/* end block 3 */
	// End Line: 416

	/* begin block 4 */
		// Start line: 417
	/* end block 4 */
	// End Line: 418
			UNIMPLEMENTED();
	return null;
}


// autogenerated function stub: 
// struct PlanningNode * /*$ra*/ PLANPOOL_GetNodeByPosition(_Position *currentPos /*$s3*/, struct PlanningNode *planningPool /*$a1*/)
struct PlanningNode * PLANPOOL_GetNodeByPosition(_Position *currentPos, struct PlanningNode *planningPool)
{ // line 230, offset 0x80099414
	/* begin block 1 */
		// Start line: 231
		// Start offset: 0x80099414
		// Variables:
			int i; // $s1
			unsigned long zDiff; // $v0
			unsigned long minZDiff; // $s4
			struct PlanningNode *returnNode; // $s2
	/* end block 1 */
	// End offset: 0x800994C4
	// End Line: 247

	/* begin block 2 */
		// Start line: 451
	/* end block 2 */
	// End Line: 452

	/* begin block 3 */
		// Start line: 456
	/* end block 3 */
	// End Line: 457
			UNIMPLEMENTED();
	return null;
}


// autogenerated function stub: 
// struct PlanningNode * /*$ra*/ PLANPOOL_GetClosestNode(_Position *pos /*$s1*/, struct PlanningNode *planningPool /*$a1*/, char distanceType /*$s5*/)
struct PlanningNode * PLANPOOL_GetClosestNode(_Position *pos, struct PlanningNode *planningPool, char distanceType)
{ // line 251, offset 0x800994e8
	/* begin block 1 */
		// Start line: 252
		// Start offset: 0x800994E8
		// Variables:
			int i; // $s2
			long dist; // $v1
			long minDist; // $s4
			struct PlanningNode *closestNode; // $s3
	/* end block 1 */
	// End offset: 0x800995C0
	// End Line: 270

	/* begin block 2 */
		// Start line: 514
	/* end block 2 */
	// End Line: 515
			UNIMPLEMENTED();
	return null;
}


// autogenerated function stub: 
// int /*$ra*/ PLANPOOL_AppropriatePair(struct PlanningNode *node1 /*$t1*/, struct PlanningNode *node2 /*$a1*/)
int PLANPOOL_AppropriatePair(struct PlanningNode *node1, struct PlanningNode *node2)
{ // line 277, offset 0x800995e8
	/* begin block 1 */
		// Start line: 278
		// Start offset: 0x800995E8
		// Variables:
			struct PlanningNode *temp; // $v0
			int res; // $s0
			int src; // $a0
			int plc; // $v1
			short type1; // $a0
			short type2; // $v1
			short placement1; // $t5
			short placement2; // $t4
			short source1; // $t2
			short source2; // $t3
	/* end block 1 */
	// End offset: 0x80099748
	// End Line: 345

	/* begin block 2 */
		// Start line: 595
	/* end block 2 */
	// End Line: 596
			UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ PLANPOOL_AreTwoNodesConnected(struct PlanningNode *node1 /*$a3*/, struct PlanningNode *node2 /*$a1*/, struct PlanningNode *planningPool /*$a2*/)
int PLANPOOL_AreTwoNodesConnected(struct PlanningNode *node1, struct PlanningNode *node2, struct PlanningNode *planningPool)
{ // line 350, offset 0x8009975c
	/* begin block 1 */
		// Start line: 351
		// Start offset: 0x8009975C
		// Variables:
			long node2Mask; // $a0
	/* end block 1 */
	// End offset: 0x800997C4
	// End Line: 361

	/* begin block 2 */
		// Start line: 741
	/* end block 2 */
	// End Line: 742
			UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ PLANPOOL_MarkTwoNodesAsConnected(struct PlanningNode *node1 /*$s1*/, struct PlanningNode *node2 /*$a1*/, struct PlanningNode *planningPool /*$a2*/)
void PLANPOOL_MarkTwoNodesAsConnected(struct PlanningNode *node1, struct PlanningNode *node2, struct PlanningNode *planningPool)
{ // line 365, offset 0x800997cc
	/* begin block 1 */
		// Start line: 366
		// Start offset: 0x800997CC
		// Variables:
			int node1Index; // $s2
			int node2Index; // $s0
	/* end block 1 */
	// End offset: 0x80099874
	// End Line: 377

	/* begin block 2 */
		// Start line: 773
	/* end block 2 */
	// End Line: 774
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ PLANPOOL_MarkTwoNodesAsNotConnected(struct PlanningNode *node1 /*$a0*/, struct PlanningNode *node2 /*$a1*/, struct PlanningNode *planningPool /*$a2*/)
void PLANPOOL_MarkTwoNodesAsNotConnected(struct PlanningNode *node1, struct PlanningNode *node2, struct PlanningNode *planningPool)
{ // line 393, offset 0x800998c8
	/* begin block 1 */
		// Start line: 395
		// Start offset: 0x800998C8
	/* end block 1 */
	// End offset: 0x800998C8
	// End Line: 396

	/* begin block 2 */
		// Start line: 856
	/* end block 2 */
	// End Line: 857

	/* begin block 3 */
		// Start line: 857
	/* end block 3 */
	// End Line: 858

	/* begin block 4 */
		// Start line: 858
	/* end block 4 */
	// End Line: 859
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// struct PlanningNode * /*$ra*/ PLANPOOL_GetClosestUnexploredValidNeighbor(struct PlanningNode *startNode /*$s1*/, struct PlanningNode *planningPool /*$s6*/)
struct PlanningNode * PLANPOOL_GetClosestUnexploredValidNeighbor(struct PlanningNode *startNode, struct PlanningNode *planningPool)
{ // line 415, offset 0x80099924
	/* begin block 1 */
		// Start line: 416
		// Start offset: 0x80099924
		// Variables:
			int i; // $s3
			unsigned long connectionStatus; // $s2
			unsigned long dist; // $v1
			unsigned long minDist; // $s5
			struct PlanningNode *returnNode; // $s4
	/* end block 1 */
	// End offset: 0x80099A0C
	// End Line: 444

	/* begin block 2 */
		// Start line: 908
	/* end block 2 */
	// End Line: 909
			UNIMPLEMENTED();
	return null;
}


// autogenerated function stub: 
// void /*$ra*/ PLANPOOL_ChangeNodePosition(_Position *newPos /*$t0*/, struct PlanningNode *nodeToChange /*$a1*/, struct PlanningNode *planningPool /*$a2*/)
void PLANPOOL_ChangeNodePosition(_Position *newPos, struct PlanningNode *nodeToChange, struct PlanningNode *planningPool)
{ // line 451, offset 0x80099a34
	/* begin block 1 */
		// Start line: 452
		// Start offset: 0x80099A34
		// Variables:
			int i; // $a0
			unsigned char nodeToChangeMask; // $v1
	/* end block 1 */
	// End offset: 0x80099AE4
	// End Line: 469

	/* begin block 2 */
		// Start line: 1002
	/* end block 2 */
	// End Line: 1003
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// struct PlanningNode * /*$ra*/ PLANPOOL_AddNodeToPool(_Position *pos /*$t2*/, struct PlanningNode *planningPool /*$t3*/, short nodeType /*$a2*/, short nodeID /*$a3*/, long streamUnitID /*stack 16*/)
struct PlanningNode * PLANPOOL_AddNodeToPool(_Position *pos, struct PlanningNode *planningPool, short nodeType, short nodeID, long streamUnitID)
{ // line 472, offset 0x80099aec
	/* begin block 1 */
		// Start line: 473
		// Start offset: 0x80099AEC
		// Variables:
			struct PlanningNode *nextAvailableNode; // $t0
			int i; // $a1

		/* begin block 1.1 */
			// Start line: 479
			// Start offset: 0x80099B0C
			// Variables:
				short _x1; // $v1
				short _y1; // $a0
				short _z1; // $a1
		/* end block 1.1 */
		// End offset: 0x80099B0C
		// End Line: 479
	/* end block 1 */
	// End offset: 0x80099BD8
	// End Line: 499

	/* begin block 2 */
		// Start line: 1054
	/* end block 2 */
	// End Line: 1055
				UNIMPLEMENTED();
	return null;
}


// autogenerated function stub: 
// void /*$ra*/ PLANPOOL_DeleteNodeFromPool(struct PlanningNode *nodeToDelete /*$a0*/, struct PlanningNode *planningPool /*$a1*/)
void PLANPOOL_DeleteNodeFromPool(struct PlanningNode *nodeToDelete, struct PlanningNode *planningPool)
{ // line 510, offset 0x80099be0
	/* begin block 1 */
		// Start line: 512
		// Start offset: 0x80099BE0
		// Variables:
			int indexOfNodeToDelete; // $t3
			int lastNodeIndex; // $t2
			long oldConnectionMask; // $v1
			long newConnectionMask; // $a3
			int i; // $a2
			struct PlanningNode *lastNode; // $v0
	/* end block 1 */
	// End offset: 0x80099DA4
	// End Line: 556

	/* begin block 2 */
		// Start line: 1146
	/* end block 2 */
	// End Line: 1147

	/* begin block 3 */
		// Start line: 1147
	/* end block 3 */
	// End Line: 1148

	/* begin block 4 */
		// Start line: 1152
	/* end block 4 */
	// End Line: 1153
			UNIMPLEMENTED();
}




