#include "CORE.H"
#include "ANMINTRP.H"


// autogenerated function stub: 
// void /*$ra*/ G2AnimSection_InterpToKeylistAtTime(struct _G2AnimSection_Type *section /*$s1*/, struct _G2AnimKeylist_Type *keylist /*$s7*/, int keylistID /*$fp*/, short targetTime /*stack -48*/, int duration /*stack 16*/)
void G2AnimSection_InterpToKeylistAtTime(struct _G2AnimSection_Type *section, struct _G2AnimKeylist_Type *keylist, int keylistID, short targetTime, int duration)
{ // line 49, offset 0x800920dc
	/* begin block 1 */
		// Start line: 50
		// Start offset: 0x800920DC
		// Variables:
			struct _G2Anim_Type *anim; // $s5
			struct _G2AnimInterpInfo_Type *interpInfo; // $s3
			struct _G2AnimInterpStateBlock_Type *stateBlockList; // $t0
			struct _G2AnimQuatInfo_Type *quatInfo; // $a2
			unsigned long alarmFlags; // $s0
			short elapsedTime; // $s4
			int quatInfoChunkCount; // $a3
			int segCount; // $s2
	/* end block 1 */
	// End offset: 0x80092390
	// End Line: 183

	/* begin block 2 */
		// Start line: 98
	/* end block 2 */
	// End Line: 99

}


// autogenerated function stub: 
// void /*$ra*/ _G2AnimSection_UpdateStoredFrameFromQuat(struct _G2AnimSection_Type *section /*$s7*/)
void _G2AnimSection_UpdateStoredFrameFromQuat(struct _G2AnimSection_Type *section)
{ // line 193, offset 0x800923c0
	/* begin block 1 */
		// Start line: 194
		// Start offset: 0x800923C0
		// Variables:
			struct _G2AnimSegValue_Type *segValue; // $s1
			struct _G2AnimInterpInfo_Type *interpInfo; // $s0
			struct _G2AnimInterpStateBlock_Type *stateBlockList; // $s3
			struct _G2AnimQuatInfo_Type *quatInfo; // $s0
			long alpha; // $s5
			struct _G2Quat_Type newQuat; // stack offset -48
			int quatInfoChunkCount; // $s4
			int segCount; // $s6

		/* begin block 1.1 */
			// Start line: 223
			// Start offset: 0x8009244C
			// Variables:
				struct _G2Quat_Type *source; // $fp
				struct _G2Quat_Type *dest; // $s1

			/* begin block 1.1.1 */
				// Start line: 223
				// Start offset: 0x8009244C
				// Variables:
					unsigned long zw; // $v1
					unsigned long xy; // $v0
			/* end block 1.1.1 */
			// End offset: 0x8009244C
			// End Line: 223
		/* end block 1.1 */
		// End offset: 0x8009244C
		// End Line: 223

		/* begin block 1.2 */
			// Start line: 223
			// Start offset: 0x8009244C
			// Variables:
				//struct _G2SVector3_Type *dest; // $a0
				//struct _G2SVector3_Type *base; // $v0
				//struct _G2SVector3_Type *offset; // $v1
				//long alpha; // $s5
		/* end block 1.2 */
		// End offset: 0x8009244C
		// End Line: 223

		/* begin block 1.3 */
			// Start line: 223
			// Start offset: 0x8009244C
			// Variables:
				//struct _G2SVector3_Type *dest; // $a0
				//struct _G2SVector3_Type *base; // $v0
				//struct _G2SVector3_Type *offset; // $v1
				//long alpha; // $s5
		/* end block 1.3 */
		// End offset: 0x8009244C
		// End Line: 223
	/* end block 1 */
	// End offset: 0x8009256C
	// End Line: 252

	/* begin block 2 */
		// Start line: 434
	/* end block 2 */
	// End Line: 435

}


// autogenerated function stub: 
// void /*$ra*/ _G2AnimSection_InterpStateToQuat(struct _G2AnimSection_Type *section /*$a0*/)
void _G2AnimSection_InterpStateToQuat(struct _G2AnimSection_Type *section)
{ // line 258, offset 0x800925b0
	/* begin block 1 */
		// Start line: 259
		// Start offset: 0x800925B0
		// Variables:
			struct _G2AnimInterpInfo_Type *interpInfo; // $s0
			struct _G2AnimInterpStateBlock_Type *stateBlockList; // $s3
			struct _G2AnimQuatInfo_Type *quatInfo; // $s0
			long alpha; // $s1
			struct _G2Quat_Type newQuat; // stack offset -40
			int quatInfoChunkCount; // $s2
			int segCount; // $s4

		/* begin block 1.1 */
			// Start line: 288
			// Start offset: 0x80092610
			// Variables:
				struct _G2Quat_Type *source; // $s5
				struct _G2Quat_Type *dest; // $s0

			/* begin block 1.1.1 */
				// Start line: 288
				// Start offset: 0x80092610
				// Variables:
					unsigned long zw; // $v1
					unsigned long xy; // $v0
			/* end block 1.1.1 */
			// End offset: 0x80092610
			// End Line: 288
		/* end block 1.1 */
		// End offset: 0x80092610
		// End Line: 288

		/* begin block 1.2 */
			// Start line: 288
			// Start offset: 0x80092610
			// Variables:
				//struct _G2SVector3_Type *dest; // $v1
				//struct _G2SVector3_Type *offset; // $v0
				//long alpha; // $s1
		/* end block 1.2 */
		// End offset: 0x80092610
		// End Line: 288

		/* begin block 1.3 */
			// Start line: 288
			// Start offset: 0x80092610
			// Variables:
				//struct _G2SVector3_Type *dest; // $v1
				//struct _G2SVector3_Type *offset; // $v0
				//long alpha; // $s1
		/* end block 1.3 */
		// End offset: 0x80092610
		// End Line: 288
	/* end block 1 */
	// End offset: 0x8009271C
	// End Line: 313

	/* begin block 2 */
		// Start line: 582
	/* end block 2 */
	// End Line: 583

}


// autogenerated function stub: 
// void /*$ra*/ _G2AnimSection_SegValueToQuat(struct _G2AnimSection_Type *section /*$a0*/, int zeroOne /*$s6*/)
void _G2AnimSection_SegValueToQuat(struct _G2AnimSection_Type *section, int zeroOne)
{ // line 318, offset 0x80092740
	/* begin block 1 */
		// Start line: 319
		// Start offset: 0x80092740
		// Variables:
			struct _G2AnimSegValue_Type *segValue; // $s2
			struct _G2AnimInterpInfo_Type *interpInfo; // $v0
			struct _G2AnimInterpStateBlock_Type *stateBlockList; // $s4
			struct _G2AnimQuatInfo_Type *quatInfo; // $s0
			struct _G2EulerAngles_Type preQuat; // stack offset -40
			int quatInfoChunkCount; // $s3
			int segCount; // $s5
	/* end block 1 */
	// End offset: 0x800928A4
	// End Line: 384

	/* begin block 2 */
		// Start line: 716
	/* end block 2 */
	// End Line: 717

}


// autogenerated function stub: 
// struct _G2AnimInterpStateBlock_Type * /*$ra*/ _G2Anim_AllocateInterpStateBlockList(struct _G2AnimSection_Type *section /*$v0*/)
struct _G2AnimInterpStateBlock_Type * _G2Anim_AllocateInterpStateBlockList(struct _G2AnimSection_Type *section)
{ // line 388, offset 0x800928cc
	/* begin block 1 */
		// Start line: 389
		// Start offset: 0x800928CC
		// Variables:
			struct _G2AnimInterpInfo_Type *interpInfo; // $s2
			struct _G2AnimInterpStateBlock_Type *newBlock; // $s1
			int segCount; // $s0
	/* end block 1 */
	// End offset: 0x8009294C
	// End Line: 425

	/* begin block 2 */
		// Start line: 891
	/* end block 2 */
	// End Line: 892

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ _G2Anim_FreeInterpStateBlockList(struct _G2AnimInterpStateBlock_Type *block /*$a1*/)
void _G2Anim_FreeInterpStateBlockList(struct _G2AnimInterpStateBlock_Type *block)
{ // line 429, offset 0x80092964
	/* begin block 1 */
		// Start line: 430
		// Start offset: 0x80092964
		// Variables:
			struct _G2AnimInterpStateBlock_Type *nextBlock; // $s0
	/* end block 1 */
	// End offset: 0x80092994
	// End Line: 441

	/* begin block 2 */
		// Start line: 985
	/* end block 2 */
	// End Line: 986

}




