#include "CORE.H"
#include "HEALTH.H"
#include "GAMELOOP.H"
#include "RAZLIB.H"

void InitHealthSystem()
{
	Raziel.DamageFrequency = 0;
	Raziel.HealthScale = 1;
	Raziel.HealthBalls = 0;
	Raziel.GlyphManaBalls = 0;

	if (gameTrackerX.gameData.asmData.MorphType == 0)
	{
		Raziel.CurrentPlane = 2;
		Raziel.HitPoints = 100000;
		
		razMaterialShift();
	}
	else
	{
		Raziel.CurrentPlane = 1;
		Raziel.HitPoints = GetMaxHealth();
		
		razSpectralShift();
	}

	if (razInBaseArea("under", sizeof("under")-1))
	{
		Raziel.HitPoints = 100;
	}
	else
	{
		razSetPlayerEventHistory(0x1000);
	}
}


// autogenerated function stub: 
// void /*$ra*/ GainHealth(int data /*$a0*/)
void GainHealth(int data)
{ // line 32, offset 0x800a4668
	/* begin block 1 */
		// Start line: 71
	/* end block 1 */
	// End Line: 72

}


// autogenerated function stub: 
// void /*$ra*/ LoseHealth(int amount /*$a0*/)
void LoseHealth(int amount)
{ // line 47, offset 0x800a46f4
	/* begin block 1 */
		// Start line: 101
	/* end block 1 */
	// End Line: 102

}


// autogenerated function stub: 
// void /*$ra*/ DrainHealth(int amount /*$a0*/)
void DrainHealth(int amount)
{ // line 72, offset 0x800a47f0
	/* begin block 1 */
		// Start line: 153
	/* end block 1 */
	// End Line: 154

}


// autogenerated function stub: 
// void /*$ra*/ BumpUpHealth()
void BumpUpHealth()
{ // line 97, offset 0x800a490c
	/* begin block 1 */
		// Start line: 206
	/* end block 1 */
	// End Line: 207

	/* begin block 2 */
		// Start line: 215
	/* end block 2 */
	// End Line: 216

}


// autogenerated function stub: 
// int /*$ra*/ GetMaxHealth()
int GetMaxHealth()
{ // line 115, offset 0x800a4950
	/* begin block 1 */
		// Start line: 251
	/* end block 1 */
	// End Line: 252

	/* begin block 2 */
		// Start line: 252
	/* end block 2 */
	// End Line: 253

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ ProcessHealth(struct _Instance *instance /*$s0*/)
void ProcessHealth(struct _Instance *instance)
{ // line 132, offset 0x800a49a0
	/* begin block 1 */
		// Start line: 133
		// Start offset: 0x800A49A0

		/* begin block 1.1 */
			// Start line: 228
			// Start offset: 0x800A4BC8
		/* end block 1.1 */
		// End offset: 0x800A4C5C
		// End Line: 241
	/* end block 1 */
	// End offset: 0x800A4E3C
	// End Line: 289

	/* begin block 2 */
		// Start line: 264
	/* end block 2 */
	// End Line: 265

	/* begin block 3 */
		// Start line: 319
	/* end block 3 */
	// End Line: 320

}


// autogenerated function stub: 
// int /*$ra*/ HealthCheckForLowHealth()
int HealthCheckForLowHealth()
{ // line 292, offset 0x800a4e4c
	/* begin block 1 */
		// Start line: 649
	/* end block 1 */
	// End Line: 650

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ DrainMana(int amount /*$a0*/)
void DrainMana(int amount)
{ // line 314, offset 0x800a4eb8
	/* begin block 1 */
		// Start line: 693
	/* end block 1 */
	// End Line: 694

	/* begin block 2 */
		// Start line: 694
	/* end block 2 */
	// End Line: 695

}


// autogenerated function stub: 
// void /*$ra*/ SetMana(int amount /*$a0*/)
void SetMana(int amount)
{ // line 324, offset 0x800a4efc
	/* begin block 1 */
		// Start line: 713
	/* end block 1 */
	// End Line: 714

	/* begin block 2 */
		// Start line: 714
	/* end block 2 */
	// End Line: 715

}


// autogenerated function stub: 
// void /*$ra*/ HealthInstantDeath(struct _Instance *instance /*$a0*/)
void HealthInstantDeath(struct _Instance *instance)
{ // line 333, offset 0x800a4f24
	/* begin block 1 */
		// Start line: 731
	/* end block 1 */
	// End Line: 732

}


// autogenerated function stub: 
// void /*$ra*/ RAZIEL_DebugHealthSetScale(long healthScale /*$a0*/)
void RAZIEL_DebugHealthSetScale(long healthScale)
{ // line 352, offset 0x800a4fa4
	/* begin block 1 */
		// Start line: 773
	/* end block 1 */
	// End Line: 774

	/* begin block 2 */
		// Start line: 778
	/* end block 2 */
	// End Line: 779

}


// autogenerated function stub: 
// void /*$ra*/ RAZIEL_DebugManaSetMax(long manaScale /*$a0*/)
void RAZIEL_DebugManaSetMax(long manaScale)
{ // line 363, offset 0x800a4ffc
	/* begin block 1 */
		// Start line: 800
	/* end block 1 */
	// End Line: 801

	/* begin block 2 */
		// Start line: 802
	/* end block 2 */
	// End Line: 803

}


// autogenerated function stub: 
// void /*$ra*/ RAZIEL_DebugHealthFillUp()
void RAZIEL_DebugHealthFillUp()
{ // line 375, offset 0x800a5024
	/* begin block 1 */
		// Start line: 824
	/* end block 1 */
	// End Line: 825

	/* begin block 2 */
		// Start line: 825
	/* end block 2 */
	// End Line: 826

}


// autogenerated function stub: 
// void /*$ra*/ RAZIEL_DebugManaFillUp()
void RAZIEL_DebugManaFillUp()
{ // line 387, offset 0x800a5084
	/* begin block 1 */
		// Start line: 848
	/* end block 1 */
	// End Line: 849

}


// autogenerated function stub: 
// void /*$ra*/ razPlayUnderworldSounds(struct _Instance *instance /*$s3*/)
void razPlayUnderworldSounds(struct _Instance *instance)
{ // line 395, offset 0x800a50a4
	/* begin block 1 */
		// Start line: 864
	/* end block 1 */
	// End Line: 865

}




