#include "Game/CORE.H"
#include "PUPPET.H"


// autogenerated function stub: 
// void /*$ra*/ StateHandlerPuppetShow(struct __CharacterState *In /*$s2*/, int CurrentSection /*$s1*/, int Data /*$s4*/)
void StateHandlerPuppetShow(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 8, offset 0x8009a984
	/* begin block 1 */
		// Start line: 9
		// Start offset: 0x8009A984
		// Variables:
			struct __Event *Ptr; // $s0

		/* begin block 1.1 */
			// Start line: 38
			// Start offset: 0x8009AB48
			// Variables:
				struct evActionPlayHostAnimationData *data; // $v0
		/* end block 1.1 */
		// End offset: 0x8009AB48
		// End Line: 40

		/* begin block 1.2 */
			// Start line: 53
			// Start offset: 0x8009ABB8
			// Variables:
				//struct evAnimationInstanceSwitchData *data; // $v1
		/* end block 1.2 */
		// End offset: 0x8009ABB8
		// End Line: 55

		/* begin block 1.3 */
			// Start line: 67
			// Start offset: 0x8009AC34
			// Variables:
				//struct evPositionData *data; // $v0
		/* end block 1.3 */
		// End offset: 0x8009AC34
		// End Line: 67

		/* begin block 1.4 */
			// Start line: 78
			// Start offset: 0x8009AC78
			// Variables:
				//struct evPositionData *data; // $v0

			/* begin block 1.4.1 */
				// Start line: 78
				// Start offset: 0x8009AC78
				// Variables:
					short _x1; // $v1
					short _y1; // $a0
					short _z1; // $a1
					_Position *_v0; // $v0
			/* end block 1.4.1 */
			// End offset: 0x8009AC78
			// End Line: 78
		/* end block 1.4 */
		// End offset: 0x8009AC78
		// End Line: 78
	/* end block 1 */
	// End offset: 0x8009ACF4
	// End Line: 98

	/* begin block 2 */
		// Start line: 16
	/* end block 2 */
	// End Line: 17
					UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerMoveToPosition(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s6*/)
void StateHandlerMoveToPosition(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 102, offset 0x8009ad20
	/* begin block 1 */
		// Start line: 103
		// Start offset: 0x8009AD20
		// Variables:
			struct __Event *Ptr; // $s0
			long distance; // $s0
			int motion; // $v0
			int applyMotion; // $s5

		/* begin block 1.1 */
			// Start line: 113
			// Start offset: 0x8009AE2C
			// Variables:
				struct evPositionData *moveToPoint; // $v0

			/* begin block 1.1.1 */
				// Start line: 115
				// Start offset: 0x8009AE2C
				// Variables:
					short _x1; // $v1
					short _y1; // $a0
					short _z1; // $v0
					_Position *_v0; // $s3
			/* end block 1.1.1 */
			// End offset: 0x8009AE2C
			// End Line: 115
		/* end block 1.1 */
		// End offset: 0x8009AE2C
		// End Line: 115

		/* begin block 1.2 */
			// Start line: 134
			// Start offset: 0x8009AEC8
			// Variables:
				//struct evPositionData *moveToPoint; // $v0

			/* begin block 1.2.1 */
				// Start line: 136
				// Start offset: 0x8009AEC8
				// Variables:
					//short _x1; // $v1
					//short _y1; // $a0
					//short _z1; // $v0
			/* end block 1.2.1 */
			// End offset: 0x8009AEC8
			// End Line: 136
		/* end block 1.2 */
		// End offset: 0x8009AEEC
		// End Line: 140
	/* end block 1 */
	// End offset: 0x8009AFA0
	// End Line: 174

	/* begin block 2 */
		// Start line: 217
	/* end block 2 */
	// End Line: 218
					UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ DefaultPuppetStateHandler(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s0*/, int Data /*$s2*/)
void DefaultPuppetStateHandler(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 174, offset 0x8009afc8
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x8009AFC8
		// Variables:
			struct __Event *Ptr; // $a1

		/* begin block 1.1 */
			// Start line: 194
			// Start offset: 0x8009B190
			// Variables:
				struct evPositionData *data; // $v0
		/* end block 1.1 */
		// End offset: 0x8009B190
		// End Line: 194

		/* begin block 1.2 */
			// Start line: 201
			// Start offset: 0x8009B1A4
			// Variables:
				//struct evPositionData *data; // $v1

			/* begin block 1.2.1 */
				// Start line: 203
				// Start offset: 0x8009B1A4
				// Variables:
					long _x1; // $a0
					long _y1; // $a2
					long _z1; // $a1
					struct _Vector *_v0; // $v0
			/* end block 1.2.1 */
			// End offset: 0x8009B1A4
			// End Line: 203
		/* end block 1.2 */
		// End offset: 0x8009B1E4
		// End Line: 208
	/* end block 1 */
	// End offset: 0x8009B264
	// End Line: 240

	/* begin block 2 */
		// Start line: 383
	/* end block 2 */
	// End Line: 384
					UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerWarpGate(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s1*/, int Data /*$s4*/)
void StateHandlerWarpGate(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 243, offset 0x8009b27c
	/* begin block 1 */
		// Start line: 244
		// Start offset: 0x8009B27C
		// Variables:
			struct __Event *Ptr; // $v0
			int anim; // $s3

		/* begin block 1.1 */
			// Start line: 289
			// Start offset: 0x8009B58C
			// Variables:
				struct _Instance *heldInst; // $v0
		/* end block 1.1 */
		// End offset: 0x8009B5E0
		// End Line: 296

		/* begin block 1.2 */
			// Start line: 302
			// Start offset: 0x8009B614
		/* end block 1.2 */
		// End offset: 0x8009B614
		// End Line: 302
	/* end block 1 */
	// End offset: 0x8009B6F0
	// End Line: 344

	/* begin block 2 */
		// Start line: 527
	/* end block 2 */
	// End Line: 528
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerForcedGlide(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s7*/)
void StateHandlerForcedGlide(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 348, offset 0x8009b710
	/* begin block 1 */
		// Start line: 349
		// Start offset: 0x8009B710
		// Variables:
			struct __Event *Ptr; // $s0
			int Anim; // $s6
			int extraProcess; // $s4

		/* begin block 1.1 */
			// Start line: 425
			// Start offset: 0x8009BAA0
		/* end block 1.1 */
		// End offset: 0x8009BAD4
		// End Line: 431
	/* end block 1 */
	// End offset: 0x8009BAD4
	// End Line: 435

	/* begin block 2 */
		// Start line: 741
	/* end block 2 */
	// End Line: 742
			UNIMPLEMENTED();
}




