#include "Game/CORE.H"
#include "Game/PLAYER.H"
#include "RAZIEL.H"
#include "Game/GAMELOOP.H"
#include "Game/OBTABLE.H"
#include "Game/COLLIDE.H"
#include "Game/STATE.H"
#include "Game/G2/ANMG2ILF.H"
#include "RAZLIB.H"
#include "HEALTH.H"
#include "Game/DEBUG.H"
#include "CONTROL.H"
#include "Game/CAMERA.H"
#include "Game/STREAM.H"
#include "Game/SAVEINFO.H"
#include "Game/EVENT.H"
#include "RAZDBUG.H"
#include "Game/RAZCNTRL.H"
#include "Game/GLYPH.H"
#include "Game/SOUND.H"
#include "Game/PHYSICS.H"
#include "Game/FX.H"
#include "Game/G2/ANMCTRLR.H"
#include "Game/GAMEPAD.H"
#include "Game/TIMER.H"
#include "Game/RAZIEL/STEERING.H"

struct RazielData* PlayerData;
struct _G2AnimInterpInfo_Type razInterpInfo[3];
struct __EngagedInstance EngagedList[15];
struct __FitPoint constrictData[32];
int ControlFlag;
struct _G2SVector3_Type* ExtraRot;
int WaterStatus;
_Normal Norm;
struct __Force ExternalForces[4];
int LoopCounter;

void InitStates(struct _Instance* PlayerInstance)
{
	unsigned char i;
	struct _G2AnimSection_Type* animSection;

	if (Raziel.footPrint == 0)
	{
		Raziel.footPrint = (int)PlayerInstance->object;
	}

	PlayerInstance->InstanceState = &Raziel.State.CharacterInstance;
	Raziel.State.CharacterInstance = PlayerInstance;
	PlayerData = (struct RazielData*)PlayerInstance->data;

	G2EmulationSetTotalSections(&Raziel.State, 3);
	G2EmulationSetStartAndEndSegment(&Raziel.State, 0, 0, 13);
	G2EmulationSetStartAndEndSegment(&Raziel.State, 1, 14, 49);
	G2EmulationSetStartAndEndSegment(&Raziel.State, 2, 50, 65);
	
	for (i = 0; i < 3; i++)
	{
		animSection = &PlayerInstance->anim.section[0];
		animSection->callback = (unsigned long (*)(struct _G2Anim_Type*, int, enum _G2AnimCallbackMsg_Enum, long, long, struct _Instance*)) & RazielAnimCallback;
		animSection->callbackData = NULL;
	
		Raziel.State.SectionList[i].Process = &StateHandlerIdle;

		InitMessageQueue(&Raziel.State.SectionList[i].Event);
		InitMessageQueue(&Raziel.State.SectionList[i].Defer);
	}

	G2AnimSection_SetInterpInfo(&PlayerInstance->anim.section[0], &razInterpInfo[0]);
	G2AnimSection_SetInterpInfo(&PlayerInstance->anim.section[1], &razInterpInfo[1]);
	G2AnimSection_SetInterpInfo(&PlayerInstance->anim.section[2], &razInterpInfo[2]);

	Raziel.Mode = 1;

	gameTrackerX.debugFlags2 |= 0x800;

	InitHealthSystem();

	Raziel.Abilities = 0x1000000;

	debugRazielFlags1 = 0x1000000;

	Raziel.GlyphManaBalls = 0;
	Raziel.GlyphManaMax = 0;
	Raziel.Abilities = 0;
	Raziel.RotationSegment = 0;
	Raziel.extraRot.x = 0;
	Raziel.extraRot.y = 0;
	Raziel.extraRot.z = 0;

	PlayerInstance->rotation.x = 0;
	PlayerInstance->rotation.y = 0;
	PlayerInstance->rotation.z = 0;

	Raziel.Senses.EngagedList = &EngagedList[0];
	Raziel.constrictData = &constrictData[0];
	Raziel.dropOffHeight = 256;
	Raziel.Senses.EngagedMask = 0;
	Raziel.idleInstance = NULL;
	Raziel.soulReaver = NULL;
	Raziel.fallZVelocity = -32;

	G2EmulationSetAnimation(&Raziel.State, 0, 0, 0, 0);
	G2EmulationSetMode(&Raziel.State, 0, 2);

	G2EmulationSetAnimation(&Raziel.State, 1, 0, 0, 0);
	G2EmulationSetMode(&Raziel.State, 1, 2);

	G2EmulationSetAnimation(&Raziel.State, 2, 0, 0, 0);
	G2EmulationSetMode(&Raziel.State, 2, 2);

	ControlFlag = 0x519;

	PlayerInstance->maxXVel = 256;
	PlayerInstance->maxYVel = 256;
	PlayerInstance->maxZVel = 256;

	razSetCowlNoDraw(1);

	InitExternalForces(&ExternalForces[0], 4);

	ResetPhysics(PlayerInstance, -16);

	ExtraRot = NULL;

	CAMERA_ChangeToOutOfWater(&theCamera, PlayerInstance);

	razAttachControllers();

	INSTANCE_Post(PlayerInstance, 0x100006, 0);

	PlayerInstance->checkMask = 0x803E002E;
	PlayerInstance->flags2 |= 0x400;

	G2EmulationInit();

	InitGlyphSystem(PlayerInstance);

	Raziel.slipSlope = 0xB50;
	Raziel.terminator = -1;

	gameTrackerX.raziel_collide_override = 0;
}


// autogenerated function stub: 
// void /*$ra*/ StateInitIdle(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Ptr /*$a2*/)
void StateInitIdle(struct __CharacterState *In, int CurrentSection, int Ptr)
{ // line 459, offset 0x800a83b0
	/* begin block 1 */
		// Start line: 460
		// Start offset: 0x800A83B0
		// Variables:
			struct evControlInitIdleData *data; // $s0
			struct _Instance *linkWeapon; // $a0
	/* end block 1 */
	// End offset: 0x800A8650
	// End Line: 575

	/* begin block 2 */
		// Start line: 918
	/* end block 2 */
	// End Line: 919
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerIdle(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$fp*/)
void StateHandlerIdle(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 624, offset 0x800a8668
	/* begin block 1 */
		// Start line: 625
		// Start offset: 0x800A8668
		// Variables:
			struct __Event *Ptr; // $s0
			int Anim; // $s5
			int blockForwardMotion; // $s7

		/* begin block 1.1 */
			// Start line: 777
			// Start offset: 0x800A8C7C
			// Variables:
				struct _Instance *heldInst; // $v0
		/* end block 1.1 */
		// End offset: 0x800A8CA4
		// End Line: 783

		/* begin block 1.2 */
			// Start line: 821
			// Start offset: 0x800A8D40
			// Variables:
				struct evPhysicsEdgeData *EdgeData; // $v0
		/* end block 1.2 */
		// End offset: 0x800A8D98
		// End Line: 828
	/* end block 1 */
	// End offset: 0x800A8EF8
	// End Line: 898

	/* begin block 2 */
		// Start line: 1248
	/* end block 2 */
	// End Line: 1249
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerLookAround(struct __CharacterState *In /*$s2*/, int CurrentSection /*$s1*/, int Data /*$a2*/)
void StateHandlerLookAround(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 902, offset 0x800a8f28
	/* begin block 1 */
		// Start line: 903
		// Start offset: 0x800A8F28
		// Variables:
			struct __Event *Ptr; // $s0

		/* begin block 1.1 */
			// Start line: 910
			// Start offset: 0x800A9018
			// Variables:
				struct _Instance *instance; // $s0
		/* end block 1.1 */
		// End offset: 0x800A905C
		// End Line: 918

		/* begin block 1.2 */
			// Start line: 925
			// Start offset: 0x800A9094
			// Variables:
				//struct _Instance *instance; // $s0
		/* end block 1.2 */
		// End offset: 0x800A9094
		// End Line: 926

		/* begin block 1.3 */
			// Start line: 938
			// Start offset: 0x800A90DC
			// Variables:
				int message; // stack offset -32
				int messageData; // stack offset -28
		/* end block 1.3 */
		// End offset: 0x800A9190
		// End Line: 956
	/* end block 1 */
	// End offset: 0x800A9254
	// End Line: 979

	/* begin block 2 */
		// Start line: 1925
	/* end block 2 */
	// End Line: 1926
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerCrouch(struct __CharacterState *In /*$s3*/, int CurrentSection /*$s4*/, int Data /*stack 8*/)
void StateHandlerCrouch(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 982, offset 0x800a9270
	/* begin block 1 */
		// Start line: 983
		// Start offset: 0x800A9270
		// Variables:
			struct __Event *Ptr; // $s1
			int Anim; // $s0
			struct _Instance *heldInst; // $s5
			int DropThisFrame; // stack offset -48

		/* begin block 1.1 */
			// Start line: 1097
			// Start offset: 0x800A96A0
			// Variables:
				struct evObjectData *data; // $s0
				int i; // $s2
		/* end block 1.1 */
		// End offset: 0x800A9788
		// End Line: 1124
	/* end block 1 */
	// End offset: 0x800A99B8
	// End Line: 1186

	/* begin block 2 */
		// Start line: 2095
	/* end block 2 */
	// End Line: 2096
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerDropAction(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s0*/, int Data /*$s4*/)
void StateHandlerDropAction(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 1189, offset 0x800a99e8
	/* begin block 1 */
		// Start line: 1190
		// Start offset: 0x800A99E8
		// Variables:
			struct __Event *Ptr; // $v0
	/* end block 1 */
	// End offset: 0x800A9C48
	// End Line: 1260

	/* begin block 2 */
		// Start line: 2528
	/* end block 2 */
	// End Line: 2529
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerSoulSuck(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s0*/, int Data /*$s5*/)
void StateHandlerSoulSuck(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 1267, offset 0x800a9c68
	/* begin block 1 */
		// Start line: 1268
		// Start offset: 0x800A9C68
		// Variables:
			struct __Event *Ptr; // $a0
			int Anim; // $s3

		/* begin block 1.1 */
			// Start line: 1375
			// Start offset: 0x800AA130
			// Variables:
				struct evPhysicsSwimData *SwimData; // $v0
		/* end block 1.1 */
		// End offset: 0x800AA160
		// End Line: 1382
	/* end block 1 */
	// End offset: 0x800AA17C
	// End Line: 1390

	/* begin block 2 */
		// Start line: 2693
	/* end block 2 */
	// End Line: 2694

	/* begin block 3 */
		// Start line: 2698
	/* end block 3 */
	// End Line: 2699
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerStartTurn(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s1*/, int Data /*$s3*/)
void StateHandlerStartTurn(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 1396, offset 0x800aa1a0
	/* begin block 1 */
		// Start line: 1397
		// Start offset: 0x800AA1A0
		// Variables:
			struct __Event *Ptr; // $v0
	/* end block 1 */
	// End offset: 0x800AA384
	// End Line: 1457

	/* begin block 2 */
		// Start line: 2961
	/* end block 2 */
	// End Line: 2962
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateInitStartMove(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s0*/, int Frame /*$s3*/)
void StateInitStartMove(struct __CharacterState *In, int CurrentSection, int Frame)
{ // line 1461, offset 0x800aa3a0
	/* begin block 1 */
		// Start line: 3096
	/* end block 1 */
	// End Line: 3097

	/* begin block 2 */
		// Start line: 3099
	/* end block 2 */
	// End Line: 3100
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerStartMove(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s4*/)
void StateHandlerStartMove(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 1550, offset 0x800aa44c
	/* begin block 1 */
		// Start line: 1551
		// Start offset: 0x800AA44C
		// Variables:
			struct __Event *Ptr; // $a1

		/* begin block 1.1 */
			// Start line: 1613
			// Start offset: 0x800AA728
			// Variables:
				int mode; // $a0
		/* end block 1.1 */
		// End offset: 0x800AA780
		// End Line: 1631
	/* end block 1 */
	// End offset: 0x800AAACC
	// End Line: 1722

	/* begin block 2 */
		// Start line: 3277
	/* end block 2 */
	// End Line: 3278
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateInitMove(struct __CharacterState *In /*$s2*/, int CurrentSection /*$s0*/, int Frames /*$a2*/)
void StateInitMove(struct __CharacterState *In, int CurrentSection, int Frames)
{ // line 1725, offset 0x800aaaec
	/* begin block 1 */
		// Start line: 3642
	/* end block 1 */
	// End Line: 3643

	/* begin block 2 */
		// Start line: 3647
	/* end block 2 */
	// End Line: 3648
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerMove(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s7*/)
void StateHandlerMove(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 1931, offset 0x800aad30
	/* begin block 1 */
		// Start line: 1932
		// Start offset: 0x800AAD30
		// Variables:
			struct __Event *Ptr; // $s0
			int Anim; // $s6

		/* begin block 1.1 */
			// Start line: 1997
			// Start offset: 0x800AB0E8
			// Variables:
				int data; // $a2
		/* end block 1.1 */
		// End offset: 0x800AB144
		// End Line: 2011
	/* end block 1 */
	// End offset: 0x800AB404
	// End Line: 2102

	/* begin block 2 */
		// Start line: 4090
	/* end block 2 */
	// End Line: 4091
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerStopMove(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s1*/, int Data /*$s4*/)
void StateHandlerStopMove(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2105, offset 0x800ab430
	/* begin block 1 */
		// Start line: 2106
		// Start offset: 0x800AB430
		// Variables:
			struct __Event *Ptr; // $a1
	/* end block 1 */
	// End offset: 0x800AB768
	// End Line: 2202

	/* begin block 2 */
		// Start line: 4448
	/* end block 2 */
	// End Line: 4449
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerCompression(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s1*/, int Data /*$s4*/)
void StateHandlerCompression(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2209, offset 0x800ab788
	/* begin block 1 */
		// Start line: 2210
		// Start offset: 0x800AB788
		// Variables:
			struct __Event *Ptr; // $v0
	/* end block 1 */
	// End offset: 0x800ABB2C
	// End Line: 2305

	/* begin block 2 */
		// Start line: 4667
	/* end block 2 */
	// End Line: 4668
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerJump(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s2*/, int Data /*$s6*/)
void StateHandlerJump(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2308, offset 0x800abb4c
	/* begin block 1 */
		// Start line: 2309
		// Start offset: 0x800ABB4C
		// Variables:
			struct __Event *Ptr; // $v0
	/* end block 1 */
	// End offset: 0x800ABF5C
	// End Line: 2408

	/* begin block 2 */
		// Start line: 4888
	/* end block 2 */
	// End Line: 4889
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerFall(struct __CharacterState *In /*$s2*/, int CurrentSection /*$s3*/, int Data /*stack 8*/)
void StateHandlerFall(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2411, offset 0x800abf84
	/* begin block 1 */
		// Start line: 2412
		// Start offset: 0x800ABF84
		// Variables:
			struct __Event *Ptr; // $s0
			int Moving; // $s7
			int DeferFlag; // $s6
			struct evPhysicsSwimData *SwimData; // $s1

		/* begin block 1.1 */
			// Start line: 2430
			// Start offset: 0x800ABFC8
		/* end block 1.1 */
		// End offset: 0x800ABFFC
		// End Line: 2436
	/* end block 1 */
	// End offset: 0x800AC3C8
	// End Line: 2617

	/* begin block 2 */
		// Start line: 5132
	/* end block 2 */
	// End Line: 5133
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerSlide(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s1*/, int Data /*$s3*/)
void StateHandlerSlide(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2621, offset 0x800ac3f8
	/* begin block 1 */
		// Start line: 2622
		// Start offset: 0x800AC3F8
		// Variables:
			struct __Event *Ptr; // $v0
	/* end block 1 */
	// End offset: 0x800AC5BC
	// End Line: 2678

	/* begin block 2 */
		// Start line: 5560
	/* end block 2 */
	// End Line: 5561
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerBlock(struct __CharacterState *In /*$s2*/, int CurrentSection /*$s4*/, int Data /*$s7*/)
void StateHandlerBlock(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2688, offset 0x800ac5d8
	/* begin block 1 */
		// Start line: 2689
		// Start offset: 0x800AC5D8
		// Variables:
			struct __Event *Ptr; // $a0
			int Anim; // $s3

		/* begin block 1.1 */
			// Start line: 2727
			// Start offset: 0x800AC7E0
			// Variables:
				struct _Rotation rot; // stack offset -56
		/* end block 1.1 */
		// End offset: 0x800AC7E0
		// End Line: 2728

		/* begin block 1.2 */
			// Start line: 2743
			// Start offset: 0x800AC868
		/* end block 1.2 */
		// End offset: 0x800AC868
		// End Line: 2744

		/* begin block 1.3 */
			// Start line: 2757
			// Start offset: 0x800AC90C
			// Variables:
				struct evPhysicsEdgeData *EdgeData; // $s1

			/* begin block 1.3.1 */
				// Start line: 2762
				// Start offset: 0x800AC94C
				// Variables:
					//SVECTOR startVec; // stack offset -56
					///SVECTOR endVec; // stack offset -48
			/* end block 1.3.1 */
			// End offset: 0x800AC9A4
			// End Line: 2770
		/* end block 1.3 */
		// End offset: 0x800AC9F8
		// End Line: 2779
	/* end block 1 */
	// End offset: 0x800ACA18
	// End Line: 2792

	/* begin block 2 */
		// Start line: 5703
	/* end block 2 */
	// End Line: 5704
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerDeCompression(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s2*/, int Data /*$s5*/)
void StateHandlerDeCompression(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2795, offset 0x800aca44
	/* begin block 1 */
		// Start line: 2796
		// Start offset: 0x800ACA44
		// Variables:
			struct __Event *Ptr; // $s1

		/* begin block 1.1 */
			// Start line: 2805
			// Start offset: 0x800ACB1C
		/* end block 1.1 */
		// End offset: 0x800ACC94
		// End Line: 2844
	/* end block 1 */
	// End offset: 0x800ACD90
	// End Line: 2884

	/* begin block 2 */
		// Start line: 5926
	/* end block 2 */
	// End Line: 5927
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerGlide(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s3*/, int Data /*$fp*/)
void StateHandlerGlide(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 2889, offset 0x800acdb4
	/* begin block 1 */
		// Start line: 2890
		// Start offset: 0x800ACDB4
		// Variables:
			struct __Event *Ptr; // $s0
			int Frame; // $s7
			int Anim; // $s5
			int moving; // $s6

		/* begin block 1.1 */
			// Start line: 3009
			// Start offset: 0x800AD32C
			// Variables:
				struct evObjectDraftData *draft; // $a2
		/* end block 1.1 */
		// End offset: 0x800AD384
		// End Line: 3016

		/* begin block 1.2 */
			// Start line: 3021
			// Start offset: 0x800AD3AC
			// Variables:
				struct evPhysicsSwimData *SwimData; // $v0
		/* end block 1.2 */
		// End offset: 0x800AD43C
		// End Line: 3034
	/* end block 1 */
	// End offset: 0x800AD4F0
	// End Line: 3087

	/* begin block 2 */
		// Start line: 6140
	/* end block 2 */
	// End Line: 6141
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerHang(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$fp*/)
void StateHandlerHang(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 3090, offset 0x800ad520
	/* begin block 1 */
		// Start line: 3091
		// Start offset: 0x800AD520
		// Variables:
			struct __Event *Ptr; // $a0
			int Anim; // $s7

		/* begin block 1.1 */
			// Start line: 3103
			// Start offset: 0x800AD6E0
			// Variables:
				struct evControlInitHangData *data; // $s0
		/* end block 1.1 */
		// End offset: 0x800AD7F4
		// End Line: 3133
	/* end block 1 */
	// End offset: 0x800ADA94
	// End Line: 3244

	/* begin block 2 */
		// Start line: 6555
	/* end block 2 */
	// End Line: 6556
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerPushObject(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s5*/)
void StateHandlerPushObject(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 3247, offset 0x800adac4
	/* begin block 1 */
		// Start line: 3248
		// Start offset: 0x800ADAC4
		// Variables:
			struct __Event *Ptr; // $v0

		/* begin block 1.1 */
			// Start line: 3300
			// Start offset: 0x800ADD58
			// Variables:
				struct evObjectData *data; // $s0
		/* end block 1.1 */
		// End offset: 0x800ADDB0
		// End Line: 3309
	/* end block 1 */
	// End offset: 0x800ADDCC
	// End Line: 3319

	/* begin block 2 */
		// Start line: 6879
	/* end block 2 */
	// End Line: 6880

	/* begin block 3 */
		// Start line: 6882
	/* end block 3 */
	// End Line: 6883
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerBreakOff(struct __CharacterState *In /*$s3*/, int CurrentSection /*$s4*/, int Data /*$s7*/)
void StateHandlerBreakOff(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 3322, offset 0x800addf0
	/* begin block 1 */
		// Start line: 3323
		// Start offset: 0x800ADDF0
		// Variables:
			struct __Event *Ptr; // $v0

		/* begin block 1.1 */
			// Start line: 3334
			// Start offset: 0x800ADEF4
			// Variables:
				struct PhysObInteractProperties *interactProp; // $s0
				struct _Instance *Inst; // $s1
				int anim; // $a2
		/* end block 1.1 */
		// End offset: 0x800AE07C
		// End Line: 3383

		/* begin block 1.2 */
			// Start line: 3397
			// Start offset: 0x800AE0D4
			// Variables:
				//struct PhysObInteractProperties *interactProp; // $v0
				int action; // $s1
				int condition; // $v0
				//struct _Instance *Inst; // $s0
		/* end block 1.2 */
		// End offset: 0x800AE17C
		// End Line: 3428
	/* end block 1 */
	// End offset: 0x800AE1C8
	// End Line: 3443

	/* begin block 2 */
		// Start line: 7040
	/* end block 2 */
	// End Line: 7041
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerPullSwitch(struct __CharacterState *In /*$s4*/, int CurrentSection /*$s5*/, int Data /*stack 8*/)
void StateHandlerPullSwitch(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 3446, offset 0x800ae1f4
	/* begin block 1 */
		// Start line: 3447
		// Start offset: 0x800AE1F4
		// Variables:
			struct __Event *Ptr; // $s2
			int switchDone; // stack offset -56
			int hitPosted; // stack offset -52

		/* begin block 1.1 */
			// Start line: 3459
			// Start offset: 0x800AE32C
			// Variables:
				struct PhysObSwitchProperties *switchData; // $fp

			/* begin block 1.1.1 */
				// Start line: 3465
				// Start offset: 0x800AE35C
				// Variables:
					int switchStatus; // $s1
					int switchSuccess; // $s3
					struct _Instance *inst; // $s2
					struct PhysObSwitchProperties *switchProperties; // $s0
					int extraZ; // $s6

				/* begin block 1.1.1.1 */
					// Start line: 3478
					// Start offset: 0x800AE3B0
				/* end block 1.1.1.1 */
				// End offset: 0x800AE408
				// End Line: 3490
			/* end block 1.1.1 */
			// End offset: 0x800AE534
			// End Line: 3539
		/* end block 1.1 */
		// End offset: 0x800AE534
		// End Line: 3539

		/* begin block 1.2 */
			// Start line: 3545
			// Start offset: 0x800AE544
			// Variables:
				//int switchStatus; // $v1
				//struct _Instance *inst; // $s0
				//struct PhysObSwitchProperties *switchProperties; // $s0
				int switchClass; // $s1
		/* end block 1.2 */
		// End offset: 0x800AE6C8
		// End Line: 3586

		/* begin block 1.3 */
			// Start line: 3598
			// Start offset: 0x800AE740
			// Variables:
				struct evMonsterHitData *data; // $s0
		/* end block 1.3 */
		// End offset: 0x800AE7A8
		// End Line: 3609
	/* end block 1 */
	// End offset: 0x800AE7D4
	// End Line: 3629

	/* begin block 2 */
		// Start line: 7314
	/* end block 2 */
	// End Line: 7315
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerDragObject(struct __CharacterState *In /*$s2*/, int CurrentSection /*$s4*/, int Data /*$fp*/)
void StateHandlerDragObject(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 3632, offset 0x800ae804
	/* begin block 1 */
		// Start line: 3633
		// Start offset: 0x800AE804
		// Variables:
			struct __Event *Ptr; // $s1
			struct _Instance *instance; // $s3
			int anim; // $s0
			int hitPosted; // $s7

		/* begin block 1.1 */
			// Start line: 3676
			// Start offset: 0x800AEA10
			// Variables:
				struct evPhysicsSlideData *slideData; // stack offset -48

			/* begin block 1.1.1 */
				// Start line: 3681
				// Start offset: 0x800AEA2C
				// Variables:
					struct evObjectData *data; // $s0
			/* end block 1.1.1 */
			// End offset: 0x800AED18
			// End Line: 3738
		/* end block 1.1 */
		// End offset: 0x800AED18
		// End Line: 3739

		/* begin block 1.2 */
			// Start line: 3795
			// Start offset: 0x800AEEA0
			// Variables:
				//struct evMonsterHitData *data; // $v0
		/* end block 1.2 */
		// End offset: 0x800AEEA0
		// End Line: 3796
	/* end block 1 */
	// End offset: 0x800AEEFC
	// End Line: 3810

	/* begin block 2 */
		// Start line: 7694
	/* end block 2 */
	// End Line: 7695

	/* begin block 3 */
		// Start line: 7700
	/* end block 3 */
	// End Line: 7701
					UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerPickupObject(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s0*/, int Data /*$s4*/)
void StateHandlerPickupObject(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 3813, offset 0x800aef2c
	/* begin block 1 */
		// Start line: 3814
		// Start offset: 0x800AEF2C
		// Variables:
			struct __Event *Ptr; // $v0

		/* begin block 1.1 */
			// Start line: 3822
			// Start offset: 0x800AEFE4
			// Variables:
				long colorArray[1]; // stack offset -32
		/* end block 1.1 */
		// End offset: 0x800AEFE4
		// End Line: 3822
	/* end block 1 */
	// End offset: 0x800AF128
	// End Line: 3870

	/* begin block 2 */
		// Start line: 8073
	/* end block 2 */
	// End Line: 8074
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerAutoFace(struct __CharacterState *In /*$s0*/, int CurrentSection /*$s1*/, int Data /*stack 8*/)
void StateHandlerAutoFace(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 3870, offset 0x800af148
	/* begin block 1 */
		// Start line: 3871
		// Start offset: 0x800AF148
		// Variables:
			struct __Event *Ptr; // $a0
			int Frames; // $s3
			int Anim; // $s2
	/* end block 1 */
	// End offset: 0x800AF858
	// End Line: 4077

	/* begin block 2 */
		// Start line: 8216
	/* end block 2 */
	// End Line: 8217
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ StateHandlerGlyphs(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s6*/)
void StateHandlerGlyphs(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 4083, offset 0x800af888
	/* begin block 1 */
		// Start line: 4084
		// Start offset: 0x800AF888
		// Variables:
			struct __Event *Ptr; // $s0
			int hitPosted; // $s5

		/* begin block 1.1 */
			// Start line: 4285
			// Start offset: 0x800B0018
			// Variables:
				struct evActionPlayHostAnimationData *ptr; // $v0
		/* end block 1.1 */
		// End offset: 0x800B005C
		// End Line: 4292

		/* begin block 1.2 */
			// Start line: 4295
			// Start offset: 0x800B005C
			// Variables:
				struct evMonsterHitData *data; // $v1
		/* end block 1.2 */
		// End offset: 0x800B00B0
		// End Line: 4304
	/* end block 1 */
	// End offset: 0x800B00E0
	// End Line: 4333

	/* begin block 2 */
		// Start line: 8645
	/* end block 2 */
	// End Line: 8646
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ DefaultStateHandler(struct __CharacterState *In /*$s2*/, int CurrentSection /*$s1*/, int Data /*$a2*/)
void DefaultStateHandler(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 4391, offset 0x800b0114
	/* begin block 1 */
		// Start line: 4392
		// Start offset: 0x800B0114
		// Variables:
			struct __Event *Ptr; // $s0

		/* begin block 1.1 */
			// Start line: 4411
			// Start offset: 0x800B03B4
			// Variables:
				int message; // stack offset -32
				int messageData; // stack offset -28

			/* begin block 1.1.1 */
				// Start line: 4431
				// Start offset: 0x800B0478
				// Variables:
					int i; // $s1
			/* end block 1.1.1 */
			// End offset: 0x800B04B8
			// End Line: 4437
		/* end block 1.1 */
		// End offset: 0x800B04B8
		// End Line: 4440

		/* begin block 1.2 */
			// Start line: 4602
			// Start offset: 0x800B0634
			// Variables:
				struct evPhysicsGravityData *ptr; // $v1
				short zRot; // $s0

			/* begin block 1.2.1 */
				// Start line: 4608
				// Start offset: 0x800B0640
				// Variables:
					_Position pos1; // stack offset -48
					_Position pos2; // stack offset -40
					int diff; // $v0
			/* end block 1.2.1 */
			// End offset: 0x800B0720
			// End Line: 4628
		/* end block 1.2 */
		// End offset: 0x800B0720
		// End Line: 4628

		/* begin block 1.3 */
			// Start line: 4661
			// Start offset: 0x800B07B4
			// Variables:
				struct evFXHitData *BloodData; // $a0
				struct _SVector Accel; // stack offset -48
		/* end block 1.3 */
		// End offset: 0x800B07B4
		// End Line: 4662

		/* begin block 1.4 */
			// Start line: 4710
			// Start offset: 0x800B0960
			// Variables:
				struct evPhysicsEdgeData *data; // $s0
		/* end block 1.4 */
		// End offset: 0x800B099C
		// End Line: 4716
	/* end block 1 */
	// End offset: 0x800B0A90
	// End Line: 4753

	/* begin block 2 */
		// Start line: 9276
	/* end block 2 */
	// End Line: 9277
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// long /*$ra*/ RazielAnimCallback(struct _G2Anim_Type *anim /*$s3*/, int sectionID /*$s1*/, enum _G2AnimCallbackMsg_Enum message /*$s4*/, long messageDataA /*$s5*/, long messageDataB /*stack 16*/, void *data /*stack 20*/)
long RazielAnimCallback(struct _G2Anim_Type *anim, int sectionID, enum _G2AnimCallbackMsg_Enum message, long messageDataA, long messageDataB, void *data)
{ // line 4757, offset 0x800b0aac
	/* begin block 1 */
		// Start line: 4758
		// Start offset: 0x800B0AAC
		// Variables:
			struct __State *pSection; // $a0
			struct _G2AnimSection_Type *animSection; // $a2

		/* begin block 1.1 */
			// Start line: 4776
			// Start offset: 0x800B0B70
			// Variables:
				struct evAnimationControllerDoneData *ControllerData; // $v1
		/* end block 1.1 */
		// End offset: 0x800B0BF8
		// End Line: 4792

		/* begin block 1.2 */
			// Start line: 4806
			// Start offset: 0x800B0C40
			// Variables:
				//struct __AlarmData *data; // $s0
				struct _Instance *inst; // $a0

			/* begin block 1.2.1 */
				// Start line: 4877
				// Start offset: 0x800B0E40
				// Variables:
					int test; // $a0

				/* begin block 1.2.1.1 */
					// Start line: 4897
					// Start offset: 0x800B0EA4
					// Variables:
						struct _SoundRamp *soundRamp; // $t0
				/* end block 1.2.1.1 */
				// End offset: 0x800B0FC4
				// End Line: 4912
			/* end block 1.2.1 */
			// End offset: 0x800B0FC4
			// End Line: 4912
		/* end block 1.2 */
		// End offset: 0x800B0FDC
		// End Line: 4921

		/* begin block 1.3 */
			// Start line: 4925
			// Start offset: 0x800B0FE4

			/* begin block 1.3.1 */
				// Start line: 4930
				// Start offset: 0x800B1008
				// Variables:
					struct _Instance *heldInstance; // $s0
			/* end block 1.3.1 */
			// End offset: 0x800B1048
			// End Line: 4936
		/* end block 1.3 */
		// End offset: 0x800B105C
		// End Line: 4945
	/* end block 1 */
	// End offset: 0x800B1088
	// End Line: 4960

	/* begin block 2 */
		// Start line: 10027
	/* end block 2 */
	// End Line: 10028
					UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// long /*$ra*/ RazielAnimCallbackDuringPause(struct _G2Anim_Type *anim /*$a0*/, int sectionID /*$a1*/, enum _G2AnimCallbackMsg_Enum message /*$s0*/, long messageDataA /*$s1*/, long messageDataB /*stack 16*/, void *data /*stack 20*/)
long RazielAnimCallbackDuringPause(struct _G2Anim_Type *anim, int sectionID, enum _G2AnimCallbackMsg_Enum message, long messageDataA, long messageDataB, void *data)
{ // line 4961, offset 0x800b10b0
	/* begin block 1 */
		// Start line: 4962
		// Start offset: 0x800B10B0

		/* begin block 1.1 */
			// Start line: 4971
			// Start offset: 0x800B10D0
			// Variables:
				struct evAnimationControllerDoneData *ControllerData; // $v1
		/* end block 1.1 */
		// End offset: 0x800B114C
		// End Line: 4987
	/* end block 1 */
	// End offset: 0x800B114C
	// End Line: 4992

	/* begin block 2 */
		// Start line: 10454
	/* end block 2 */
	// End Line: 10455
				UNIMPLEMENTED();
	return 0;
}

unsigned long RazielQuery(struct _Instance *instance, unsigned long Query)
{
	struct _Normal* Ptr;
	unsigned long ability;
	struct PlayerSaveData data;
	struct evShadowSegmentData* shadowData;
	
	switch (Query)
	{
	case 1:
	{
		return 1;
		break;
	}
	case 9:
	{
		return WaterStatus;
		break;
	}
	case 6:
	{
		return SetPositionData(instance->position.x, instance->position.y, instance->position.z);

		break;
	}
	case 7:
	{
		if (Raziel.steeringMode == 4)
		{
			return SetPositionData(instance->rotation.x, instance->rotation.y, Raziel.steeringLockRotation);
		}
		else
		{
			return SetPositionData(instance->rotation.x, instance->rotation.y, instance->rotation.z);
		}

		break;
	}
	case 8:
	{
		if (ExtraRot != NULL)
		{
			return (unsigned long)ExtraRot;
		}
		else
		{
			return NULL;
		}
		break;
	}
	case 10:
	{
		return Raziel.Mode;

		break;
	}
	case 11:
	{
		return Raziel.CurrentPlane;
	
		break;
	}
	case 12:
	{
		if (instance->oldMatrix != NULL)
		{
			return (unsigned long)&instance->oldMatrix[15];
		}
		else
		{
			return NULL;
		}
		break;
	}
	case 13:
	{
		if (instance->oldMatrix != NULL)
		{
			return (unsigned long)&instance->oldMatrix[0];
		}
		else
		{
			return NULL;
		}

		break;
	}
	case 16:
	{
		Ptr = (struct _Normal*)CIRC_Alloc(sizeof(_Normal));

		if (Raziel.Mode == 0x40000)
		{
			Ptr->x = instance->matrix[1].m[0][2];
			Ptr->y = instance->matrix[1].m[1][2];
			Ptr->z = instance->matrix[1].m[2][2];
		}
		else
		{
			Ptr->x = -instance->matrix[0].m[0][1];
			Ptr->y = -instance->matrix[0].m[1][1];
			Ptr->z = -instance->matrix[0].m[2][1];
		}

		return (unsigned long)Ptr;

		break;
	}
	case 19:
	{
		ability = Raziel.Abilities & 0x1FC0000;

		if ((STREAM_GetLevelWithID(instance->currentStreamUnitID)->unitFlags & 0x800) || RAZIEL_OkToShift() == 0)
		{
			ability &= 0xFEFFFFFF;
		}

		if ((Raziel.Mode & 0x40000) || Raziel.CurrentPlane == 2)
		{
			ability &= 0x1000000;
		}

		return ability;

		break;
	}
	case 24:
	{
		int ret = SetControlSaveDataData(sizeof(struct PlayerSaveData), &data);

		data.abilities = Raziel.Abilities;
		data.currentPlane = Raziel.CurrentPlane;
		data.healthScale = Raziel.HealthScale;
		data.healthBalls = Raziel.HealthBalls;
		data.manaBalls = Raziel.GlyphManaBalls;
		data.manaMax = Raziel.GlyphManaMax;
		data.playerEventHistory = Raziel.playerEventHistory;

		return ret;

		break;
	}
	case 31:
	{

		return Raziel.HealthBalls;

		break;
	}
	case 32:
	{
		return Raziel.GlyphManaBalls;

		break;
	}
	case 34:
	{
		if ((Raziel.Senses.EngagedMask & 0x40))
		{
			return ((unsigned long*)Raziel.Senses.EngagedList)[12];
		}
		else
		{
			return 0;
		}

		break;
	}
	case 38:
	{
		shadowData = (struct evShadowSegmentData*)SetShadowSegmentData(2);
		shadowData->shadowSegments[0] = 12;
		shadowData->shadowSegments[1] = 8;

		break;
	}
	case 39:
	{
		return Raziel.Senses.EngagedMask;

		break;
	}
	case 41:
	{
		return Raziel.playerEvent;

		break;
	}
	case 42:
	{
		return Raziel.playerEventHistory;

		break;
	}
	case 43:
	{
		return (Raziel.HitPoints ^ GetMaxHealth()) < 1;

		break;
	}
	case 44:
	{
		return (unsigned long)razGetHeldItem();

		break;
	}
	case 45:
	{
		return Raziel.GlyphManaMax;

		break;
	}
	case 46:
	{
		return Raziel.invincibleTimer;

		break;
	}
	}
	
	return 0;
}

void RazielPost(struct _Instance* instance, unsigned long Message, unsigned long Data)
{
	int i; // $s0
	struct PlayerSaveData* data; // $s0
	struct _G2AnimSection_Type* animSection; // $v0
	struct _Instance* heldWeapon; // $v1

	//s1 = instance
	//s2 = Message
	//s3 = Data

	//v0 = 0x10000A
	int test = 0;
	test++;
	if (Message != 0x10000A)
	{
		//v0 = 0x200000
		if (0x10000A >= Message)
		{
			if (Message == 0x40012)
			{
				//loc_800B18E0
			}
			else if (0x40012 >= Message)//v0 = 0x40000
			{
				if (Message == 0x40006)
				{
					//loc_800B16F8
				}
				else if (0x40006 >= Message)
				{
					if (Message == 0x40001)
					{
						//loc_800B16A4
					}
					else if (Message == 0x40004)
					{
						//loc_800B1728
					}
					else
					{
						//j loc_800B1BD0
						//s0 = 0
					}
				}
				else
				{
					if (Message == 0x4000E)
					{
						//loc_800B1A48

					}
					else if(0x4000E >= Message)
					{
						if (Message == 0x40008)
						{
							//loc_800B1708
						}
						else
						{
							//s0 = 0
							//j loc_800B1BD0
						}
					}
					else if (Message == 0x40011)
					{
						//loc_800B18D0

					}
					else
					{
						//s0 = 0
						//j loc_800B1BD0
					}
				}
			}
			else
			{
				//loc_800B1354
				if (Message == 0x40022)
				{
					//loc_800B1A08
				}
				else if (0x40022 >= Message)
				{
					if (Message == 0x40015)
					{
						//loc_800B190C

					}
					else
					{
						if (Message == 0x40019)
						{
							//loc_800B1718
						}
						else
						{
							//s0 = 0
							//j loc_800B1BD0
						}
					}
				}
				else
				{
					//loc_800B138C
					if (Message == 0x100007)
					{
						//loc_800B1574
					}
					else
					{
						if (0x100007 >= Message)
						{
							if (Message == 0x40024)
							{
								//loc_800B1A14
							}
							else
							{
								//s0 = 0
								//j loc_800B1BD0
							}
						}
						else
						{
							//loc_800B13B8
							if (Message == 0x100008)
							{
								//loc_800B1754
							}
							else
							{
								//s0 = 0
								//j loc_800B1BD0
							}
						}
					}
				}
			}
		}
		//loc_800B13CC
	}
	//loc_800B17BC
#if 0

		loc_800B13CC :
		li      $v0, 0x200001
		beq     $s2, $v0, loc_800B14CC
		sltu    $v0, $s2
		bnez    $v0, loc_800B1454
		lui     $v0, 0x400
		li      $v0, 0x100012
		beq     $s2, $v0, loc_800B1988
		sltu    $v0, $s2
		bnez    $v0, loc_800B1418
		lui     $v0, 0x10
		li      $v0, 0x100010
		beq     $s2, $v0, loc_800B183C
		lui     $v0, 0x10
		li      $v0, 0x100011
		beq     $s2, $v0, loc_800B196C
		move    $s0, $zero
		j       loc_800B1BD0
		nop

		loc_800B1418 :
	li      $v0, 0x100016
		beq     $s2, $v0, loc_800B1B88
		sltu    $v0, $s2
		bnez    $v0, loc_800B1444
		lui     $v0, 0x20  # ' '
		li      $v0, 0x100013
		beq     $s2, $v0, loc_800B19C4
		move    $s0, $zero
		j       loc_800B1BD0
		nop

		loc_800B1444 :
	beq     $s2, $v0, loc_800B1504
		move    $s0, $zero
		j       loc_800B1BD0
		nop

		loc_800B1454 :
	li      $v0, 0x4000001
		beq     $s2, $v0, loc_800B1650
		sltu    $v0, $s2
		bnez    $v0, loc_800B148C
		lui     $v0, 0x400
		li      $v0, 0x200004
		beq     $s2, $v0, loc_800B1530
		lui     $v0, 0x80
		li      $v0, 0x800024
		beq     $s2, $v0, loc_800B16E4
		move    $s0, $zero
		j       loc_800B1BD0
		nop

		loc_800B148C :
	li      $v0, 0x4000006
		beq     $s2, $v0, loc_800B1640
		sltu    $v0, $s2
		bnez    $v0, loc_800B14B8
		lui     $v0, 0x1000
		li      $v0, 0x4000005
		beq     $s2, $v0, loc_800B1634
		move    $s0, $zero
		j       loc_800B1BD0
		nop

		loc_800B14B8 :
	li      $v0, 0x10002000
		beq     $s2, $v0, loc_800B18FC
		move    $s0, $zero
		j       loc_800B1BD0
		nop

		loc_800B14CC :
	lw      $v0, -0x238($gp)
		lui     $v1, 4
		and $v0, $v1
		bnez    $v0, loc_800B1BF4
		nop
		jal     sub_800A4D0C
		nop
		bnez    $v0, loc_800B1BF4
		nop
		addiu   $a1, $gp, -0x9D0
		jal     sub_800A335C
		move    $a0, $s3
		j       loc_800B1BF4
		nop

		loc_800B1504 :
	lw      $v0, -0x238($gp)
		lui     $v1, 4
		and $v0, $v1
		bnez    $v0, loc_800B151C
		nop
		sw      $zero, -0x5F4($gp)

		loc_800B151C:
	lw      $v0, -0x634($gp)
		li      $v1, 0xFFFFFFDF
		and $v0, $v1
		j       loc_800B19F8
		li      $v1, 0xFFFFFFBF

		loc_800B1530 :
		lw      $v0, -0x238($gp)
		lui     $v1, 0x4000
		and $v0, $v1
		beqz    $v0, loc_800B1BF4
		move    $a0, $s1
		addiu   $a1, $gp, -0x4238
		sw      $s3, 0xC0($s1)
		jal     sub_800B3EDC
		sh      $zero, 0x2C($s3)
		jal     sub_800A5C84
		nop
		lw      $a1, 0xC0($s1)
		move    $a0, $v0
		jal     sub_8001ED78
		addiu   $a1, 0x28  # '('
		j       loc_800B1BF4
		nop

		loc_800B1574 :
	lui     $a0, 0x800D
		lw      $s0, 4($s3)
		li      $a0, aUnder      # "under"
		lw      $v0, 0($s0)
		nop
		sw      $v0, -0x5C8($gp)
		sw      $v0, -0x54A8($gp)
		jal     sub_800A7EA8
		li      $a1, 5
		bnez    $v0, loc_800B15A4
		li      $v0, 2
		lw      $v0, 4($s0)

		loc_800B15A4:
	nop
		sw      $v0, -0x598($gp)
		lhu     $v0, 8($s0)
		nop
		sh      $v0, -0x5D8($gp)
		lhu     $v0, 0xC($s0)
		nop
		sh      $v0, -0x5D6($gp)
		lw      $a0, 0xC($s0)
		jal     sub_8007C484
		nop
		lhu     $v0, 0x10($s0)
		nop
		sh      $v0, -0x5C0($gp)
		lhu     $v1, 0x12($s0)
		lw      $v0, -0x5C8($gp)
		sw      $zero, -0x5A0($gp)
		andi    $v0, 8
		sh      $v1, -0x5BE($gp)
		beqz    $v0, loc_800B15FC
		nop
		sw      $zero, -0x54A4($gp)

		loc_800B15FC:
	lw      $v0, 0x14($s0)
		nop
		sw      $v0, -0x420($gp)
		andi    $v0, 0x1000
		bnez    $v0, loc_800B1620
		li      $v0, 0x64  # 'd'
		sw      $v0, -0x5D4($gp)
		j       loc_800B1BF4
		nop

		loc_800B1620 :
	jal     sub_800A4810
		nop
		sw      $v0, -0x5D4($gp)
		j       loc_800B1BF4
		nop

		loc_800B1634 :
	sw      $s3, -0x594($gp)
		j       loc_800B1BF4
		nop

		loc_800B1640 :
	li      $v0, 0xB50
		sw      $v0, -0x594($gp)
		j       loc_800B1BF4
		nop

		loc_800B1650 :
	lw      $v0, -0x238($gp)
		nop
		andi    $v0, 8
		beqz    $v0, loc_800B1BF4
		nop
		lw      $v0, -0x634($gp)
		nop
		andi    $v0, 2
		bnez    $v0, loc_800B1BF4
		move    $s0, $zero
		addiu   $s1, $gp, -0x938

		loc_800B167C:
	move    $a0, $s1
		move    $a1, $s2
		jal     sub_80070D38
		move    $a2, $s3
		addiu   $s0, 1
		slti    $v0, $s0, 3
		bnez    $v0, loc_800B167C
		addiu   $s1, 0x11C
		j       loc_800B1BF4
		nop

		loc_800B16A4 :
	sw      $s3, 0x38($s1)
		sw      $zero, 0xB4($s1)
		lw      $v0, -0x5C4($gp)
		nop
		sw      $s3, 0x38($v0)
		lw      $v0, -0x5C4($gp)
		nop
		sw      $zero, 0xB4($v0)
		lw      $v0, -0x5A0($gp)
		nop
		beqz    $v0, loc_800B1BF4
		nop
		sw      $s3, 0x38($v0)
		lw      $v0, -0x5A0($gp)
		j       loc_800B1BF4
		sw      $zero, 0xB4($v0)

		loc_800B16E4:
	lw      $v0, 4($s3)
		nop
		sw      $v0, -0x58C($gp)
		j       loc_800B1BF4
		nop

		loc_800B16F8 :
	jal     sub_800A46C8
		move    $a0, $s3
		j       loc_800B1BF4
		nop

		loc_800B1708 :
	jal     sub_800A4D78
		move    $a0, $s3
		j       loc_800B1BF4
		nop

		loc_800B1718 :
	jal     sub_800A4DBC
		move    $a0, $s3
		j       loc_800B1BF4
		nop

		loc_800B1728 :
	li      $v0, 1
		sw      $v0, 0x28 + var_18($sp)
		addiu   $a0, $gp, -0x9CC
		li      $a1, 0x80
		move    $a2, $zero
		jal     sub_800723F0
		li      $a3, 3
		addiu   $a0, $gp, -0x9CC
		lui     $a1, 0x800A
		j       loc_800B18EC
		li      $a1, sub_8009CEB4

		loc_800B1754 :
	lw      $v0, -0x238($gp)
		lui     $v1, 0x20  # ' '
		and $v0, $v1
		beqz    $v0, loc_800B1770
		nop
		jal     sub_800B2574
		move    $a0, $s3

		loc_800B1770 :
	lhu     $v0, -0x484($gp)
		lhu     $v1, 0($s3)
		nop
		addu    $v0, $v1
		sh      $v0, -0x484($gp)
		lhu     $v0, -0x482($gp)
		lhu     $v1, 2($s3)
		nop
		addu    $v0, $v1
		sh      $v0, -0x482($gp)
		lhu     $v0, -0x480($gp)
		lhu     $v1, 4($s3)
		nop
		addu    $v0, $v1
		sh      $v0, -0x480($gp)
		jal     sub_8005E498
		nop
		j       loc_800B1BF4
		nop

		loc_800B17BC :
	beqz    $s3, loc_800B1804
		move    $s0, $zero
		lui     $v0, 0x800B
		addiu   $a0, $v0, (sub_800B0E80 - 0x800B0000)
		li      $v1, 0x1EC

		loc_800B17D0 :
		addu    $v0, $s1, $v1
		addiu   $s0, 1
		sw      $a0, 0x1C($v0)
		sw      $zero, 0x20($v0)
		slti    $v0, $s0, 3
		bnez    $v0, loc_800B17D0
		addiu   $v1, 0x30  # '0'
		jal     sub_800A1CEC
		move    $a0, $s1
		jal     sub_800A63F4
		move    $a0, $s1
		j       loc_800B1BF4
		nop

		loc_800B1804 :
	lui     $v0, 0x800B
		addiu   $a0, $v0, (sub_800B087C - 0x800B0000)
		li      $v1, 0x1EC

		loc_800B1810 :
		addu    $v0, $s1, $v1
		addiu   $s0, 1
		sw      $a0, 0x1C($v0)
		sw      $zero, 0x20($v0)
		slti    $v0, $s0, 3
		bnez    $v0, loc_800B1810
		addiu   $v1, 0x30  # '0'
		jal     sub_800A1B54
		move    $a0, $s1
		j       loc_800B1BF4
		nop

		loc_800B183C :
	beqz    $s3, loc_800B18A8
		lui     $v1, 0x4000
		lw      $v0, -0x670($gp)
		nop
		and $v0, $v1
		bnez    $v0, loc_800B1BF4
		move    $a0, $s1
		sw      $v1, -0x670($gp)
		jal     sub_8009A1AC
		li      $a1, 0xFFFFFFF0
		move    $s0, $zero
		lui     $s1, 0x800B
		move    $a0, $zero

		loc_800B1870 :
	move    $a1, $a0
		jal     sub_8007193C
		li      $a2, 3
		addiu   $a0, $gp, -0x9CC
		move    $a1, $s0
		addiu   $a2, $s1, -0x7B20
		jal     sub_80072B04
		move    $a3, $v0
		addiu   $s0, 1
		slti    $v0, $s0, 3
		bnez    $v0, loc_800B1870
		move    $a0, $zero
		j       loc_800B1BF4
		nop

		loc_800B18A8 :
	lw      $v1, -0x670($gp)
		lui     $v0, 0x4000
		and $v0, $v1, $v0
		beqz    $v0, loc_800B1BF4
		lui     $v0, 0xBFFF
		li      $v0, 0xBFFFFFFF
		and $v0, $v1, $v0
		sw      $v0, -0x670($gp)
		j       loc_800B1BF4
		nop

		loc_800B18D0 :
	jal     sub_800A4DE4
		move    $a0, $s1
		j       loc_800B1BF4
		nop

		loc_800B18E0 :
	addiu   $a0, $gp, -0x9CC
		li      $a1, sub_800A9860

		loc_800B18EC :
	jal     sub_80072BD0
		move    $a2, $zero
		j       loc_800B1BF4
		nop

		loc_800B18FC :
	jal     sub_800A5620
		move    $a0, $s1
		j       loc_800B1BF4
		nop

		loc_800B190C :
	lw      $v0, -0x5C8($gp)
		nop
		or $v0, $s3
		sw      $v0, -0x5C8($gp)
		sw      $v0, -0x54A8($gp)
		jal     sub_800A4ED0
		nop
		li      $v0, 0x3FC00
		and $v0, $s3, $v0
		beqz    $v0, loc_800B1BF4
		nop
		lw      $v0, -0x5A0($gp)
		nop
		beqz    $v0, loc_800B1BF4
		nop
		jal     sub_800A5E14
		nop
		jal     sub_800A5FF4
		move    $a0, $s3
		jal     sub_800A5FB4
		move    $a0, $v0
		j       loc_800B1BF4
		nop

		loc_800B196C :
	addiu   $a0, $gp, -0x938
		li      $a1, 0x100011
		jal     sub_80070D38
		move    $a2, $s3
		j       loc_800B1BF4
		nop

		loc_800B1988 :
	move    $a0, $s3
		jal     sub_80034648
		li      $a1, 4
		sw      $v0, -0x5E4($gp)
		li      $v1, 8
		beq     $v0, $v1, loc_800B19AC
		nop
		jal     sub_800A5D1C
		nop

		loc_800B19AC :
	lw      $v0, -0x670($gp)
		li      $v1, 0xFFFFF7FF
		and $v0, $v1
		sw      $v0, -0x670($gp)
		j       loc_800B19F0
		nop

		loc_800B19C4 :
	lw      $v0, -0x5A0($gp)
		nop
		beq     $s3, $v0, loc_800B19F0
		nop
		jal     sub_800A5E14
		nop
		bnez    $v0, loc_800B19E8
		nop
		sw      $zero, -0x5E4($gp)

		loc_800B19E8:
	jal     sub_800A5D4C
		nop

		loc_800B19F0 :
	lw      $v0, -0x634($gp)
		li      $v1, 0xFFFFFF7F

		loc_800B19F8 :
		and $v0, $v1
		sw      $v0, -0x634($gp)
		j       loc_800B1BF4
		nop

		loc_800B1A08 :
	sw      $s3, -0x434($gp)
		j       loc_800B1BF4
		nop

		loc_800B1A14 :
	jal     sub_80040818
		li      $a0, 1
		bnez    $v0, loc_800B1BF4
		li      $a1, 1
		move    $a2, $zero
		li      $a3, 0x4B  # 'K'
		lw      $a0, -0x420C($gp)
		li      $v0, 0xDAC
		sw      $v0, 0x28 + var_18($sp)
		jal     sub_8004004C
		addiu   $a0, 0x5C  # '\'
		j       loc_800B1BF4
		nop

		loc_800B1A48 :
	beqz    $s3, loc_800B1AD0
		lui     $a1, 0x800A
		li      $a1, sub_8009A90C
		sw      $a1, -0x4C8($gp)
		addiu   $a0, $gp, -0x9CC
		jal     sub_80072A8C
		move    $a2, $zero
		jal     sub_800A1B54
		move    $a0, $s1
		move    $s2, $zero
		addiu   $s1, $gp, -0x938
		addiu   $s0, $gp, -0x9C0

		loc_800B1A78:
	jal     sub_80070CD8
		move    $a0, $s0
		jal     sub_80070CD8
		move    $a0, $s1
		addiu   $s1, 0x11C
		addiu   $s2, 1
		slti    $v0, $s2, 3
		bnez    $v0, loc_800B1A78
		addiu   $s0, 0x11C
		jal     sub_800303B8
		nop
		jal     sub_800A5CBC
		nop
		move    $v1, $v0
		beqz    $v1, loc_800B1BF4
		nop
		lw      $v0, -0x5A0($gp)
		nop
		beq     $v1, $v0, loc_800B1BF4
		move    $a0, $zero
		j       loc_800B1B78
		li      $a1, 0x1000

		loc_800B1AD0:
	li      $t0, 0xFFFDFFFF
		move    $a0, $zero
		move    $a1, $a0
		li      $a2, 3
		addiu   $s2, $gp, -0x938
		addiu   $s1, $gp, -0x9C0
		li      $a3, 0xFFFFFFEF
		lw      $v0, -0x634($gp)
		lw      $v1, -0x238($gp)
		and $v0, $a3
		and $v1, $t0
		sw      $v0, -0x634($gp)
		sw      $v1, -0x238($gp)
		jal     sub_8007193C
		move    $s0, $a0
		addiu   $a0, $gp, -0x9CC
		li      $a1, sub_800A84E0
		jal     sub_80072A8C
		move    $a2, $v0

		loc_800B1B24 :
	jal     sub_80070CD8
		move    $a0, $s1
		jal     sub_80070CD8
		move    $a0, $s2
		addiu   $s2, 0x11C
		addiu   $s0, 1
		slti    $v0, $s0, 3
		bnez    $v0, loc_800B1B24
		addiu   $s1, 0x11C
		jal     sub_800303A8
		nop
		jal     sub_800A5CBC
		nop
		move    $v1, $v0
		beqz    $v1, loc_800B1BF4
		nop
		lw      $v0, -0x5A0($gp)
		nop
		beq     $v1, $v0, loc_800B1BF4
		li      $a0, 0x1000
		move    $a1, $zero

		loc_800B1B78 :
	jal     sub_800A55FC
		li      $a2, 0xA
		j       loc_800B1BF4
		nop

		loc_800B1B88 :
	move    $a0, $s1
		addiu   $a1, $gp, -0x46C
		li      $a2, 0x33  # '3'
		li      $a3, 0xFFFFFF38
		move    $v0, $a3
		sw      $v0, 0x28 + var_18($sp)
		li      $v0, 0x78  # 'x'
		sll     $s0, $s3, 12
		sw      $v0, 0x28 + var_14($sp)
		sw      $v0, 0x28 + var_10($sp)
		li      $v0, 0xDAC
		sw      $s0, 0x28 + var_C($sp)
		jal     sub_800A7D40
		sw      $v0, 0x28 + var_8($sp)
		sw      $s0, -0x43C($gp)
		sw      $zero, -0x438($gp)
		j       loc_800B1BF4
		nop

		loc_800B1BD0 :
	addiu   $s1, $gp, -0x938

		loc_800B1BD4 :
		move    $a0, $s1
		move    $a1, $s2
		jal     sub_80070D38
		move    $a2, $s3
		addiu   $s0, 1
		slti    $v0, $s0, 3
		bnez    $v0, loc_800B1BD4
		addiu   $s1, 0x11C

		loc_800B1BF4:
	lw      $ra, 0x28 + var_s10($sp)
		lw      $s3, 0x28 + var_sC($sp)
		lw      $s2, 0x28 + var_s8($sp)
		lw      $s1, 0x28 + var_s4($sp)
		lw      $s0, 0x28 + var_s0($sp)
		jr      $ra
		addiu   $sp, 0x40
#endif
}

int SetStates(struct _Instance* instance, struct GameTracker* GT, long* controlCommand, int AnalogLength)
{
	int i; // $s1
	int Event; // $s2
	int Data1; // $s3
	static unsigned long LastTime; // offset 0x0
	struct __Event *Ptr; // $v0
	struct __Event *message; // $v0
	//s4 = instance
	//s7 = GT
	//s6 = controlCommand
	Data1 = 0;
	//a0 = 0xF2000000
	LastTime = (GetRCnt(0xF2000000) & 0xFFFF) | (gameTimer << 16);

	//s5 = &Raziel.State.SectionList[0].Defer
	//s2 = &Raziel.State.SectionList[0].Event

	//s0 = 0
	//v1 = gameTimer << 16
	//a0 = LoopCounter

	PadData = controlCommand;

	gameTracker = GT;

	LoopCounter++;

	//loc_800B1C88
	for(i = 0; i < 3; i++)
	{
		Ptr = DeMessageQueue(&Raziel.State.SectionList[i].Defer);

		if (Ptr != NULL)
		{
			EnMessageQueue(&Raziel.State.SectionList[i].Event, Ptr);
			i--;//?
		}
	}

	if (instance->offset.x != 0 && instance->offset.y != 0 && instance->offset.z != 0)
	{
		//loc_800B1CD8
		INSTANCE_Post(instance, 0x4000004, LoopCounter);

		SetImpulsePhysics(instance, &Raziel);
	}
	//loc_800B1CF4

	//v0 = Raziel.Senses.HitMonster
	if (Raziel.Senses.HitMonster != NULL)
	{
		INSTANCE_Post(instance, 0x2000002, SetMonsterHitData(Raziel.Senses.HitMonster, NULL, 4096, Raziel.attack->knockBackDistance, Raziel.attack->knockBackFrames));
		
		DisableWristCollision(instance, 1);

		DisableWristCollision(instance, 2);
	}
	//loc_800B1D4C
	//v0 = gameTrackerX.playerInstance->flags

	if (!(gameTrackerX.playerInstance->flags & 0x100))
	{
		//v1 = 0x800000
		
		Event = 0;

		if ((ControlFlag & 0x800000))
		{
			//v0 = &Raziel.blankPad
			PadData = &Raziel.blankPad;

			for (i = 0; i < 3; i++)
			{
				//s0 = &Raziel.State.Event.Head
				//loc_800B1D8C
				EnMessageQueueData(&Raziel.State.SectionList[i].Event, Event, Data1);
			}
		}
		else
		{
			//loc_800B1DB4
			GetControllerMessages(controlCommand);

			//&Raziel.State.SectionList[i].Event

			while ((message = DeMessageQueue(&Raziel.padCommands)) != NULL)
			{
				Event = message->ID;

				if (Event == 0x8000)
				{
					if (!(Raziel.Senses.EngagedMask & 0x681F))
					{
						if ((Raziel.Senses.EngagedMask & 0x20))
						{
							if (razGetHeldItem() == NULL)
							{
								Event = 0x2000000;
							}
						}
					}
					else
					{
						Event = 0x2000000;
					}
				}
				//loc_800B1E14
				if (Event != 0)
				{
					for (i = 0; i < 3; i++)
					{
						EnMessageQueueData(&Raziel.State.SectionList[i].Event, Event, Data1);
					}
				}
			}
			//loc_800B1E48
			Data1 = ProcessMovement(instance, controlCommand, GT);

			if (Data1 != 0)
			{
				if ((Data1 & 0x1000))
				{
					Event = 0x1000001;
				}
				else
				{
					//loc_800B1E78
					Event = 0x10000000;
				}
			}
			else
			{
				//loc_800B1E74
				Event = 0;
			}
			//loc_800B1E78
			//s0 = &Raziel.State.SectionList[0].Event
			for (i = 0; i < 3; i++)
			{
				EnMessageQueueData(&Raziel.State.SectionList[i].Event, Event, Data1);
			}
		}
	}
	//loc_800B1EA0
	razSetPlayerEvent();

	G2EmulatePlayAnimation(&Raziel.State);

	//loc_800B1EB8
	for (i = 0; i < 3; i++)
	{
		Raziel.State.SectionList[i].Process(&Raziel.State, i, 1);
	}

	if (gameTracker->cheatMode == 1)
	{
		PhysicsMode = 3;
	}

	//loc_800B1EFC
	ProcessPhysics(&Raziel, &Raziel.State, 0, PhysicsMode);

	//v0 = PadData
	//v1 = RazielCommands[7];

	if((PadData[0] & RazielCommands[7]))
	{
		//v0 = Raziel.Senses.EngagedMask
		Raziel.nothingCounter = 0;

		//v1 = 0x2000000
		if ((Raziel.Senses.EngagedMask & 0x40))
		{
			//v0 = Raziel.Mode

			if (!(Raziel.Mode & 0x2000000))
			{
				for (i = 0; i < 3; i++)
				{
					EnMessageQueueData(&Raziel.State.SectionList[i].Event, 0x1000001, 0);
				}
			}
			//loc_800B1F80
		}
		//loc_800B1F80

		ControlFlag |= 0x4;

		if ((Raziel.Senses.EngagedMask & 0x40))
		{
			Raziel.Senses.CurrentAutoFace = Raziel.Senses.EngagedList[6].instance;
		}
		else
		{
			//loc_800B1FB8
			Raziel.Senses.CurrentAutoFace = NULL;
		}
	}
	else
	{
		//loc_800B1FC4

	}
	//loc_800B2058
#if 0

		loc_800B1FC4 :
	lw      $v0, -0x48C($gp)
		nop
		addiu   $v1, $v0, 1
		slti    $v0, $v1, 6
		sw      $v1, -0x48C($gp)
		beqz    $v0, loc_800B2038
		li      $v0, 6
		lw      $v0, -0x5F4($gp)
		nop
		andi    $v0, 0x40
		beqz    $v0, loc_800B2048
		lui     $v1, 0x200
		lw      $v0, -0x670($gp)
		nop
		and $v0, $v1
		bnez    $v0, loc_800B2048
		move    $s1, $zero
		addiu   $s0, $gp, -0x9C0

		loc_800B200C:
	move    $a0, $s0
		li      $a1, 0x1000001
		jal     sub_80070D38
		move    $a2, $zero
		addiu   $s1, 1
		slti    $v0, $s1, 3
		bnez    $v0, loc_800B200C
		addiu   $s0, 0x11C
		j       loc_800B2048
		nop

		loc_800B2038 :
	bne     $v1, $v0, loc_800B2048
		nop
		sw      $zero, -0x600($gp)
		sw      $zero, -0x604($gp)

		loc_800B2048 :
		lw      $v0, -0x238($gp)
		li      $v1, 0xFFFFFFFB
		and $v0, $v1
		sw      $v0, -0x238($gp)

		loc_800B2058 :
		addiu   $a0, $gp, -0x9CC
		li      $v0, 0xFFFFFFFF
		sw      $v0, -0x23C($gp)
		lhu     $v0, 0x5C($s4)
		lhu     $v1, 0x64($s4)
		lhu     $a2, 0xE0($s4)
		subu    $v0, $v1
		subu    $v0, $a2
		sh      $v0, -0x664($gp)
		lhu     $v0, 0x5E($s4)
		lhu     $v1, 0x66($s4)
		lhu     $a2, 0xE2($s4)
		subu    $v0, $v1
		subu    $v0, $a2
		sh      $v0, -0x662($gp)
		lhu     $v0, 0x60($s4)
		lhu     $v1, 0x68($s4)
		lhu     $a2, 0xE4($s4)
		subu    $v0, $v1
		subu    $v0, $a2
		sh      $v0, -0x660($gp)
		jal     sub_80072CC4
		li      $a1, 3
		lw      $v0, -0x4174($gp)
		nop
		andi    $v0, 0x800
		beqz    $v0, loc_800B20E4
		lui     $v1, 0x100
		lw      $v0, -0x238($gp)
		nop
		and $v0, $v1
		bnez    $v0, loc_800B20E4
		nop
		jal     sub_800A4860
		move    $a0, $s4

		loc_800B20E4 :
	lw      $v0, -0x238($gp)
		lui     $v1, 2
		and $v0, $v1
		beqz    $v0, loc_800B213C
		nop
		lw      $v0, -0x5F4($gp)
		nop
		andi    $v0, 0x400
		beqz    $v0, loc_800B2120
		move    $a0, $s4
		lw      $v0, -0x5F8($gp)
		nop
		lw      $a1, 0x50($v0)
		j       loc_800B2134
		nop

		loc_800B2120 :
	lw      $v0, -0x634($gp)
		nop
		andi    $v0, 0x10
		beqz    $v0, loc_800B213C
		move    $a1, $zero

		loc_800B2134 :
	jal     sub_800A1DEC
		nop

		loc_800B213C :
	lw      $v0, -0x238($gp)
		lui     $v1, 0x20  # ' '
		and $v0, $v1
		beqz    $v0, loc_800B2168
		nop
		lw      $v0, -0x3FD8($gp)
		nop
		beqz    $v0, loc_800B2168
		nop
		jal     sub_800B22A0
		nop

		loc_800B2168 :
	lw      $v0, -0x4B4($gp)
		nop
		beqz    $v0, loc_800B2180
		nop
		jal     sub_800B26D4
		move    $a0, $s4

		loc_800B2180 :
	jal     sub_800B2A20
		move    $a0, $s4
		jal     sub_800B30D4
		move    $a0, $s4
		lw      $v0, -0x634($gp)
		nop
		andi    $v0, 0x40
		beqz    $v0, loc_800B2210
		nop
		jal     sub_800A5854
		nop
		beqz    $v0, loc_800B2210
		nop
		lw      $a0, -0x5FC($gp)
		jal     sub_80034648
		li      $a1, 0x11
		li      $v1, 1
		beq     $v0, $v1, loc_800B2270
		nop
		lw      $a0, -0x5FC($gp)
		jal     sub_8004D6AC
		nop
		li      $a1, 1
		move    $a2, $zero
		move    $a3, $a2
		lw      $a0, -0x5FC($gp)
		li      $v0, 2
		jal     sub_80071590
		sw      $v0, 0x18 + var_8($sp)
		li      $a1, 0x8000008
		lw      $a0, -0x5FC($gp)
		jal     sub_80034684
		move    $a2, $v0
		j       loc_800B2270
		nop

		loc_800B2210 :
	lw      $a0, -0x5FC($gp)
		nop
		beqz    $a0, loc_800B226C
		nop
		jal     sub_80034648
		li      $a1, 0x11
		beqz    $v0, loc_800B226C
		nop
		lw      $a0, -0x5FC($gp)
		jal     sub_8004D6AC
		nop
		move    $a1, $zero
		move    $a2, $a1
		move    $a3, $a1
		lw      $a0, -0x5FC($gp)
		li      $v0, 2
		jal     sub_80071590
		sw      $v0, 0x18 + var_8($sp)
		li      $a1, 0x8000008
		lw      $a0, -0x5FC($gp)
		jal     sub_80034684
		move    $a2, $v0

		loc_800B226C :
	sw      $zero, -0x5FC($gp)

		loc_800B2270 :
		lw      $ra, 0x18 + var_s20($sp)
		lw      $s7, 0x18 + var_s1C($sp)
		lw      $s6, 0x18 + var_s18($sp)
		lw      $s5, 0x18 + var_s14($sp)
		lw      $s4, 0x18 + var_s10($sp)
		lw      $s3, 0x18 + var_sC($sp)
		lw      $s2, 0x18 + var_s8($sp)
		lw      $s1, 0x18 + var_s4($sp)
		lw      $s0, 0x18 + var_s0($sp)
		li      $v0, 1
		jr      $ra
		addiu   $sp, 0x40
#endif

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ ProcessConstrict()
void ProcessConstrict()
{ // line 5900, offset 0x800b2588
	/* begin block 1 */
		// Start line: 5901
		// Start offset: 0x800B2588

		/* begin block 1.1 */
			// Start line: 5942
			// Start offset: 0x800B268C
			// Variables:
				int i; // $s0

			/* begin block 1.1.1 */
				// Start line: 5990
				// Start offset: 0x800B2754
				// Variables:
					int thisIndex; // $v1
					int nextIndex; // $v0
			/* end block 1.1.1 */
			// End offset: 0x800B27B8
			// End Line: 6011
		/* end block 1.1 */
		// End offset: 0x800B284C
		// End Line: 6034
	/* end block 1 */
	// End offset: 0x800B284C
	// End Line: 6065

	/* begin block 2 */
		// Start line: 12443
	/* end block 2 */
	// End Line: 12444

	/* begin block 3 */
		// Start line: 12446
	/* end block 3 */
	// End Line: 12447
					UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ RelocateConstrict(struct _SVector *offset /*$a3*/)
void RelocateConstrict(struct _SVector *offset)
{ // line 6068, offset 0x800b285c
	/* begin block 1 */
		// Start line: 6069
		// Start offset: 0x800B285C
		// Variables:
			int i; // $a2
	/* end block 1 */
	// End offset: 0x800B29B4
	// End Line: 6097

	/* begin block 2 */
		// Start line: 12827
	/* end block 2 */
	// End Line: 12828

	/* begin block 3 */
		// Start line: 12832
	/* end block 3 */
	// End Line: 12833
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ ProcessEffects(struct _Instance *instance /*$s0*/)
void ProcessEffects(struct _Instance *instance)
{ // line 6097, offset 0x800b29bc
	/* begin block 1 */
		// Start line: 6098
		// Start offset: 0x800B29BC
		// Variables:
			struct _Instance *heldInst; // $s2

		/* begin block 1.1 */
			// Start line: 6149
			// Start offset: 0x800B2AE0
			// Variables:
				int step; // $v1
		/* end block 1.1 */
		// End offset: 0x800B2BB8
		// End Line: 6188
	/* end block 1 */
	// End offset: 0x800B2BB8
	// End Line: 6190

	/* begin block 2 */
		// Start line: 12903
	/* end block 2 */
	// End Line: 12904
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ ProcessHints()
void ProcessHints()
{ // line 6194, offset 0x800b2bd0
	/* begin block 1 */
		// Start line: 6195
		// Start offset: 0x800B2BD0
		// Variables:
			long hint; // $s0
	/* end block 1 */
	// End offset: 0x800B2CF8
	// End Line: 6256

	/* begin block 2 */
		// Start line: 13103
	/* end block 2 */
	// End Line: 13104
			UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ ProcessInteractiveMusic(struct _Instance *instance /*$a0*/)
void ProcessInteractiveMusic(struct _Instance *instance)
{ // line 6261, offset 0x800b2d08
	/* begin block 1 */
		// Start line: 6262
		// Start offset: 0x800B2D08
		// Variables:
			struct Level *level; // $s1

		/* begin block 1.1 */
			// Start line: 6279
			// Start offset: 0x800B2DB4
		/* end block 1.1 */
		// End offset: 0x800B2DD8
		// End Line: 6286
	/* end block 1 */
	// End offset: 0x800B2EA4
	// End Line: 6335

	/* begin block 2 */
		// Start line: 13237
	/* end block 2 */
	// End Line: 13238
			UNIMPLEMENTED();
}

void ProcessTimers(struct _Instance* instance)
{
	//a2 = Raziel.timeAccumulator
	//s3 = instance

	if (Raziel.timeAccumulator > 0)
	{
		Raziel.timeAccumulator -= gameTrackerX.timeMult;

		if (Raziel.timeAccumulator <= 0)
		{
			INSTANCE_Post(instance, 0x100015, -Raziel.timeAccumulator);
		}
	}
	//loc_800B2C1C
	if (Raziel.soundTimerNext > 0)
	{
		Raziel.soundTimerNext -= gameTrackerX.timeMult;

		if (Raziel.soundTimerNext <= 0)
		{
			//v0 = 
			Raziel.soundTimerNext = 0;

			switch (Raziel.soundTimerData)
			{
			case 1:
			{
				razSetupSoundRamp(instance, (struct _SoundRamp*)&Raziel.soundHandle, 19, 1000, 1000, 120, 120, 4096, 3500);
				razSetupSoundRamp(instance, (struct _SoundRamp*)&Raziel.soundHandle2, 20, 1030, 1030, 120, 120, 4096, 3500);

				Raziel.soundTimerNext = 122880;

				//v0 = Raziel.effectsFlags
				//v1 = 2
				break;
			}
			case 2:
			{
				//s2 = 0x3C000
				//a0 = instance
				razSetupSoundRamp(instance, (struct _SoundRamp*)&Raziel.soundHandle, 19, 1000, 1000, 120, 0, 245760, 3500);
				razSetupSoundRamp(instance, (struct _SoundRamp*)&Raziel.soundHandle2, 20, 1030, 1030, 120, 0, 245760, 3500);

				//j loc_800B3078

				break;
			case 3:
			{
				if (Raziel.soundHandle != 0)
				{
					SndEndLoop(Raziel.soundHandle);
				}
				break;
			}
			}
			}
			//loc_800B30A8
		}
		//loc_800B30A8
		UNIMPLEMENTED();
#if 0

		loc_800B2D74 :
		move    $a0, $s3
			addiu   $a1, $gp, -0x46C
			li      $a2, 0xD
			move    $a3, $zero
			li      $v0, 0x64  # 'd'
			sw      $v0, 0x28 + var_14($sp)
			sw      $v0, 0x28 + var_10($sp)
			li      $v0, 0x1000
			sw      $v0, 0x28 + var_C($sp)
			li      $v0, 0xDAC
			sw      $zero, -0x46C($gp)
			sw      $zero, 0x28 + var_18($sp)
			jal     sub_800A7D40
			sw      $v0, 0x28 + var_8($sp)
			li      $v0, 0xA000
			sw      $v0, -0x43C($gp)
			li      $v0, 4
			sw      $v0, -0x438($gp)
			j       loc_800B30A8
			nop

			loc_800B2DC4 : # jumptable 800B2C70 case 4
			lw      $a0, -0x454($gp)
			nop
			beqz    $a0, loc_800B2DDC
			nop
			jal     sub_80040870
			nop

			loc_800B2DDC :
		move    $a0, $s3
			addiu   $a1, $gp, -0x454
			li      $a2, 0xD
			li      $a3, 0x32  # '2'
			move    $v0, $a3
			sw      $v0, 0x28 + var_18($sp)
			li      $v0, 0x5F  # '_'
			sw      $v0, 0x28 + var_14($sp)
			sw      $v0, 0x28 + var_10($sp)
			li      $v0, 0x1000
			sw      $v0, 0x28 + var_C($sp)
			li      $v0, 0xDAC
			sw      $zero, -0x454($gp)
			jal     sub_800A7D40
			sw      $v0, 0x28 + var_8($sp)
			li      $v0, 0x7000
			sw      $v0, -0x43C($gp)
			lw      $v0, -0x4B4($gp)
			li      $v1, 5

			loc_800B2E28:
		sw      $v1, -0x438($gp)
			ori     $v0, 8
			sw      $v0, -0x4B4($gp)
			j       loc_800B30A8
			nop

			loc_800B2E3C : # jumptable 800B2C70 case 5
			lw      $a0, -0x46C($gp)
			nop
			beqz    $a0, loc_800B2E54
			nop
			jal     sub_80040870
			nop

			loc_800B2E54 :
		move    $a0, $s3
			addiu   $a1, $gp, -0x46C
			li      $a2, 0xD
			li      $a3, 0xFFFFFFEC
			move    $v0, $a3
			sw      $v0, 0x28 + var_18($sp)
			li      $v0, 0x50  # 'P'
			sw      $v0, 0x28 + var_14($sp)
			sw      $v0, 0x28 + var_10($sp)
			li      $v0, 0x1000
			sw      $v0, 0x28 + var_C($sp)
			li      $v0, 0xDAC
			sw      $zero, -0x46C($gp)
			jal     sub_800A7D40
			sw      $v0, 0x28 + var_8($sp)
			li      $v0, 0x8000
			sw      $v0, -0x43C($gp)
			li      $v0, 6
			sw      $v0, -0x438($gp)
			j       loc_800B30A8
			nop

			loc_800B2EA8 : # jumptable 800B2C70 case 6
			lw      $a0, -0x454($gp)
			nop
			beqz    $a0, loc_800B2EC0
			nop
			jal     sub_80040870
			nop

			loc_800B2EC0 :
		move    $a0, $s3
			addiu   $a1, $gp, -0x454
			li      $a2, 0xD
			li      $a3, 0x64  # 'd'
			move    $v0, $a3
			sw      $v0, 0x28 + var_18($sp)
			li      $v0, 0x4B  # 'K'
			sw      $v0, 0x28 + var_14($sp)
			sw      $v0, 0x28 + var_10($sp)
			li      $v0, 0x1000
			sw      $v0, 0x28 + var_C($sp)
			li      $v0, 0xDAC
			sw      $zero, -0x454($gp)
			jal     sub_800A7D40
			sw      $v0, 0x28 + var_8($sp)
			li      $v0, 0xA000
			sw      $v0, -0x43C($gp)
			li      $v0, 7
			sw      $v0, -0x438($gp)
			j       loc_800B30A8
			nop

			loc_800B2F14 : # jumptable 800B2C70 case 7
			lw      $a0, -0x46C($gp)
			nop
			beqz    $a0, loc_800B2F2C
			nop
			jal     sub_80040870
			nop

			loc_800B2F2C :
		move    $a0, $s3
			addiu   $a1, $gp, -0x46C
			li      $a2, 0xD
			li      $a3, 0xFFFFFF9C
			move    $v0, $a3
			sw      $v0, 0x28 + var_18($sp)
			li      $v0, 0x41  # 'A'
			sw      $v0, 0x28 + var_14($sp)
			sw      $v0, 0x28 + var_10($sp)
			li      $v0, 0x1000
			sw      $v0, 0x28 + var_C($sp)
			li      $v0, 0xDAC
			sw      $zero, -0x46C($gp)
			jal     sub_800A7D40
			sw      $v0, 0x28 + var_8($sp)
			li      $v0, 0x5000
			sw      $v0, -0x43C($gp)
			li      $v0, 8
			sw      $v0, -0x438($gp)
			j       loc_800B30A8
			nop

			loc_800B2F80 : # jumptable 800B2C70 case 8
			lw      $a0, -0x454($gp)
			nop
			beqz    $a0, loc_800B2F98
			nop
			jal     sub_80040870
			nop

			loc_800B2F98 :
		move    $a0, $s3
			addiu   $a1, $gp, -0x454
			li      $a2, 0xD
			li      $a3, 0x1E
			move    $v0, $a3
			sw      $v0, 0x28 + var_18($sp)
			li      $v0, 0x3C  # '<'
			sw      $v0, 0x28 + var_14($sp)
			sw      $v0, 0x28 + var_10($sp)
			li      $v0, 0x1000
			sw      $v0, 0x28 + var_C($sp)
			li      $v0, 0xDAC
			sw      $zero, -0x454($gp)
			jal     sub_800A7D40
			sw      $v0, 0x28 + var_8($sp)
			li      $v0, 0xA000
			sw      $v0, -0x43C($gp)
			li      $v0, 9
			sw      $v0, -0x438($gp)
			j       loc_800B30A8
			nop

			loc_800B2FEC : # jumptable 800B2C70 case 9
			lw      $a0, -0x46C($gp)
			nop
			beqz    $a0, loc_800B3004
			nop
			jal     sub_80040870
			nop

			loc_800B3004 :
		lw      $a0, -0x454($gp)
			sw      $zero, -0x46C($gp)
			beqz    $a0, loc_800B301C
			nop
			jal     sub_80040870
			nop

			loc_800B301C :
		lw      $v0, -0x4B4($gp)
			li      $v1, 0xFFFFFFFB
			sw      $zero, -0x454($gp)
			and $v0, $v1
			li      $v1, 0xFFFFFFF7
			and $v0, $v1
			sw      $v0, -0x4B4($gp)
			j       loc_800B30A8
			nop

			loc_800B3040 : # jumptable 800B2C70 case 10
			li      $v1, 0x3C000
			move    $a0, $s3
			addiu   $a1, $gp, -0x46C
			li      $a2, 0x33  # '3'
			li      $a3, 0xFFFFFF38
			move    $v0, $a3
			sw      $v0, 0x28 + var_18($sp)
			li      $v0, 0x78  # 'x'
			sw      $v0, 0x28 + var_14($sp)
			li      $v0, 0xDAC
			sw      $zero, 0x28 + var_10($sp)
			sw      $v1, 0x28 + var_C($sp)
			sw      $v0, 0x28 + var_8($sp)

loc_800B3078:
jal     sub_800A7D40
nop
sw      $zero, -0x43C($gp)
sw      $zero, -0x438($gp)
j       loc_800B30A8
nop

def_800B2C70 : # jumptable 800B2C70 default case
lw      $a0, -0x46C($gp)
nop
beqz    $a0, loc_800B30A8
nop
jal     sub_80040870
nop

loc_800B30A8 :
lw      $ra, 0x28 + var_s10($sp)
lw      $s3, 0x28 + var_sC($sp)
lw      $s2, 0x28 + var_s8($sp)
lw      $s1, 0x28 + var_s4($sp)
lw      $s0, 0x28 + var_s0($sp)
jr      $ra
addiu   $sp, 0x40
#endif
	}
}

void SetTimer(int ticks)
{
	Raziel.timeAccumulator = ticks >> 12;
}


// autogenerated function stub: 
// void /*$ra*/ ProcessSpecialAbilities(struct _Instance *instance /*$s1*/)
void ProcessSpecialAbilities(struct _Instance* instance)
{ // line 6452, offset 0x800b33bc
	/* begin block 1 */
		// Start line: 6453
		// Start offset: 0x800B33BC
		// Variables:
	unsigned long reaver; // $s0

	/* begin block 1.1 */
		// Start line: 6460
		// Start offset: 0x800B33EC
		// Variables:
	unsigned long temp; // $a0
	/* end block 1.1 */
	// End offset: 0x800B340C
	// End Line: 6469

	/* begin block 1.2 */
		// Start line: 6493
		// Start offset: 0x800B3450
		// Variables:
	struct Object* soulReaverOb; // $a1

	/* begin block 1.2.1 */
		// Start line: 6497
		// Start offset: 0x800B3460
	/* end block 1.2.1 */
	// End offset: 0x800B3460
	// End Line: 6497
/* end block 1.2 */
// End offset: 0x800B3460
// End Line: 6497

/* begin block 1.3 */
	// Start line: 6518
	// Start offset: 0x800B34B8
	// Variables:
	struct Level* level; // $a1
	/* end block 1.3 */
	// End offset: 0x800B351C
	// End Line: 6529
/* end block 1 */
// End offset: 0x800B3560
// End Line: 6548

/* begin block 2 */
	// Start line: 13631
/* end block 2 */
// End Line: 13632

/* begin block 3 */
	// Start line: 13635
/* end block 3 */
// End Line: 13636
	UNIMPLEMENTED();
}

int GetControllerMessages(long* controlCommand)
{
	if ((controlCommand[1] & RazielCommands[2]))
	{
		EnMessageQueueData(&Raziel.padCommands, 0x80000000, 0);
	}
	else
	{
		if ((controlCommand[2] & RazielCommands[2]))
		{
			EnMessageQueueData(&Raziel.padCommands, 0x20000000, 0);

		}
	}

	if ((controlCommand[1] & RazielCommands[1]))
	{
		EnMessageQueueData(&Raziel.padCommands, 0x80000002, 0);
	}
	else
	{
		if ((controlCommand[2] & RazielCommands[1]))
		{
			EnMessageQueueData(&Raziel.padCommands, 0x20000002, 0);
		}
	}

	if ((controlCommand[1] & RazielCommands[3]))
	{
		EnMessageQueueData(&Raziel.padCommands, 0x80000001, 0);
	}
	else
	{
		if ((controlCommand[2] & RazielCommands[3]))
		{
			EnMessageQueueData(&Raziel.padCommands, 0x20000001, 0);
		}
	}

	if ((controlCommand[1] & RazielCommands[7]))
	{
		EnMessageQueueData(&Raziel.padCommands, 0x80000004, 0);
	}
	else
	{
		if ((controlCommand[2] & RazielCommands[7]))
		{
			EnMessageQueueData(&Raziel.padCommands, 0x20000004, 0);
		}
	}

	if ((controlCommand[1] & RazielCommands[6]))
	{
		EnMessageQueueData(&Raziel.padCommands, 0x80000008, 0);
	}
	else
	{
		if ((controlCommand[2] & RazielCommands[6]))
		{
			EnMessageQueueData(&Raziel.padCommands, 0x20000008, 0);
		}
	}

	if ((controlCommand[1] & RazielCommands[9]))
	{
		EnMessageQueueData(&Raziel.padCommands, 0x80000020, 0);
	}
	else
	{
		if ((controlCommand[2] & RazielCommands[9]))
		{
			EnMessageQueueData(&Raziel.padCommands, 0x20000020, 0);
		}
	}

	if ((controlCommand[1] & RazielCommands[0]))
	{
		EnMessageQueueData(&Raziel.padCommands, 0x80000010, 0);
	}
	
	return 0;
}

void RazielAdditionalCollide(struct _Instance* instance, struct GameTracker* gameTracker)
{
	int rc;
	int Mode;
	short Height;
	struct evPhysicsEdgeData* Data;
	struct evPhysicsSwimData* swimData;
	struct _Instance* Inst;

	rc = 0;

	if ((ControlFlag & 0x8))
	{
		rc = 1;
	}

	if ((ControlFlag & 0x2000))
	{
		PhysicsCheckDropOff(instance, SetPhysicsDropOffData(0, -96, Raziel.dropOffHeight, Raziel.slipSlope, 256), 2);
	}

	if ((rc & 0x1))
	{
		if (gameTrackerX.cheatMode == 1)
		{
			Height = 64;
		}
		else
		{
			Height = 128;
		}

		if (Height < (instance->position.z - instance->oldPos.z))
		{
			Height = instance->position.z - instance->oldPos.z;
		}

		if ((PhysicsCheckGravity(instance, SetPhysicsGravityData(((short*)instance->matrix)[30] - (instance->matrix)->t[2], Height, 0, 0, 0, Raziel.slipSlope), 7) & 0x1))
		{
			Raziel.Senses.Flags |= 0x4;
		}
		else
		{
			Raziel.Senses.Flags &= 0xFFFFFFFB;
		}

		FX_UpdateInstanceWaterSplit(instance);
	}
	else
	{
		instance->oldTFace = NULL;
		instance->tface = NULL;
		instance->tfaceLevel = NULL;
		instance->waterFace = NULL;
		instance->waterFaceTerrain = NULL;
	}

	if ((ControlFlag & 0x400))
	{
		if (Raziel.Senses.heldClass != 3)
		{
			Data = (struct evPhysicsEdgeData*)SetPhysicsEdgeData(400, -256, 144, 0, -196, 498, &Raziel.Senses.ForwardNormal, &Raziel.Senses.AboveNormal, &Raziel.Senses.Delta);

			Mode = PhysicsCheckEdgeGrabbing(instance, gameTracker, (int)Data, 3);

			if ((Mode & 0x6) == 6)
			{
				SetPhysics(instance, 0, 0, 0, -3);

				Raziel.Senses.Flags |= 0x2;

				if (ExtraRot != NULL)
				{
					G2Anim_DisableController(&instance->anim, 1, 14);

					instance->rotation.z += ExtraRot->z;

					ExtraRot = NULL;
				}

				if (Data != NULL)
				{
					PhysicsDefaultEdgeGrabResponse(instance, Data, 0);
				}
			}
			else
			{
				Raziel.Senses.Flags &= 0xFFFFFFFD;
			}

			if ((Mode & 0x2))
			{
				Raziel.Senses.Flags |= 0x1;
			}
			else
			{
				Raziel.Senses.Flags &= 0xFFFFFFFE;
			}
		}
	}

	if ((ControlFlag & 0x100))
	{
		Inst = razGetHeldWeapon();

		swimData = (struct evPhysicsSwimData*)SetPhysicsSwimData((Raziel.Mode >> 18) & 0x1, &Raziel.iVelocity, 256, 416, 112);

		WaterStatus = PhysicsCheckSwim(instance, (int)swimData, 3);

		if ((swimData->rc & 0x10) && Inst != NULL)
		{
			if (INSTANCE_Query(Inst, 4) == 3)
			{
				G2Anim_SetSpeedAdjustment(&instance->anim, 2048);
			}
		}

		if ((swimData->rc & 0x20) && Inst != NULL)
		{
			if (INSTANCE_Query(Inst, 4) == 3)
			{
				G2Anim_SetSpeedAdjustment(&instance->anim, 4096);
			}
		}
	}
	else
	{
		WaterStatus = 32;

		FX_UpdateInstanceWaterSplit(instance);
	}

	if ((ControlFlag & 0x8000))
	{
		Mode = PhysicsCheckBlockers(instance, gameTracker, SetPhysicsEdgeData(256, -256, 80, 0, -104, 0, &Raziel.Senses.ForwardNormal, &Raziel.Senses.AboveNormal, &Raziel.Senses.Delta), 3);

		if ((Mode & 0x4))
		{
			Raziel.Senses.Flags |= 0x2;
		}
		else
		{
			Raziel.Senses.Flags &= 0xFFFFFFFD;
		}

		if ((Mode & 0x2))
		{
			Raziel.Senses.Flags |= 0x1;
		}
		else
		{
			Raziel.Senses.Flags &= 0xFFFFFFFE;
		}
	}

	if ((ControlFlag & 0x80000))
	{
		PhysicsFollowWall(instance, gameTracker, SetPhysicsWallCrawlData(0, -448, 160, -186), 7);
	}

	if ((ControlFlag & 0x4000000))
	{
		if (Raziel.attachedPlatform != NULL)
		{
			if (INSTANCE_Query(Raziel.attachedPlatform, 2) & 0x8)
			{
				PhysicsCheckLinkedMove(instance, SetPhysicsLinkedMoveData(Raziel.attachedPlatform, 2, NULL, NULL), 5);
			}
			else
			{
				PhysicsCheckLinkedMove(instance, SetPhysicsLinkedMoveData(Raziel.attachedPlatform, 0, NULL, NULL), 5);
			}
		}
	}
}


// autogenerated function stub: 
// int /*$ra*/ GetEngageEvent(struct _Instance *instance /*$a0*/)
int GetEngageEvent(struct _Instance *instance)
{ // line 6975, offset 0x800b3c78
	/* begin block 1 */
		// Start line: 6976
		// Start offset: 0x800B3C78
		// Variables:
			int Ability; // $v1
	/* end block 1 */
	// End offset: 0x800B3CC0
	// End Line: 6994

	/* begin block 2 */
		// Start line: 14764
	/* end block 2 */
	// End Line: 14765
			UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ SetupReaction(struct _Instance *player /*$s2*/, struct _Instance *instance /*$a0*/)
int SetupReaction(struct _Instance *player, struct _Instance *instance)
{ // line 6997, offset 0x800b3cd0
	/* begin block 1 */
		// Start line: 6998
		// Start offset: 0x800B3CD0
		// Variables:
			int FaceAngle; // $s3

		/* begin block 1.1 */
			// Start line: 7014
			// Start offset: 0x800B3D14
		/* end block 1.1 */
		// End offset: 0x800B3D9C
		// End Line: 7023
	/* end block 1 */
	// End offset: 0x800B3D9C
	// End Line: 7024

	/* begin block 2 */
		// Start line: 14808
	/* end block 2 */
	// End Line: 14809
			UNIMPLEMENTED();
	return 0;
}

int CheckHolding(struct _Instance* instance)
{
	return instance->LinkChild != NULL;
}

void DisableWristCollision(struct _Instance *instance, int Side)
{
	if ((Side & 0x1))
	{
		COLLIDE_SegmentCollisionOff(instance, 0x1F);
	}

	if ((Side & 0x2))
	{
		COLLIDE_SegmentCollisionOff(instance, 0x29);
	}
}


// autogenerated function stub: 
// void /*$ra*/ EnableWristCollision(struct _Instance *instance /*$s1*/, int Side /*$s0*/)
void EnableWristCollision(struct _Instance *instance, int Side)
{ // line 7065, offset 0x800b3e1c
	/* begin block 1 */
		// Start line: 14947
	/* end block 1 */
	// End Line: 14948
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// int /*$ra*/ GetCollisionType(struct _Instance *instance /*$s1*/)
int GetCollisionType(struct _Instance *instance)
{ // line 7202, offset 0x800b3e6c
	/* begin block 1 */
		// Start line: 7203
		// Start offset: 0x800B3E6C
		// Variables:
			struct _CollideInfo *collideInfo; // $s0
			struct _HSphere *S; // $v0

		/* begin block 1.1 */
			// Start line: 7217
			// Start offset: 0x800B3EB0
			// Variables:
				struct _Instance *inst; // $v1
		/* end block 1.1 */
		// End offset: 0x800B3EB0
		// End Line: 7217
	/* end block 1 */
	// End offset: 0x800B4000
	// End Line: 7273

	/* begin block 2 */
		// Start line: 15221
	/* end block 2 */
	// End Line: 15222
				UNIMPLEMENTED();
	return 0;
}

void InitGlyphSystem(struct _Instance* instance)
{
	struct Object* GlyphOb;
	struct _Instance* iGlyph;
	
	GlyphOb = (struct Object*)objectAccess[20].object;
	
	if (GlyphOb != NULL)
	{
		iGlyph = INSTANCE_BirthObject(instance, GlyphOb, 0);

		if (iGlyph != NULL)
		{
			Raziel.GlyphSystem = iGlyph;
		}
	}
}

void mdRazielProcess(struct _Instance *playerInstance, struct GameTracker *gameTracker, long *controlCommand)
{
	ProcessTimers(playerInstance);

	razClearPlayerEvent();

	ProcessRazControl(controlCommand);

	SetStates(playerInstance, gameTracker, controlCommand, -1);

	ProcessHints();

	CAMERA_Control(&theCamera, playerInstance);

	playerInstance->offset.x = 0;
	playerInstance->offset.y = 0;
	playerInstance->offset.z = 0;
	
	Raziel.collisionEdgeOffset.x = 0;
	Raziel.collisionEdgeOffset.y = 0;
	Raziel.collisionEdgeOffset.z = 0;

	Raziel.Senses.HitMonster = NULL;

	if (Raziel.GlyphSystem != NULL)
	{
		GlyphProcess(Raziel.GlyphSystem, gameTracker);
	}

	Raziel.Abilities = debugRazielFlags1;
	
	debugRazielFlags1 |= debugRazielFlags2;
}

void RazielProcess(struct _Instance *playerInstance, struct GameTracker *gameTracker)
{
#if defined(PSX_VERSION)
	
	mdRazielProcess(gameTracker->playerInstance, gameTracker, &gameTrackerX.controlCommand[0][0]);

	DebugProcess(playerInstance , &Raziel);

	Norm.z = 0;
	Norm.y = 0;
	Norm.x = 0;

#elif defined(PC_VERSION)
	struct _Instance* v2; // edi
	int* v3; // esi
	int CurrentHint; // esi

	v2 = gameTracker->playerInstance;
	v3 = gameTracker->controlCommand[0];
	ProcessTimers(v2);
	if ((ControlFlag & 0x100000) != 0)
		dword_B089C8 &= 0x2000u;
	else
		dword_B089C8 = 0;
	ProcessRazControl(v3);
	SetStates(v2, gameTracker, v3);
	CurrentHint = HINT_GetCurrentHint();
	if ((dword_B089CC & 0x2000) == 0)
	{
		if ((dword_B089C8 & 0x2000) != 0)
		{
			if (CurrentHint == -1)
				HINT_StartHint(12);
			if (CurrentHint == 12 && (int(__cdecl*)(int, int, int))stru_B0841C.SectionList[0].Process == StateHandlerGlyphs)
			{
				HINT_KillSpecificHint(12);
				HINT_StartHint(40);
			}
			if (CurrentHint == 40 && (int(__cdecl*)(int, int, int))stru_B0841C.SectionList[0].Process != StateHandlerGlyphs)
			{
				HINT_KillSpecificHint(40);
				HINT_StartHint(12);
			}
			goto LABEL_19;
		}
		if (CurrentHint != 12)
			goto LABEL_19;
	LABEL_15:
		HINT_KillSpecificHint(12);
		goto LABEL_19;
	}
	if (CurrentHint == 12)
		goto LABEL_15;
	if (CurrentHint == 40)
		HINT_KillSpecificHint(40);
LABEL_19:
	if ((dword_B089CC & 0x10000) == 0)
	{
		if ((dword_B089C8 & 0x10000) != 0)
		{
			if (CurrentHint == -1)
				HINT_StartHint(32);
		}
		else if (CurrentHint == 32)
		{
			HINT_KillSpecificHint(32);
		}
	}
	CAMERA_Control(&theCamera, v2);
	v2->offset.x = 0;
	v2->offset.y = 0;
	v2->offset.z = 0;
	word_B089BC = 0;
	word_B089BE = 0;
	word_B089C0 = 0;
	dword_B087E0 = 0;
	if (instance)
		GlyphProcess(instance, gameTracker);
	dword_B08820 = debugRazielFlags1;
	word_B08414 = 0;
	word_B08412 = 0;
	word_B08410 = 0;
	debugRazielFlags1 |= debugRazielFlags2;
#endif
}

void RazielInit(struct _Instance *instance, struct GameTracker *gameTracker)
{ 
	instance->data = instance->object->data;
	gameTracker->playerInstance = instance;
	instance->intro = NULL;
	instance->zVel = 0;
	instance->zAccl = 0;
	instance->yVel = 0;
	instance->yAccl = 0;
	instance->work0 = 0;
	instance->work1 = 0;
	instance->offset.x = 0;
	instance->offset.y = 0;
	instance->offset.z = 0;
	instance->currentMainState = 0;
	instance->currentSubState = 0;
	instance->matrix = NULL;
	instance->maxZVel = 0;
	instance->work3 = 0;
	instance->lightGroup = 0;
	instance->flags |= 0x400;
	instance->flags &= 0xFFFFFEFF;
	instance->flags2 |= 0x84;

	OBTABLE_GetInstanceCollideFunc(instance);
	OBTABLE_GetInstanceProcessFunc(instance);
	DisableWristCollision(instance, 2);
	DisableWristCollision(instance, 1);
	InitStates(instance);
}


// autogenerated function stub: 
// void /*$ra*/ RazielCollide(struct _Instance *instance /*$s0*/, struct GameTracker *gameTracker /*$a1*/)
void RazielCollide(struct _Instance *instance, struct GameTracker *gameTracker)
{ // line 7491, offset 0x800b420c
	/* begin block 1 */
		// Start line: 7492
		// Start offset: 0x800B420C
		// Variables:
			struct _CollideInfo *collideInfo; // $s2

		/* begin block 1.1 */
			// Start line: 7521
			// Start offset: 0x800B42B8
			// Variables:
				SVECTOR*offset; // $s1
		/* end block 1.1 */
		// End offset: 0x800B434C
		// End Line: 7537

		/* begin block 1.2 */
			// Start line: 7555
			// Start offset: 0x800B43EC
			// Variables:
				///SVECTOR*offset; // $a1
		/* end block 1.2 */
		// End offset: 0x800B4454
		// End Line: 7571
	/* end block 1 */
	// End offset: 0x800B4454
	// End Line: 7573

	/* begin block 2 */
		// Start line: 15836
	/* end block 2 */
	// End Line: 15837
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ RAZIEL_TurnHead(struct _Instance *instance /*$s2*/, short *rotx /*$s0*/, short *rotz /*$s1*/, struct GameTracker *gameTracker /*$a3*/)
void RAZIEL_TurnHead(struct _Instance *instance, short *rotx, short *rotz, struct GameTracker *gameTracker)
{ // line 7573, offset 0x800b4470
	/* begin block 1 */
		// Start line: 7574
		// Start offset: 0x800B4470

		/* begin block 1.1 */
			// Start line: 7578
			// Start offset: 0x800B44B4
			// Variables:
				struct _Rotation rot; // stack offset -40
		/* end block 1.1 */
		// End offset: 0x800B4598
		// End Line: 7600

		/* begin block 1.2 */
			// Start line: 7603
			// Start offset: 0x800B45BC
			// Variables:
				//struct evActionLookAroundData data; // stack offset -32
		/* end block 1.2 */
		// End offset: 0x800B467C
		// End Line: 7621
	/* end block 1 */
	// End offset: 0x800B467C
	// End Line: 7623

	/* begin block 2 */
		// Start line: 16013
	/* end block 2 */
	// End Line: 16014
				UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ RAZIEL_SetLookAround(struct _Instance *instance /*$s1*/)
void RAZIEL_SetLookAround(struct _Instance *instance)
{ // line 7623, offset 0x800b4694
	/* begin block 1 */
		// Start line: 16133
	/* end block 1 */
	// End Line: 16134
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// void /*$ra*/ RAZIEL_ResetLookAround(struct _Instance *instance /*$s1*/)
void RAZIEL_ResetLookAround(struct _Instance *instance)
{ // line 7652, offset 0x800b470c
	/* begin block 1 */
		// Start line: 16208
	/* end block 1 */
	// End Line: 16209
	UNIMPLEMENTED();
}


// autogenerated function stub: 
// long /*$ra*/ RAZIEL_OkToLookAround(struct _Instance *playerInstance /*$a0*/)
long RAZIEL_OkToLookAround(struct _Instance *playerInstance)
{ // line 7675, offset 0x800b4788
	/* begin block 1 */
		// Start line: 16266
	/* end block 1 */
	// End Line: 16267

	/* begin block 2 */
		// Start line: 16280
	/* end block 2 */
	// End Line: 16281
	UNIMPLEMENTED();
	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ TrailWaterFX(struct _Instance *instance /*$s2*/, int Segment /*$s0*/, int Bubbles /*$s7*/, int Type /*$s6*/)
void TrailWaterFX(struct _Instance *instance, int Segment, int Bubbles, int Type)
{ // line 7714, offset 0x800b4810
	/* begin block 1 */
		// Start line: 7715
		// Start offset: 0x800B4810
		// Variables:
			struct _SVector Pos; // stack offset -88
			struct _SVector Vel; // stack offset -80
			struct _SVector Accl; // stack offset -72
			int i; // $s4
			int j; // $s1
			struct Level *level; // $s5
			//struct __BubbleParams BP; // stack offset -64
	/* end block 1 */
	// End offset: 0x800B4B64
	// End Line: 7761

	/* begin block 2 */
		// Start line: 16358
	/* end block 2 */
	// End Line: 16359
			UNIMPLEMENTED();
}




