#include "CORE.H"
#include "PLANAPI.H"


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_ConvertPlanIntoEnmyPlanDataFormat(struct PlanningNode *goalNode /*$a0*/, struct EnemyPlanData *planData /*$s1*/, struct PlanningNode *planningPool /*$s2*/)
void PLANAPI_ConvertPlanIntoEnmyPlanDataFormat(struct PlanningNode *goalNode, struct EnemyPlanData *planData, struct PlanningNode *planningPool)
{ // line 131, offset 0x80097b8c
	/* begin block 1 */
		// Start line: 132
		// Start offset: 0x80097B8C
		// Variables:
			struct PlanningNode *currentNode; // $s0
			int i; // $a0
	/* end block 1 */
	// End offset: 0x80097C28
	// End Line: 151

	/* begin block 2 */
		// Start line: 262
	/* end block 2 */
	// End Line: 263

}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_FindPathBetweenNodes(struct PlanningNode *startNode /*$v0*/, struct PlanningNode *goalNode /*$v1*/, struct EnemyPlanData *planData /*$s3*/, int validNodeTypes /*$a3*/)
int PLANAPI_FindPathBetweenNodes(struct PlanningNode *startNode, struct PlanningNode *goalNode, struct EnemyPlanData *planData, int validNodeTypes)
{ // line 157, offset 0x80097c40
	/* begin block 1 */
		// Start line: 158
		// Start offset: 0x80097C40
		// Variables:
			struct PlanningNode *planningPool; // $s1
			int successFlag; // $s2
	/* end block 1 */
	// End offset: 0x80097CA8
	// End Line: 172

	/* begin block 2 */
		// Start line: 317
	/* end block 2 */
	// End Line: 318

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_DoTimingCalcsAndDrawing(long startTime /*$a0*/, struct PlanningNode *planningPool /*$s2*/)
void PLANAPI_DoTimingCalcsAndDrawing(long startTime, struct PlanningNode *planningPool)
{ // line 177, offset 0x80097cc8
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x80097CC8
		// Variables:
			int i; // $a1
			long minTime; // $s1
			long maxTime; // $s0

		/* begin block 1.1 */
			// Start line: 199
			// Start offset: 0x80097D70
		/* end block 1.1 */
		// End offset: 0x80097DCC
		// End Line: 221
	/* end block 1 */
	// End offset: 0x80097DCC
	// End Line: 222

	/* begin block 2 */
		// Start line: 361
	/* end block 2 */
	// End Line: 362

}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_AddNodeOfTypeToPool(struct _Position *pos /*$s0*/, int type /*$s2*/)
int PLANAPI_AddNodeOfTypeToPool(struct _Position *pos, int type)
{ // line 269, offset 0x80097de4
	/* begin block 1 */
		// Start line: 270
		// Start offset: 0x80097DE4
		// Variables:
			struct PlanningNode *planningPool; // $s1
			int foundHit; // $v1
			int nodePlacement; // stack offset -24
			//struct _PlanCollideInfo pci; // stack offset -40

		/* begin block 1.1 */
			// Start line: 284
			// Start offset: 0x80097E30
			// Variables:
				short _x1; // $v0
				short _y1; // $v1
				short _z1; // $t0
				struct _Position *_v0; // $s0
		/* end block 1.1 */
		// End offset: 0x80097E30
		// End Line: 284
	/* end block 1 */
	// End offset: 0x80097EAC
	// End Line: 294

	/* begin block 2 */
		// Start line: 552
	/* end block 2 */
	// End Line: 553

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_DeleteNodesFromPoolByType(int nodeSource /*$s3*/)
void PLANAPI_DeleteNodesFromPoolByType(int nodeSource)
{ // line 306, offset 0x80097ec4
	/* begin block 1 */
		// Start line: 307
		// Start offset: 0x80097EC4
		// Variables:
			struct PlanningNode *planningPool; // $s2
			struct PlanningNode *nodeToDelete; // $s0
			int i; // $s1
	/* end block 1 */
	// End offset: 0x80097F44
	// End Line: 324

	/* begin block 2 */
		// Start line: 612
	/* end block 2 */
	// End Line: 613

	/* begin block 3 */
		// Start line: 626
	/* end block 3 */
	// End Line: 627

}


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_DeleteNodeFromPoolByUnit(long streamUnitID /*$s3*/)
void PLANAPI_DeleteNodeFromPoolByUnit(long streamUnitID)
{ // line 327, offset 0x80097f60
	/* begin block 1 */
		// Start line: 328
		// Start offset: 0x80097F60
		// Variables:
			struct PlanningNode *planningPool; // $s2
			struct PlanningNode *nodeToDelete; // $s0
			int i; // $s1
	/* end block 1 */
	// End offset: 0x80097FDC
	// End Line: 347

	/* begin block 2 */
		// Start line: 683
	/* end block 2 */
	// End Line: 684

	/* begin block 3 */
		// Start line: 688
	/* end block 3 */
	// End Line: 689

}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_FindPathInGraphToTarget(struct _Position *startPos /*$a0*/, struct EnemyPlanData *planData /*$s1*/, int validNodeTypes /*$s2*/)
int PLANAPI_FindPathInGraphToTarget(struct _Position *startPos, struct EnemyPlanData *planData, int validNodeTypes)
{ // line 388, offset 0x80097ff8
	/* begin block 1 */
		// Start line: 389
		// Start offset: 0x80097FF8
		// Variables:
			struct PlanningNode *planningPool; // $s0
			struct PlanningNode *startNode; // $s0
	/* end block 1 */
	// End offset: 0x80097FF8
	// End Line: 389

	/* begin block 2 */
		// Start line: 827
	/* end block 2 */
	// End Line: 828

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_InitPlanning(void *planningPool /*$a0*/)
void PLANAPI_InitPlanning(void *planningPool)
{ // line 405, offset 0x8009805c
	/* begin block 1 */
		// Start line: 407
		// Start offset: 0x8009805C
		// Variables:
			int i; // $a1
			int j; // $a0
	/* end block 1 */
	// End offset: 0x800980D0
	// End Line: 439

	/* begin block 2 */
		// Start line: 862
	/* end block 2 */
	// End Line: 863

	/* begin block 3 */
		// Start line: 863
	/* end block 3 */
	// End Line: 864

	/* begin block 4 */
		// Start line: 885
	/* end block 4 */
	// End Line: 886

}


// autogenerated function stub: 
// short /*$ra*/ PLANAPI_PairType(struct PlanningNode *node1 /*$a0*/, struct PlanningNode *node2 /*$a1*/)
short PLANAPI_PairType(struct PlanningNode *node1, struct PlanningNode *node2)
{ // line 446, offset 0x800980dc
	/* begin block 1 */
		// Start line: 448
		// Start offset: 0x800980DC
		// Variables:
			short placement1; // $a2
			short placement2; // $a1
	/* end block 1 */
	// End offset: 0x80098118
	// End Line: 457

	/* begin block 2 */
		// Start line: 964
	/* end block 2 */
	// End Line: 965

	/* begin block 3 */
		// Start line: 965
	/* end block 3 */
	// End Line: 966

	/* begin block 4 */
		// Start line: 969
	/* end block 4 */
	// End Line: 970

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_PassThroughHit(struct PlanningNode *node1 /*$a0*/, struct PlanningNode *node2 /*$a1*/)
int PLANAPI_PassThroughHit(struct PlanningNode *node1, struct PlanningNode *node2)
{ // line 462, offset 0x80098124
	/* begin block 1 */
		// Start line: 464
		// Start offset: 0x80098124
		// Variables:
			int src1; // $a0
			int src2; // $v1
			int res; // $v1
	/* end block 1 */
	// End offset: 0x80098188
	// End Line: 485

	/* begin block 2 */
		// Start line: 997
	/* end block 2 */
	// End Line: 998

	/* begin block 3 */
		// Start line: 998
	/* end block 3 */
	// End Line: 999

	/* begin block 4 */
		// Start line: 1002
	/* end block 4 */
	// End Line: 1003

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_CheckTargetToEnemyNode(struct PlanningNode **node1 /*$s2*/, struct PlanningNode **node2 /*$s3*/)
int PLANAPI_CheckTargetToEnemyNode(struct PlanningNode **node1, struct PlanningNode **node2)
{ // line 487, offset 0x80098190
	/* begin block 1 */
		// Start line: 488
		// Start offset: 0x80098190
		// Variables:
			struct PlanningNode *planningPool; // $s0
			struct PlanningNode *temp1; // $s1
			struct PlanningNode *temp2; // $a1
	/* end block 1 */
	// End offset: 0x80098284
	// End Line: 511

	/* begin block 2 */
		// Start line: 1048
	/* end block 2 */
	// End Line: 1049

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_UpdatePlanningDatabase(struct GameTracker *gameTracker /*$a0*/, struct _Instance *player /*$s2*/)
void PLANAPI_UpdatePlanningDatabase(struct GameTracker *gameTracker, struct _Instance *player)
{ // line 517, offset 0x800982a0
	/* begin block 1 */
		// Start line: 518
		// Start offset: 0x800982A0
		// Variables:
			struct PlanningNode *planningPool; // $s1
			struct PlanningNode *node1; // stack offset -32
			struct PlanningNode *node2; // stack offset -28
			long startTime; // $s3
			int pathExistsAbove; // $s0
			int pathExistsBelow; // $v1

		/* begin block 1.1 */
			// Start line: 566
			// Start offset: 0x800984A8
		/* end block 1.1 */
		// End offset: 0x800984B4
		// End Line: 570
	/* end block 1 */
	// End offset: 0x80098720
	// End Line: 681

	/* begin block 2 */
		// Start line: 1116
	/* end block 2 */
	// End Line: 1117

}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_NumNodesInPool(void *planningPool /*$a0*/)
int PLANAPI_NumNodesInPool(void *planningPool)
{ // line 689, offset 0x8009874c
	/* begin block 1 */
		// Start line: 1491
	/* end block 1 */
	// End Line: 1492

	/* begin block 2 */
		// Start line: 1492
	/* end block 2 */
	// End Line: 1493

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_InitPlanMkrList(struct _StreamUnit *streamUnit /*$a0*/)
void PLANAPI_InitPlanMkrList(struct _StreamUnit *streamUnit)
{ // line 697, offset 0x80098760
	/* begin block 1 */
		// Start line: 698
		// Start offset: 0x80098760
		// Variables:
			int i; // $s2
			int terrainFoundFlag; // $v0
			struct Level *level; // $v0
			unsigned short numPlanMkrs; // $s3
			struct _PlanMkr *planMkrList; // $v1

		/* begin block 1.1 */
			// Start line: 712
			// Start offset: 0x800987A0
			// Variables:
				//struct _PlanCollideInfo pci; // stack offset -40

			/* begin block 1.1.1 */
				// Start line: 713
				// Start offset: 0x800987A0
				// Variables:
					short _x1; // $v0
					short _y1; // $v1
					short _z1; // $a0
					struct _Position *_v0; // $s1
			/* end block 1.1.1 */
			// End offset: 0x800987A0
			// End Line: 713

			/* begin block 1.1.2 */
				// Start line: 738
				// Start offset: 0x8009883C
				// Variables:
			/* end block 1.1.2 */
			// End offset: 0x80098854
			// End Line: 738
		/* end block 1.1 */
		// End offset: 0x80098854
		// End Line: 741
	/* end block 1 */
	// End offset: 0x80098868
	// End Line: 742

	/* begin block 2 */
		// Start line: 1507
	/* end block 2 */
	// End Line: 1508

}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_GetFlags(int type /*$a0*/)
int PLANAPI_GetFlags(int type)
{ // line 755, offset 0x80098884
	/* begin block 1 */
		// Start line: 757
		// Start offset: 0x80098884
		// Variables:
			int chk; // $v0
	/* end block 1 */
	// End offset: 0x800988E4
	// End Line: 779

	/* begin block 2 */
		// Start line: 1510
	/* end block 2 */
	// End Line: 1511

	/* begin block 3 */
		// Start line: 1641
	/* end block 3 */
	// End Line: 1642

	/* begin block 4 */
		// Start line: 1643
	/* end block 4 */
	// End Line: 1644

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_FindNodePositionInUnit(struct _StreamUnit *streamUnit /*$a0*/, struct _Position *pos /*$s3*/, int id /*$s2*/, int type /*$a3*/)
int PLANAPI_FindNodePositionInUnit(struct _StreamUnit *streamUnit, struct _Position *pos, int id, int type)
{ // line 781, offset 0x800988ec
	/* begin block 1 */
		// Start line: 782
		// Start offset: 0x800988EC

		/* begin block 1.1 */
			// Start line: 785
			// Start offset: 0x80098910
			// Variables:
				struct Level *level; // $v0
				int numPlanMkrs; // $s0
				struct _PlanMkr *planMkr; // $s1
				int i; // $s0

			/* begin block 1.1.1 */
				// Start line: 795
				// Start offset: 0x80098944
				// Variables:
					short _x1; // $v1
					short _y1; // $a0
					short _z1; // $a1
			/* end block 1.1.1 */
			// End offset: 0x80098944
			// End Line: 795
		/* end block 1.1 */
		// End offset: 0x80098970
		// End Line: 799
	/* end block 1 */
	// End offset: 0x80098974
	// End Line: 801

	/* begin block 2 */
		// Start line: 1692
	/* end block 2 */
	// End Line: 1693

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ PLANAPI_FindClosestNodePositionInUnit(struct _StreamUnit *streamUnit /*$a0*/, struct _Position *target /*$s3*/, struct _Position *pos /*$fp*/, int offset /*stack 12*/, int max /*stack 16*/, int type /*stack 20*/, int distanceCheck /*stack 24*/)
int PLANAPI_FindClosestNodePositionInUnit(struct _StreamUnit *streamUnit, struct _Position *target, struct _Position *pos, int offset, int max, int type, int distanceCheck)
{ // line 806, offset 0x80098990
	/* begin block 1 */
		// Start line: 807
		// Start offset: 0x80098990
		// Variables:
			struct Level *level; // $v0
			int numPlanMkrs; // $s0
			struct _PlanMkr *planMkr; // $s1
			struct _Position *ptr; // $s4
			int dist; // $v1
			int min_dist; // $s5
			int chk; // $s7
			int res; // $s6
			int i; // $s2

		/* begin block 1.1 */
			// Start line: 846
			// Start offset: 0x80098AC8
			// Variables:
				short _x1; // $v0
				short _y1; // $v1
				short _z1; // $a0
		/* end block 1.1 */
		// End offset: 0x80098AE0
		// End Line: 846
	/* end block 1 */
	// End offset: 0x80098AE0
	// End Line: 849

	/* begin block 2 */
		// Start line: 1749
	/* end block 2 */
	// End Line: 1750

	return 0;
}




