#include "THISDUST.H"
#include "HUMAN.H"


// autogenerated function stub: 
// void /*$ra*/ HUMAN_WaitForWeapon(struct _Instance *instance /*$s0*/, struct GameTracker *gameTracker /*$a1*/)
void HUMAN_WaitForWeapon(struct _Instance *instance, struct GameTracker *gameTracker)
{ // line 92, offset 0x8007cb40
	/* begin block 1 */
		// Start line: 184
	/* end block 1 */
	// End Line: 185

}


// autogenerated function stub: 
// struct _Instance * /*$ra*/ HUMAN_CreateWeapon(struct _Instance *instance /*$s1*/, int weaponid /*$a1*/, int segment /*$s2*/)
struct _Instance * HUMAN_CreateWeapon(struct _Instance *instance, int weaponid, int segment)
{ // line 110, offset 0x8007cbb0
	/* begin block 1 */
		// Start line: 111
		// Start offset: 0x8007CBB0
		// Variables:
			struct Object *weapon; // $a1

		/* begin block 1.1 */
			// Start line: 116
			// Start offset: 0x8007CBE8
			// Variables:
				struct _Instance *iweapon; // $s0
		/* end block 1.1 */
		// End offset: 0x8007CC3C
		// End Line: 141
	/* end block 1 */
	// End offset: 0x8007CC6C
	// End Line: 150

	/* begin block 2 */
		// Start line: 228
	/* end block 2 */
	// End Line: 229

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_Init(struct _Instance *instance /*$s1*/)
void HUMAN_Init(struct _Instance *instance)
{ // line 155, offset 0x8007cc84
	/* begin block 1 */
		// Start line: 156
		// Start offset: 0x8007CC84
		// Variables:
			struct _MonsterVars *mv; // $s0
			struct _MonsterAttributes *ma; // $v0

		/* begin block 1.1 */
			// Start line: 162
			// Start offset: 0x8007CCB4
			// Variables:
				int opinion; // $v0
				struct _MonsterAllegiances *allegiances; // $a1
		/* end block 1.1 */
		// End offset: 0x8007CD20
		// End Line: 180
	/* end block 1 */
	// End offset: 0x8007CD4C
	// End Line: 188

	/* begin block 2 */
		// Start line: 330
	/* end block 2 */
	// End Line: 331

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_CleanUp(struct _Instance *instance /*$a0*/)
void HUMAN_CleanUp(struct _Instance *instance)
{ // line 199, offset 0x8007cd7c
	/* begin block 1 */
		// Start line: 431
	/* end block 1 */
	// End Line: 432

}


// autogenerated function stub: 
// unsigned long /*$ra*/ HUMAN_Query(struct _Instance *instance /*$a0*/, unsigned long query /*$a1*/)
unsigned long HUMAN_Query(struct _Instance *instance, unsigned long query)
{ // line 207, offset 0x8007cd9c
	/* begin block 1 */
		// Start line: 208
		// Start offset: 0x8007CD9C
		// Variables:
			struct _MonsterVars *mv; // $a3
			struct _MonsterAttributes *ma; // $v1
			unsigned long ret; // $a1
	/* end block 1 */
	// End offset: 0x8007CE7C
	// End Line: 261

	/* begin block 2 */
		// Start line: 447
	/* end block 2 */
	// End Line: 448

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_DeadEntry(struct _Instance *instance /*$s1*/)
void HUMAN_DeadEntry(struct _Instance *instance)
{ // line 266, offset 0x8007ce8c
	/* begin block 1 */
		// Start line: 267
		// Start offset: 0x8007CE8C
		// Variables:
			struct _MonsterVars *mv; // $s0
	/* end block 1 */
	// End offset: 0x8007CED4
	// End Line: 274

	/* begin block 2 */
		// Start line: 566
	/* end block 2 */
	// End Line: 567

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_Dead(struct _Instance *instance /*$s1*/)
void HUMAN_Dead(struct _Instance *instance)
{ // line 287, offset 0x8007cf04
	/* begin block 1 */
		// Start line: 288
		// Start offset: 0x8007CF04
		// Variables:
			struct _MonsterVars *mv; // $s0
	/* end block 1 */
	// End offset: 0x8007CFD8
	// End Line: 316

	/* begin block 2 */
		// Start line: 608
	/* end block 2 */
	// End Line: 609

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_StunnedEntry(struct _Instance *instance /*$s0*/)
void HUMAN_StunnedEntry(struct _Instance *instance)
{ // line 321, offset 0x8007cfec
	/* begin block 1 */
		// Start line: 322
		// Start offset: 0x8007CFEC
		// Variables:
			struct _MonsterVars *mv; // $s1
	/* end block 1 */
	// End offset: 0x8007D050
	// End Line: 333

	/* begin block 2 */
		// Start line: 676
	/* end block 2 */
	// End Line: 677

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_Stunned(struct _Instance *instance /*$s1*/)
void HUMAN_Stunned(struct _Instance *instance)
{ // line 335, offset 0x8007d064
	/* begin block 1 */
		// Start line: 336
		// Start offset: 0x8007D064
		// Variables:
			struct _MonsterVars *mv; // $s0
	/* end block 1 */
	// End offset: 0x8007D0F8
	// End Line: 354

	/* begin block 2 */
		// Start line: 704
	/* end block 2 */
	// End Line: 705

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_EmbraceEntry(struct _Instance *instance /*$s0*/)
void HUMAN_EmbraceEntry(struct _Instance *instance)
{ // line 359, offset 0x8007d10c
	/* begin block 1 */
		// Start line: 360
		// Start offset: 0x8007D10C
		// Variables:
			struct _MonsterVars *mv; // $s1
	/* end block 1 */
	// End offset: 0x8007D14C
	// End Line: 367

	/* begin block 2 */
		// Start line: 752
	/* end block 2 */
	// End Line: 753

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_Embrace(struct _Instance *instance /*$s2*/)
void HUMAN_Embrace(struct _Instance *instance)
{ // line 370, offset 0x8007d168
	/* begin block 1 */
		// Start line: 371
		// Start offset: 0x8007D168
		// Variables:
			struct _MonsterVars *mv; // $s1
			struct __Event *message; // $a1
			int letgo; // $s3
			int juice; // $s0
	/* end block 1 */
	// End offset: 0x8007D314
	// End Line: 426

	/* begin block 2 */
		// Start line: 777
	/* end block 2 */
	// End Line: 778

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_IdleEntry(struct _Instance *instance /*$a0*/)
void HUMAN_IdleEntry(struct _Instance *instance)
{ // line 431, offset 0x8007d330
	/* begin block 1 */
		// Start line: 432
		// Start offset: 0x8007D330
		// Variables:
			struct _MonsterVars *mv; // $s0
	/* end block 1 */
	// End offset: 0x8007D330
	// End Line: 432

	/* begin block 2 */
		// Start line: 917
	/* end block 2 */
	// End Line: 918

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_Idle(struct _Instance *instance /*$s1*/)
void HUMAN_Idle(struct _Instance *instance)
{ // line 440, offset 0x8007d378
	/* begin block 1 */
		// Start line: 441
		// Start offset: 0x8007D378
		// Variables:
			struct _MonsterVars *mv; // $s0
			struct _MonsterAttributes *ma; // $a3
			struct _MonsterIR *ally; // $v1
			struct _MonsterIR *enemy; // $a0
	/* end block 1 */
	// End offset: 0x8007D51C
	// End Line: 491

	/* begin block 2 */
		// Start line: 935
	/* end block 2 */
	// End Line: 936

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_Flee(struct _Instance *instance /*$s1*/)
void HUMAN_Flee(struct _Instance *instance)
{ // line 496, offset 0x8007d530
	/* begin block 1 */
		// Start line: 497
		// Start offset: 0x8007D530
		// Variables:
			struct _MonsterVars *mv; // $s0
			struct _MonsterIR *enemy; // $s2

		/* begin block 1.1 */
			// Start line: 505
			// Start offset: 0x8007D588
			// Variables:
				struct _MonsterAttributes *ma; // $v0
		/* end block 1.1 */
		// End offset: 0x8007D5EC
		// End Line: 517
	/* end block 1 */
	// End offset: 0x8007D670
	// End Line: 535

	/* begin block 2 */
		// Start line: 1053
	/* end block 2 */
	// End Line: 1054

}


// autogenerated function stub: 
// void /*$ra*/ HUMAN_GetAngry()
void HUMAN_GetAngry()
{ // line 540, offset 0x8007d688
	/* begin block 1 */
		// Start line: 541
		// Start offset: 0x8007D688
		// Variables:
			struct _Instance *instance; // $s0

		/* begin block 1.1 */
			// Start line: 548
			// Start offset: 0x8007D6C4
			// Variables:
				struct _MonsterVars *mv; // $v0
				struct _MonsterAllegiances *allegiances; // $a0
				struct _MonsterIR *mir; // $v1
		/* end block 1.1 */
		// End offset: 0x8007D72C
		// End Line: 563
	/* end block 1 */
	// End offset: 0x8007D73C
	// End Line: 565

	/* begin block 2 */
		// Start line: 1141
	/* end block 2 */
	// End Line: 1142

	/* begin block 3 */
		// Start line: 1144
	/* end block 3 */
	// End Line: 1145

}


// autogenerated function stub: 
// int /*$ra*/ HUMAN_TypeOfHuman(struct _Instance *instance /*$s0*/)
int HUMAN_TypeOfHuman(struct _Instance *instance)
{ // line 567, offset 0x8007d750
	/* begin block 1 */
		// Start line: 568
		// Start offset: 0x8007D750
		// Variables:
			int type; // $v1
			struct _MonsterVars *mv; // $a0
	/* end block 1 */
	// End offset: 0x8007D7AC
	// End Line: 580

	/* begin block 2 */
		// Start line: 1219
	/* end block 2 */
	// End Line: 1220

	return 0;
}




