#include "CORE.H"
#include "CAMERA.H"
#include "MATH3D.H"
#include "GAMELOOP.H"
#include "STREAM.H"

short camera_still;
short shorten_flag;
short shorten_count;
short combat_cam_debounce;

struct _SVector camera_shakeOffset[16];
MATRIX wcTransformX;
MATRIX wcTransform2X;
MATRIX cwTransform2X;

void CAMERA_CalculateViewVolumeNormals(struct Camera *camera)
{
	short projDistance;
	struct _Normal n0;
	struct _Normal n1;
	struct _Normal n2;
	struct _Normal n3;
	int x1;
	int x2;
	int y1;
	int y2;

	x1 = (camera->core.leftX - 160) << 4;
	projDistance = camera->core.projDistance << 4;
	x2 = (camera->core.rightX - 160) << 4;
	y1 = (camera->core.topY - 120) << 4;
	y2 = (camera->core.bottomY - 120) << 4;

	n0.z = projDistance;
	n1.z = projDistance;
	n2.z = projDistance;
	n3.z = projDistance;

	n0.x = x1;
	n0.y = y1;

	n1.x = x2;
	n1.y = y1;

	n2.x = x1;
	n2.y = y2;

	n3.x = x2;
	n3.y = y2;

	camera->core.viewVolumeNormal[0].x = 0;
	camera->core.viewVolumeNormal[0].y = 0;
	camera->core.viewVolumeNormal[0].z = 4096;

	camera->core.viewVolumeNormal[1].x = (((n0.y * n1.z) - (n0.z * n1.y)) >> 12);
	camera->core.viewVolumeNormal[1].y = -(((n0.x * n1.z) - (n0.z * n1.x)) >> 12);
	camera->core.viewVolumeNormal[1].z = (((n0.x * n1.y) - (n0.y * n1.x)) >> 12);

	CAMERA_Normalize((_SVector*)&camera->core.viewVolumeNormal[1]);

	camera->core.viewVolumeNormal[2].x = (((n2.y * n0.z) - (n2.z * n0.y)) >> 12);
	camera->core.viewVolumeNormal[2].y = -(((n2.x * n0.z) - (n2.z * n0.x)) >> 12);
	camera->core.viewVolumeNormal[2].z = (((n2.x * n0.y) - (n2.y * n0.x)) >> 12);

	CAMERA_Normalize((_SVector*)&camera->core.viewVolumeNormal[2]);

	camera->core.viewVolumeNormal[3].x = (((n1.y * n3.z) - (n1.z * n3.y)) >> 12);
	camera->core.viewVolumeNormal[3].y = -(((n1.x * n3.z) - (n1.z * n3.x)) >> 12);
	camera->core.viewVolumeNormal[3].z = (((n1.x * n3.y) - (n1.y * n3.x)) >> 12);

	CAMERA_Normalize((_SVector*)&camera->core.viewVolumeNormal[3]);

	camera->core.viewVolumeNormal[4].x = (((n3.y * n2.z) - (n3.z * n2.y)) >> 12);
	camera->core.viewVolumeNormal[4].y = -(((n3.x * n2.z) - (n3.z * n2.x)) >> 12);
	camera->core.viewVolumeNormal[4].z = (((n3.x * n2.y) - (n3.y * n2.x)) >> 12);

	CAMERA_Normalize((_SVector*)&camera->core.viewVolumeNormal[4]);
}

void CAMERA_CalcVVClipInfo(struct Camera* camera)
{
	ApplyMatrixSV(camera->core.cwTransform2, (SVECTOR*)&camera->core.viewVolumeNormal[0], (SVECTOR*)&camera->core.vvNormalWorVecMat[0].m[0][0]);
	ApplyMatrixSV(camera->core.cwTransform2, (SVECTOR*)&camera->core.viewVolumeNormal[1], (SVECTOR*)&camera->core.vvNormalWorVecMat[0].m[1][0]);
	ApplyMatrixSV(camera->core.cwTransform2, (SVECTOR*)&camera->core.viewVolumeNormal[2], (SVECTOR*)&camera->core.vvNormalWorVecMat[0].m[2][0]);
	ApplyMatrixSV(camera->core.cwTransform2, (SVECTOR*)&camera->core.viewVolumeNormal[3], (SVECTOR*)&camera->core.vvNormalWorVecMat[1].m[1][0]);
	ApplyMatrixSV(camera->core.cwTransform2, (SVECTOR*)&camera->core.viewVolumeNormal[4], (SVECTOR*)&camera->core.vvNormalWorVecMat[1].m[2][0]);

	gte_SetRotMatrix(camera->core.vvNormalWorVecMat[0]);
	gte_ldv0(camera->core.position);
	gte_mvmva(1, 0, 0, 3, 0);
	gte_stlvnl(camera->core.vvPlaneConsts[0]);

	gte_SetRotMatrix(camera->core.vvNormalWorVecMat[1]);
	gte_ldv0(camera->core.position);
	gte_mvmva(1, 0, 0, 3, 0);
	gte_stlvnl(camera->core.vvPlaneConsts[3]);
}

void CAMERA_SetViewVolume(struct Camera *camera)
{
	CAMERA_CalculateViewVolumeNormals(camera);
	CAMERA_CalcVVClipInfo(camera);
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetProjDistance(struct Camera *camera /*$s3*/, long distance /*$s0*/)
void CAMERA_SetProjDistance(struct Camera *camera, long distance)
{ // line 280, offset 0x80014b70
	/* begin block 1 */
		// Start line: 281
		// Start offset: 0x80014B70
		// Variables:
			struct Level *level; // $s0
			int i; // $s2
	/* end block 1 */
	// End offset: 0x80014BF4
	// End Line: 300

	/* begin block 2 */
		// Start line: 589
	/* end block 2 */
	// End Line: 590

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CreateNewFocuspoint(struct Camera *camera /*$s0*/)
void CAMERA_CreateNewFocuspoint(struct Camera *camera)
{ // line 302, offset 0x80014c14
	/* begin block 1 */
		// Start line: 303
		// Start offset: 0x80014C14
		// Variables:
			struct _SVector sv; // stack offset -24

		/* begin block 1.1 */
			// Start line: 303
			// Start offset: 0x80014C14
			// Variables:
				short _x0; // $v1
				short _y0; // $a0
				short _z0; // $a1
				short _x1; // $v0
				short _y1; // $a2
				short _z1; // $a3
				struct _SVector *_v; // $v0
		/* end block 1.1 */
		// End offset: 0x80014C14
		// End Line: 303

		/* begin block 1.2 */
			// Start line: 303
			// Start offset: 0x80014C14
			// Variables:
				//short _x0; // $v0
				//short _y0; // $v0
				//short _z0; // $v1
				//_Position *_v; // $a2
		/* end block 1.2 */
		// End offset: 0x80014C14
		// End Line: 303
	/* end block 1 */
	// End offset: 0x80014C14
	// End Line: 303

	/* begin block 2 */
		// Start line: 644
	/* end block 2 */
	// End Line: 645

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SaveMode(struct Camera *camera /*$a0*/, long mode /*$a1*/)
void CAMERA_SaveMode(struct Camera *camera, long mode)
{ // line 315, offset 0x80014cb8
	/* begin block 1 */
		// Start line: 317
		// Start offset: 0x80014CB8
		// Variables:
			long i; // $t4
	/* end block 1 */
	// End offset: 0x80014FE8
	// End Line: 357

	/* begin block 2 */
		// Start line: 674
	/* end block 2 */
	// End Line: 675

	/* begin block 3 */
		// Start line: 675
	/* end block 3 */
	// End Line: 676

	/* begin block 4 */
		// Start line: 677
	/* end block 4 */
	// End Line: 678

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_RestoreMode(struct Camera *camera /*$s0*/)
void CAMERA_RestoreMode(struct Camera *camera)
{ // line 359, offset 0x80014ff0
	/* begin block 1 */
		// Start line: 360
		// Start offset: 0x80014FF0

		/* begin block 1.1 */
			// Start line: 372
			// Start offset: 0x80015014
			// Variables:
				long mode; // $s1
		/* end block 1.1 */
		// End offset: 0x80015484
		// End Line: 485
	/* end block 1 */
	// End offset: 0x80015484
	// End Line: 486

	/* begin block 2 */
		// Start line: 770
	/* end block 2 */
	// End Line: 771

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Save(struct Camera *camera /*$a0*/, long save /*$a1*/)
void CAMERA_Save(struct Camera *camera, long save)
{ // line 489, offset 0x80015498
	/* begin block 1 */
		// Start line: 490
		// Start offset: 0x80015498

		/* begin block 1.1 */
			// Start line: 493
			// Start offset: 0x800154A8
			// Variables:
				int i; // $a2
		/* end block 1.1 */
		// End offset: 0x80015510
		// End Line: 505
	/* end block 1 */
	// End offset: 0x80015558
	// End Line: 520

	/* begin block 2 */
		// Start line: 1060
	/* end block 2 */
	// End Line: 1061

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Restore(struct Camera *camera /*$a0*/, long restore /*$a1*/)
void CAMERA_Restore(struct Camera *camera, long restore)
{ // line 524, offset 0x80015568
	/* begin block 1 */
		// Start line: 1133
	/* end block 1 */
	// End Line: 1134

}


// autogenerated function stub: 
// struct _SVector * /*$ra*/ SplineGetNextPointDC(struct Spline *spline /*$s0*/, struct SplineDef *def /*$s1*/)
struct _SVector * SplineGetNextPointDC(struct Spline *spline, struct SplineDef *def)
{ // line 564, offset 0x80015624
	/* begin block 1 */
		// Start line: 565
		// Start offset: 0x80015624
		// Variables:
			static struct _SVector point; // offset 0x0
	/* end block 1 */
	// End offset: 0x8001566C
	// End Line: 576

	/* begin block 2 */
		// Start line: 1219
	/* end block 2 */
	// End Line: 1220

	return null;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetMode(struct Camera *camera /*$s2*/, long mode /*$s3*/)
void CAMERA_SetMode(struct Camera *camera, long mode)
{ // line 578, offset 0x80015680
	/* begin block 1 */
	//	// Start line: 579
	//	// Start offset: 0x80015680
	//	// Variables:
	//		int oldMode; // $s0
	//		struct SplineDef curPositional; // stack offset -56
	//		struct _SVector sv; // stack offset -48

	//	/* begin block 1.1 */
	//		// Start line: 624
	//		// Start offset: 0x80015754
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $a0
	//			short _z1; // $a1
	//			struct _Rotation *_v0; // $v0
	//			struct _Rotation *_v1; // $v1
	//	/* end block 1.1 */
	//	// End offset: 0x80015754
	//	// End Line: 624

	//	/* begin block 1.2 */
	//		// Start line: 624
	//		// Start offset: 0x80015754
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $a0
	//			short _z1; // $v1
	//			struct _Rotation *_v0; // $v0
	//	/* end block 1.2 */
	//	// End offset: 0x80015754
	//	// End Line: 624

	//	/* begin block 1.3 */
	//		// Start line: 624
	//		// Start offset: 0x80015754
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $a1
	//			short _z0; // $v1
	//			short _x1; // $a2
	//			short _y1; // $a3
	//			short _z1; // $t0
	//			struct _SVector *_v; // $a0
	//			_Position *_v0; // $v1
	//	/* end block 1.3 */
	//	// End offset: 0x80015754
	//	// End Line: 624

	//	/* begin block 1.4 */
	//		// Start line: 684
	//		// Start offset: 0x800158B0
	//		// Variables:
	//			struct _SVector *camPos; // stack offset -32
	//			struct _SVector *targetPos; // $a0

	//		/* begin block 1.4.1 */
	//			// Start line: 689
	//			// Start offset: 0x800158C4
	//			// Variables:
	//				_Position pos; // stack offset -40
	//		/* end block 1.4.1 */
	//		// End offset: 0x800158C4
	//		// End Line: 691

	//		/* begin block 1.4.2 */
	//			// Start line: 705
	//			// Start offset: 0x80015970
	//			// Variables:
	//				short _x1; // $v0
	//				short _y1; // $v1
	//				short _z1; // $a0
	//				_Position *_v0; // $v0
	//		/* end block 1.4.2 */
	//		// End offset: 0x80015970
	//		// End Line: 705

	//		/* begin block 1.4.3 */
	//			// Start line: 715
	//			// Start offset: 0x800159C4
	//			// Variables:
	//				short _x1; // $v0
	//				short _y1; // $v1
	//				short _z1; // $a0
	//				_Position *_v0; // $v0
	//		/* end block 1.4.3 */
	//		// End offset: 0x800159E0
	//		// End Line: 715
	//	/* end block 1.4 */
	//	// End offset: 0x800159E0
	//	// End Line: 719
	///* end block 1 */
	//// End offset: 0x80015B14
	//// End Line: 771

	///* begin block 2 */
	//	// Start line: 1252
	///* end block 2 */
	//// End Line: 1253

}

void CAMERA_Initialize(struct Camera *camera)
{
	long i; // $s2

	//s1 = camera

	//a1 = 0
	//a2 = 0x4C4
	memset(camera, 0, sizeof(Camera));

	i = 0;



	//loc_80015F18
	for (i = 0; i < 16; i++)
	{
#define RAND(i, c) int r = rand(); int r2 = r; if(r < 0) { r2 = r + 255; } camera_shakeOffset[i].c = (r - ((r2 >> 8) << 8)) - 128;

		//RAND(i, x);
		//RAND(i, y);
		//RAND(i, z);

		int r = rand();
		int r2 = r;

		if (r < 0)
		{
			r2 = r + 255;
		}

		camera_shakeOffset[i].x = (r - ((r2 >> 8) << 8)) - 128;

		r = rand();
		r2 = r >> 8;
		if (r < 0)
		{
			r2 = r + 255;
		}
		r2 <<= 8;
		camera_shakeOffset[i].y = (r - r2) - 128;

		r = rand();
		r2 = r >> 8;
		if (r < 0)
		{
			r2 = r + 255;
		}

		r2 <<= 8;
		camera_shakeOffset[i].z = (r - r2) - 128;
	}

	//a0 = 0x13240
	//v0 = 0xFC7
	//v1 = 0x5DC

	camera->core.rotation.x = 4039;
	camera->targetRotation.x = 4039;
	camera->focusRotation.x = 4039;
	camera->targetFocusRotation.x = 4039;

	//v0 = 2250
	camera->focusDistanceList[0][0] = 1500;
	camera->focusDistanceList[1][0] = 1500;
	camera->focusDistanceList[0][1] = 2250;
	camera->focusDistanceList[1][1] = 2000;
	camera->focusDistanceList[2][2] = 2000;
	
	//v1 = (short)camera->focusDistanceList[0][1]
	//v0 = 0xA28
	camera->focusDistanceList[0][2] = 3200;
	camera->focusDistanceList[1][2] = 2600;
	camera->focusDistanceList[2][0] = 1200;
	camera->focusDistanceList[2][1] = 1600;
	//v0 = 0xFC7
	camera->tiltList[0][0] = 4039;
	camera->tiltList[0][1] = 4039;
	camera->tiltList[0][2] = 4039;
	camera->tiltList[1][0] = 4039;
	camera->tiltList[1][1] = 4039;
	camera->tiltList[1][2] = 4039;
	camera->tiltList[2][0] = 4039;
	camera->tiltList[2][1] = 4039;
	camera->tiltList[2][2] = 4039;

	constexpr int test = 556 - offsetof(Camera, focusDistanceList[2][1]);
	//v0 = 0x118
	camera->smallBaseSphere.radiusSquared = 78400;
	camera->focusSphere.radiusSquared = 78400;
	camera->posSphere.radiusSquared = 78400;

	//a0 = 0x140
	camera->smallBaseSphere.radius = 320;
	camera->focusSphere.radius = 320;
	camera->posSphere.radius = 320;

	camera->core.nearPlane = 50;

	//v0 = 0x2EE0
	camera->core.projDistance = 320;

	camera->targetFocusDistance = (short)camera->focusDistanceList[0][1];
	camera->focusDistance = (short)camera->focusDistanceList[0][1];
	camera->core.farPlane = 12000;

	//v0 = 0xF0
	camera->core.bottomY = 240;
	//v0 = &wcTransformX
	camera->core.wcTransform = &wcTransformX;
	//v0 = &wcTransform2X
	camera->core.wcTransform2 = &wcTransform2X;
	//v0 = &cwTransform2X
	camera->core.cwTransform2 = &cwTransform2X;

#if 0
		li      $v0, 0x10
		sh      $v0, 0x1C4($s1)
		li      $v0, 0xC8
		sw      $zero, 0xA0($s1)
		sw      $a0, 0xA4($s1)
		sw      $zero, 0xA8($s1)
		sh      $v0, 0x194($s1)
		sh      $zero, 0x4AE($s1)
		sh      $zero, 0x4B0($s1)
		ulw     $a3, 0x100($s1)
		lh      $t0, 0x104($s1)
		usw     $a3, 0x4A8($s1)
		sh      $t0, 0x4AC($s1)
		lhu     $v1, 0x104($s1)
		li      $v0, 0x200
		sw      $v0, 0x1FC($s1)
		lw      $v0, 0xE8($s1)
		li      $s3, 0x1000
		sw      $zero, 0x420($s1)
		sw      $zero, 0x41C($s1)
		sh      $zero, -0x71BC($gp)
		sh      $zero, -0x71BA($gp)
		sw      $s3, 0x200($s1)
		sh      $v1, 0x4BA($s1)
		lw      $v1, 0x108($s1)
		ori     $v0, 0x800
		beqz    $v1, loc_80016110
		sw      $v0, 0xE8($s1)
		jal     sub_8001C224
		move    $a0, $s1

		loc_80016110 :
	move    $a0, $s1
		li      $s2, 2
		lw      $a1, -0x6E88($gp)
		li      $s0, 1
		sh      $s0, 0x1F4($s1)
		jal     sub_80015A3C
		sh      $zero, 0xF0($s1)
		addiu   $a0, $s1, 8
		li      $v0, 0xBB8
		sw      $v0, 0x21C($s1)
		lw      $v0, 0xE8($s1)
		li      $v1, 0xFFFFFFFF
		sw      $zero, 0x218($s1)
		sh      $s0, 0x40C($s1)
		sh      $s3, 0xBE($s1)
		sh      $s3, 0xBC($s1)
		sh      $s3, 0xBA($s1)
		sh      $v1, 0x278($s1)
		sh      $v1, 0x27A($s1)
		ori     $v0, 0x8000
		sw      $v0, 0xE8($s1)

		loc_80016164:
	sw      $zero, 0x27C($a0)
		addiu   $s2, -1
		bgez    $s2, loc_80016164
		addiu   $a0, -4
		move    $a0, $s1
		li      $a1, 0x140
		move    $v0, $a1
		jal     sub_80014F2C
		sw      $v0, 0x68($s1)
		sh      $zero, 0x436($s1)
		lw      $ra, 0x10 + var_s10($sp)
		lw      $s3, 0x10 + var_sC($sp)
		lw      $s2, 0x10 + var_s8($sp)
		lw      $s1, 0x10 + var_s4($sp)
		lw      $s0, 0x10 + var_s0($sp)
		li      $v0, 0x200
		sh      $v0, -0x5374($gp)
		li      $v0, 0x28A
		sh      $v0, -0x5372($gp)
		li      $v0, 0xA
		sw      $v0, -0x4EA4($gp)
		li      $v0, 0xFFFFFFFF
		sh      $v0, -0x5424($gp)
		li      $v0, 0xBB8
		sh      $v0, -0x542C($gp)
		li      $v0, 0x1000
		sw      $zero, -0x71B4($gp)
		sw      $zero, -0x71B0($gp)
		sw      $zero, -0x71AC($gp)
		sh      $zero, -0x542A($gp)
		sh      $v0, -0x5428($gp)
		sh      $zero, -0x5426($gp)
		jr      $ra
		addiu   $sp, 0x28
#endif
}

void CAMERA_SetInstanceFocus(struct Camera *camera, struct _Instance *instance)
{
	camera->focusInstance = instance;
	camera->flags |= 0x800;

	camera->newFocusInstancePos.x = instance->position.x;
	camera->newFocusInstancePos.y = instance->position.y;
	camera->newFocusInstancePos.z = instance->position.z;

	if (instance->object != NULL)
	{
		if (instance == gameTrackerX.playerInstance)
		{
			camera->focusOffset.z = 352;
		}
		else
		{
			camera->focusOffset.z = 512;
		}

		camera->focusOffset.x = 0;
		camera->focusOffset.y = 0;
	}
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetZRotation(struct Camera *camera /*$a0*/, short zrot /*$a1*/)
void CAMERA_SetZRotation(struct Camera *camera, short zrot)
{ // line 1051, offset 0x80015e90
	/* begin block 1 */
		// Start line: 2552
	/* end block 1 */
	// End Line: 2553

	/* begin block 2 */
		// Start line: 2553
	/* end block 2 */
	// End Line: 2554

}

long CAMERA_LengthSVector(struct _SVector* sv)
{
	return MATH3D_FastSqrt0((sv->x * sv->x) + (sv->y * sv->y) + (sv->z * sv->z));
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetValue(struct Camera *camera /*$a0*/, long index /*$a1*/, long value /*$a2*/)
void CAMERA_SetValue(struct Camera *camera, long index, long value)
{ // line 1115, offset 0x80015f08
	/* begin block 1 */
		// Start line: 1117
		// Start offset: 0x80015F08
		// Variables:
			long min; // $t1
			long max; // $t0
			long minTilt; // $a3
			long maxTilt; // $a1
	/* end block 1 */
	// End offset: 0x8001632C
	// End Line: 1169

	/* begin block 2 */
		// Start line: 2680
	/* end block 2 */
	// End Line: 2681

	/* begin block 3 */
		// Start line: 2681
	/* end block 3 */
	// End Line: 2682

}


// autogenerated function stub: 
// short /*$ra*/ CAMERA_AngleDifference(short angle0 /*$t0*/, short angle1 /*$a3*/)
short CAMERA_AngleDifference(short angle0, short angle1)
{ // line 1172, offset 0x80016334
	/* begin block 1 */
		// Start line: 2798
	/* end block 1 */
	// End Line: 2799

	/* begin block 2 */
		// Start line: 2799
	/* end block 2 */
	// End Line: 2800

	return 0;
}


// autogenerated function stub: 
// short /*$ra*/ CAMERA_SignedAngleDifference(short angle0 /*$a0*/, short angle1 /*$a1*/)
short CAMERA_SignedAngleDifference(short angle0, short angle1)
{ // line 1189, offset 0x800163ac
	/* begin block 1 */
		// Start line: 2832
	/* end block 1 */
	// End Line: 2833

	return 0;
}

unsigned long CAMERA_QueryMode(struct Camera *camera)
{
	unsigned long mode;

	mode = INSTANCE_Query(camera->focusInstance, 10);

	if (camera->focusInstance == gameTrackerX.playerInstance)
	{
		if ((mode & 0x2000000))
		{
			combat_cam_debounce = 1;
		}
		else
		{
			if (combat_cam_debounce > 0)
			{
				combat_cam_debounce--;

				mode |= 0x2000000;
			}
		}
	}
	else
	{
		mode &= 0xFDFFFFFF;
	}

	if (WARPGATE_IsWarpgateActive() != 0)
	{
		mode |= 0x80000000;
	}

	return mode;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetMaxVel(struct Camera *camera /*$s1*/)
void CAMERA_SetMaxVel(struct Camera *camera)
{ // line 1232, offset 0x80016478
	/* begin block 1 */
		// Start line: 1233
		// Start offset: 0x80016478
		// Variables:
			long extraVel; // $s0
			long targetMaxVel; // $v0
			struct _SVector cam_dist; // stack offset -24
			static long maxVelAccl; // offset 0x8
			static long maxVelVel; // offset 0xc

		/* begin block 1.1 */
			// Start line: 1233
			// Start offset: 0x80016478
			// Variables:
				short _x0; // $v0
				short _y0; // $v1
				short _z0; // $a0
				short _x1; // $a1
				short _y1; // $a3
				short _z1; // $a2
				struct _SVector *_v; // $a1
				_Position *_v0; // $a0
				_Position *_v1; // $a2
		/* end block 1.1 */
		// End offset: 0x80016478
		// End Line: 1233
	/* end block 1 */
	// End offset: 0x80016570
	// End Line: 1265

	/* begin block 2 */
		// Start line: 2919
	/* end block 2 */
	// End Line: 2920

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetTarget(struct Camera *camera /*$s0*/, _Position *pos /*$s1*/)
void CAMERA_SetTarget(struct Camera *camera, _Position *pos)
{ // line 1267, offset 0x80016584
	/* begin block 1 */
		// Start line: 1268
		// Start offset: 0x80016584
		// Variables:
			struct _SVector sv; // stack offset -24

		/* begin block 1.1 */
			// Start line: 1268
			// Start offset: 0x80016584
			// Variables:
				short _x0; // $v0
				short _y0; // $v1
				short _z0; // $a1
				short _x1; // $a2
				short _y1; // $a3
				short _z1; // $t0
				struct _SVector *_v; // $a0
		/* end block 1.1 */
		// End offset: 0x80016584
		// End Line: 1268
	/* end block 1 */
	// End offset: 0x80016584
	// End Line: 1268

	/* begin block 2 */
		// Start line: 3007
	/* end block 2 */
	// End Line: 3008

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CalcPosition(_Position *position /*$s3*/, _Position *base /*$s2*/, struct _Rotation *rotation /*$s1*/, short distance /*$a3*/)
void CAMERA_CalcPosition(_Position *position, _Position *base, struct _Rotation *rotation, short distance)
{ // line 1278, offset 0x80016600
	/* begin block 1 */
		// Start line: 1279
		// Start offset: 0x80016600
		// Variables:
			SVECTOR sv; // stack offset -96
			//VECTOR v; // stack offset -88
			//MATRIX matrix; // stack offset -72
			struct _Vector vectorPos = {0}; // stack offset -40

		/* begin block 1.1 */
			// Start line: 1279
			// Start offset: 0x80016600
			// Variables:
				short _x1; // $v1
				short _y1; // $a0
				short _z1; // $v0
				struct _Vector *_v1; // $v0
		/* end block 1.1 */
		// End offset: 0x80016600
		// End Line: 1279
	/* end block 1 */
	// End offset: 0x80016600
	// End Line: 1279

	/* begin block 2 */
		// Start line: 3032
	/* end block 2 */
	// End Line: 3033

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetFocus(struct Camera *camera /*$s3*/, _Position *targetfocusPoint /*$s1*/)
void CAMERA_SetFocus(struct Camera *camera, _Position *targetfocusPoint)
{ // line 1319, offset 0x80016728
	///* begin block 1 */
	//	// Start line: 1320
	//	// Start offset: 0x80016728
	//	// Variables:
	//		struct _Instance *focusInstance; // $s0
	//		struct _Model *model; // $v0
	//		struct _SVector temp1; // stack offset -64
	//		struct _SVector offset; // stack offset -56
	//		struct _SVector *segPosVector; // $v1
	//		struct _Vector temp2; // stack offset -48

	//	/* begin block 1.1 */
	//		// Start line: 1335
	//		// Start offset: 0x80016774
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $a0
	//			short _z1; // $v1
	//			struct _SVector *_v0; // $s2
	//	/* end block 1.1 */
	//	// End offset: 0x80016774
	//	// End Line: 1335

	//	/* begin block 1.2 */
	//		// Start line: 1335
	//		// Start offset: 0x80016774
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $t1
	//			_Position *_v1; // $v0
	//	/* end block 1.2 */
	//	// End offset: 0x80016774
	//	// End Line: 1335

	//	/* begin block 1.3 */
	//		// Start line: 1345
	//		// Start offset: 0x800167F8

	//		/* begin block 1.3.1 */
	//			// Start line: 1347
	//			// Start offset: 0x800167F8
	//			// Variables:
	//				short _x0; // $v0
	//				short _y0; // $a2
	//				short _x1; // $a3
	//				short _y1; // $t0
	//				short _z1; // $v1
	//		/* end block 1.3.1 */
	//		// End offset: 0x800167F8
	//		// End Line: 1347
	//	/* end block 1.3 */
	//	// End offset: 0x80016848
	//	// End Line: 1355

	//	/* begin block 1.4 */
	//		// Start line: 1367
	//		// Start offset: 0x8001688C
	//		// Variables:
	//			struct _Instance *instance; // $v0
	//			struct _SVector output; // stack offset -32

	//		/* begin block 1.4.1 */
	//			// Start line: 1373
	//			// Start offset: 0x8001689C
	//			// Variables:
	//				short _x1; // $v0
	//				short _y1; // $v1
	//				short _z1; // $a0
	//		/* end block 1.4.1 */
	//		// End offset: 0x8001689C
	//		// End Line: 1373

	//		/* begin block 1.4.2 */
	//			// Start line: 1380
	//			// Start offset: 0x800168D4
	//			// Variables:
	//				short _x1; // $v1
	//				short _y1; // $a0
	//				short _z1; // $v0
	//				_Position *_v1; // $v0
	//		/* end block 1.4.2 */
	//		// End offset: 0x800168D4
	//		// End Line: 1380
	//	/* end block 1.4 */
	//	// End offset: 0x800168D4
	//	// End Line: 1380

	//	/* begin block 1.5 */
	//		// Start line: 1385
	//		// Start offset: 0x800168D4
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $v0
	//			_Position *_v1; // $v0
	//	/* end block 1.5 */
	//	// End offset: 0x800168F0
	//	// End Line: 1385

	//	/* begin block 1.6 */
	//		// Start line: 1388
	//		// Start offset: 0x800168F0
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $v0
	//			short _z0; // $v1
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $a1
	//	/* end block 1.6 */
	//	// End offset: 0x800168F0
	//	// End Line: 1388
	///* end block 1 */
	//// End offset: 0x80016984
	//// End Line: 1425

	///* begin block 2 */
	//	// Start line: 3127
	///* end block 2 */
	//// End Line: 3128

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Lock(struct Camera *camera /*$a0*/, long lock /*$a1*/)
void CAMERA_Lock(struct Camera *camera, long lock)
{ // line 1427, offset 0x800169a4
	camera->lock |= lock;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Unlock(struct Camera *camera /*$a0*/, long unlock /*$a1*/)
void CAMERA_Unlock(struct Camera *camera, long unlock)
{ // line 1432, offset 0x800169b8
	camera->lock &= ~unlock;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetSmoothValue(struct Camera *camera /*$a0*/, long smooth /*$a1*/)
void CAMERA_SetSmoothValue(struct Camera *camera, long smooth)
{ // line 1437, offset 0x800169cc
	/* begin block 1 */
		// Start line: 3394
	/* end block 1 */
	// End Line: 3395

	/* begin block 2 */
		// Start line: 3396
	/* end block 2 */
	// End Line: 3397

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetTimer(struct Camera *camera /*$a0*/, long time /*$a1*/)
void CAMERA_SetTimer(struct Camera *camera, long time)
{ // line 1450, offset 0x80016a1c
	/* begin block 1 */
		// Start line: 3420
	/* end block 1 */
	// End Line: 3421

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Adjust_tilt(struct Camera *camera /*$a0*/, long tilt /*$a1*/)
void CAMERA_Adjust_tilt(struct Camera *camera, long tilt)
{ // line 1456, offset 0x80016a3c
	/* begin block 1 */
		// Start line: 3432
	/* end block 1 */
	// End Line: 3433

	/* begin block 2 */
		// Start line: 3433
	/* end block 2 */
	// End Line: 3434

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Adjust_distance(struct Camera *camera /*$a0*/, long dist /*$a1*/)
void CAMERA_Adjust_distance(struct Camera *camera, long dist)
{ // line 1474, offset 0x80016a78
	/* begin block 1 */
		// Start line: 3471
	/* end block 1 */
	// End Line: 3472

	/* begin block 2 */
		// Start line: 3472
	/* end block 2 */
	// End Line: 3473

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Adjust_rotation(struct Camera *camera /*$s0*/, long rotation /*$s1*/)
void CAMERA_Adjust_rotation(struct Camera *camera, long rotation)
{ // line 1492, offset 0x80016af4
	/* begin block 1 */
		// Start line: 3509
	/* end block 1 */
	// End Line: 3510

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Adjust_roll(long roll_degrees /*$s0*/, int frames /*$s1*/)
void CAMERA_Adjust_roll(long roll_degrees, int frames)
{ // line 1511, offset 0x80016b78
	/* begin block 1 */
		// Start line: 3555
	/* end block 1 */
	// End Line: 3556

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Adjust(struct Camera *camera /*$s1*/, long adjust /*$s2*/)
void CAMERA_Adjust(struct Camera *camera, long adjust)
{ // line 1527, offset 0x80016bfc
	/* begin block 1 */
		// Start line: 1528
		// Start offset: 0x80016BFC

		/* begin block 1.1 */
			// Start line: 1532
			// Start offset: 0x80016C24

			/* begin block 1.1.1 */
				// Start line: 1535
				// Start offset: 0x80016C30
				// Variables:
					struct _SVector dv; // stack offset -24

				/* begin block 1.1.1.1 */
					// Start line: 1536
					// Start offset: 0x80016C30
					// Variables:
						short _x0; // $v0
						short _y0; // $v1
						short _z0; // $a1
						short _x1; // $a2
						short _y1; // $t0
						short _z1; // $a3
						struct _SVector *_v; // $a0
						struct _SVector *_v1; // $a3
				/* end block 1.1.1.1 */
				// End offset: 0x80016C30
				// End Line: 1536
			/* end block 1.1.1 */
			// End offset: 0x80016C74
			// End Line: 1551
		/* end block 1.1 */
		// End offset: 0x80016CA4
		// End Line: 1582
	/* end block 1 */
	// End offset: 0x80016CA4
	// End Line: 1587

	/* begin block 2 */
		// Start line: 3589
	/* end block 2 */
	// End Line: 3590

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_ChangeTo(struct Camera *camera /*$a0*/, struct _CameraKey *cameraKey /*$a1*/)
void CAMERA_ChangeTo(struct Camera *camera, struct _CameraKey *cameraKey)
{ // line 1590, offset 0x80016cbc
	/* begin block 1 */
		// Start line: 3715
	/* end block 1 */
	// End Line: 3716

	/* begin block 2 */
		// Start line: 3716
	/* end block 2 */
	// End Line: 3717

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetShake(struct Camera *camera /*$t0*/, long shake /*$a1*/, long scale /*$a2*/)
void CAMERA_SetShake(struct Camera *camera, long shake, long scale)
{ // line 1595, offset 0x80016cc4
	/* begin block 1 */
		// Start line: 1596
		// Start offset: 0x80016CC4
		// Variables:
			int shock; // $a0
			int duration; // $a1
	/* end block 1 */
	// End offset: 0x80016D5C
	// End Line: 1615

	/* begin block 2 */
		// Start line: 3725
	/* end block 2 */
	// End Line: 3726

}


// autogenerated function stub: 
// void /*$ra*/ Decouple_AngleMoveToward(short *current_ptr /*$a0*/, short destination /*$a1*/, short step /*$a3*/)
void Decouple_AngleMoveToward(short *current_ptr, short destination, short step)
{ // line 1618, offset 0x80016d74
	/* begin block 1 */
		// Start line: 3771
	/* end block 1 */
	// End Line: 3772

}

void CriticalDampValue(long dampMode, short *sourceVal, short targetVal, short *vel, short *accl, int smooth)
{
	short maxVel;
	short useVel;
	
	if (smooth != 0)
	{
		maxVel = smooth;

		if (smooth < 0)
		{
			maxVel = -4096 / smooth;
		}

		if (dampMode == 1)
		{
			if (dampMode == 5)
			{
				accl[0] = ((targetVal - sourceVal[0]) >> 1) - vel[0];

				useVel = vel[0] + accl[0];

				vel[0] = useVel;

				if (maxVel < useVel)
				{
					vel[0] = maxVel;

					if (gameTrackerX.timeMult != 4096)
					{
						useVel = (maxVel * gameTrackerX.timeMult) >> 12;
					}
				}
				else
				{
					if (useVel < -maxVel)
					{
						useVel = -maxVel;

						vel[0] = useVel;

						if (gameTrackerX.timeMult != 4096)
						{
							useVel = -(maxVel * gameTrackerX.timeMult) >> 12;
						}
					}
				}

				sourceVal[0] += useVel;
			}
			else if (dampMode == 6)
			{
				accl[0] = ((targetVal - sourceVal[0]) >> 3) - vel[0];

				useVel = vel[0] + accl[0];

				vel[0] = useVel;


				if (maxVel < useVel)
				{
					vel[0] = maxVel;

					if (gameTrackerX.timeMult != 4096)
					{
						useVel = (maxVel * gameTrackerX.timeMult) >> 12;
					}
				}
				else
				{
					if (useVel < -maxVel)
					{
						useVel = -maxVel;

						vel[0] = useVel;

						if (gameTrackerX.timeMult != 4096)
						{
							useVel = -(maxVel * gameTrackerX.timeMult) >> 12;
						}
					}
				}

				sourceVal[0] += useVel;
			}
			else
			{
				accl[0] = ((targetVal - sourceVal[0]) >> 2) - vel[0];

				useVel = vel[0] + accl[0];

				vel[0] = useVel;

				if (maxVel < useVel)
				{
					vel[0] = maxVel;

					if (gameTrackerX.timeMult != 4096)
					{
						useVel = (maxVel * gameTrackerX.timeMult) >> 12;
					}
				}
				else
				{
					if (useVel < -maxVel)
					{
						useVel = -maxVel;

						vel[0] = useVel;

						if (gameTrackerX.timeMult != 4096)
						{
							useVel = -(maxVel * gameTrackerX.timeMult) >> 12;
						}
					}
				}

				sourceVal[0] += useVel;
			}
		}
		else if (dampMode >= 2)
		{
			//loc_800171D4
			if (dampMode >= 7)
			{
				if (vel[0] == 0)
				{
					sourceVal[0] = targetVal;
				}
			}
			else if (dampMode >= 5)
			{
				if (dampMode == 5)
				{
					accl[0] = ((targetVal - sourceVal[0]) >> 1) - vel[0];
					
					useVel = vel[0] + accl[0];
					
					vel[0] = useVel;

					if (maxVel < useVel)
					{
						vel[0] = maxVel;

						if (gameTrackerX.timeMult != 4096)
						{
							useVel = (maxVel * gameTrackerX.timeMult) >> 12;
						}
					}
					else
					{
						if (useVel < -maxVel)
						{
							useVel = -maxVel;

							vel[0] = useVel;

							if (gameTrackerX.timeMult != 4096)
							{
								useVel = -(maxVel * gameTrackerX.timeMult) >> 12;
							}
						}
					}

					sourceVal[0] += useVel;
				}
				else if (dampMode == 6)
				{
					accl[0] = ((targetVal - sourceVal[0]) >> 3) - vel[0];
					
					useVel = vel[0] + accl[0];
					
					vel[0] = useVel;


					if (maxVel < useVel)
					{
						vel[0] = maxVel;

						if (gameTrackerX.timeMult != 4096)
						{
							useVel = (maxVel * gameTrackerX.timeMult) >> 12;
						}
					}
					else
					{
						if (useVel < -maxVel)
						{
							useVel = -maxVel;

							vel[0] = useVel;

							if (gameTrackerX.timeMult != 4096)
							{
								useVel = -(maxVel * gameTrackerX.timeMult) >> 12;
							}
						}
					}

					sourceVal[0] += useVel;
				}
				else
				{
					accl[0] = ((targetVal - sourceVal[0]) >> 2) - vel[0];
					
					useVel = vel[0] + accl[0];
					
					vel[0] = useVel;
					
					if (maxVel < useVel)
					{
						vel[0] = maxVel;

						if (gameTrackerX.timeMult != 4096)
						{
							useVel = (maxVel * gameTrackerX.timeMult) >> 12;
						}
					}
					else
					{
						if (useVel < -maxVel)
						{
							useVel = -maxVel;

							vel[0] = useVel;

							if (gameTrackerX.timeMult != 4096)
							{
								useVel = -(maxVel * gameTrackerX.timeMult) >> 12;
							}
						}
					}

					sourceVal[0] += useVel;
				}
			}
		}
		else if (dampMode == 0)
		{
			accl[0] = ((targetVal - sourceVal[0]) >> 2) - vel[0];
			
			vel[0] += accl[0];
			
			sourceVal[0] += vel[0];
		}

		if (vel[0] == 0)
		{
			sourceVal[0] = targetVal;
		}

	}
	else
	{
		sourceVal[0] = targetVal;
	}
}


// autogenerated function stub: 
// void /*$ra*/ CriticalDampPosition(long dampMode /*$a0*/, _Position *position /*$s1*/, _Position *targetPos /*$s3*/, struct _SVector *vel /*$s2*/, struct _SVector *accl /*stack 16*/, int smooth /*stack 20*/)
void CriticalDampPosition(long dampMode, _Position *position, _Position *targetPos, struct _SVector *vel, struct _SVector *accl, int smooth)
{ // line 1738, offset 0x80016f78
	///* begin block 1 */
	//	// Start line: 1739
	//	// Start offset: 0x80016F78
	//	// Variables:
	//		long length; // $s0
	//		struct _Vector vector; // stack offset -48
	//		struct _SVector svector; // stack offset -32
	//		short maxVel; // $s4
	//		int shift; // $a3

	//	/* begin block 1.1 */
	//		// Start line: 1760
	//		// Start offset: 0x80016FF4
	//		// Variables:
	//			long _x0; // $v0
	//			long _y0; // $a2
	//			long _z0; // $a1
	//			long _x1; // $v1
	//			long _y1; // $v1
	//			long _z1; // $a0
	//			struct _Vector *_v; // $v1
	//	/* end block 1.1 */
	//	// End offset: 0x80016FF4
	//	// End Line: 1760

	//	/* begin block 1.2 */
	//		// Start line: 1775
	//		// Start offset: 0x800170B0
	//		// Variables:
	//			long _x0; // $v0
	//			long _y0; // $a2
	//			long _z0; // $a1
	//			long _x1; // $v1
	//			long _y1; // $v1
	//			long _z1; // $a0
	//			struct _Vector *_v; // $v1
	//	/* end block 1.2 */
	//	// End offset: 0x800170B0
	//	// End Line: 1775

	//	/* begin block 1.3 */
	//		// Start line: 1809
	//		// Start offset: 0x80017254
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $v1
	//			short _z0; // $a1
	//			short _x1; // $a2
	//			short _y1; // $a3
	//			short _z1; // $t0
	//			struct _SVector *_v; // $s2
	//	/* end block 1.3 */
	//	// End offset: 0x80017254
	//	// End Line: 1809

	//	/* begin block 1.4 */
	//		// Start line: 1813
	//		// Start offset: 0x800172A8
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//	/* end block 1.4 */
	//	// End offset: 0x800172A8
	//	// End Line: 1813

	//	/* begin block 1.5 */
	//		// Start line: 1817
	//		// Start offset: 0x800172A8
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $v0
	//			short _z0; // $v1
	//			short _y1; // $a0
	//			short _z1; // $a1
	//	/* end block 1.5 */
	//	// End offset: 0x800172A8
	//	// End Line: 1817

	//	/* begin block 1.6 */
	//		// Start line: 1824
	//		// Start offset: 0x80017344
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $v1
	//			short _z0; // $a0
	//			short _x1; // $a1
	//			short _y1; // $a2
	//			short _z1; // $a3
	//			struct _SVector *_v; // $a1
	//	/* end block 1.6 */
	//	// End offset: 0x80017344
	//	// End Line: 1824

	//	/* begin block 1.7 */
	//		// Start line: 1838
	//		// Start offset: 0x800174D4
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//	/* end block 1.7 */
	//	// End offset: 0x800174D4
	//	// End Line: 1838

	//	/* begin block 1.8 */
	//		// Start line: 1869
	//		// Start offset: 0x80017604
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//	/* end block 1.8 */
	//	// End offset: 0x8001761C
	//	// End Line: 1869
	///* end block 1 */
	//// End offset: 0x8001761C
	//// End Line: 1871

	///* begin block 2 */
	//	// Start line: 4013
	///* end block 2 */
	//// End Line: 4014

}


// autogenerated function stub: 
// void /*$ra*/ CriticalDampAngle(long dampMode /*$a0*/, short *currentVal /*$s0*/, short target /*$t1*/, short *vel /*$a3*/, short *accl /*stack 16*/, int smooth /*stack 20*/)
void CriticalDampAngle(long dampMode, short *currentVal, short target, short *vel, short *accl, int smooth)
{ // line 1873, offset 0x8001763c
	/* begin block 1 */
		// Start line: 1874
		// Start offset: 0x8001763C
		// Variables:
			short current; // stack offset -16
	/* end block 1 */
	// End offset: 0x80017698
	// End Line: 1889

	/* begin block 2 */
		// Start line: 4301
	/* end block 2 */
	// End Line: 4302

}


// autogenerated function stub: 
// short /*$ra*/ CAMERA_CalcZRotation(_Position *target /*$a0*/, _Position *position /*$a1*/)
short CAMERA_CalcZRotation(_Position *target, _Position *position)
{ // line 1894, offset 0x800176dc
	/* begin block 1 */
		// Start line: 1895
		// Start offset: 0x800176DC
		// Variables:
			struct _SVector sv; // stack offset -24
			struct _SVector onPlane; // stack offset -16

		/* begin block 1.1 */
			// Start line: 1895
			// Start offset: 0x800176DC
			// Variables:
				short _x0; // $a2
				short _y0; // $v0
				short _z0; // $v1
				short _x1; // $a1
				short _y1; // $a3
				short _z1; // $t0
				struct _SVector *_v; // $a0
		/* end block 1.1 */
		// End offset: 0x800176DC
		// End Line: 1895
	/* end block 1 */
	// End offset: 0x800176DC
	// End Line: 1895

	/* begin block 2 */
		// Start line: 4353
	/* end block 2 */
	// End Line: 4354

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CalcRotation(struct _Rotation *rotation /*$s0*/, _Position *target /*$a1*/, _Position *position /*$a2*/)
void CAMERA_CalcRotation(struct _Rotation *rotation, _Position *target, _Position *position)
{ // line 1911, offset 0x80017754
	/* begin block 1 */
		// Start line: 1912
		// Start offset: 0x80017754
		// Variables:
			struct _SVector sv; // stack offset -24
			struct _SVector onPlane; // stack offset -16

		/* begin block 1.1 */
			// Start line: 1912
			// Start offset: 0x80017754
			// Variables:
				short _x0; // $a3
				short _y0; // $v0
				short _z0; // $v1
				short _x1; // $a0
				short _y1; // $a2
				short _z1; // $a1
				struct _SVector *_v; // $a0
		/* end block 1.1 */
		// End offset: 0x80017754
		// End Line: 1912
	/* end block 1 */
	// End offset: 0x80017754
	// End Line: 1912

	/* begin block 2 */
		// Start line: 4392
	/* end block 2 */
	// End Line: 4393

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CalcFSRotation(struct Camera *camera /*$a0*/, struct _Rotation *rotation /*$s0*/, _Position *target /*$a2*/, _Position *position /*$a3*/)
void CAMERA_CalcFSRotation(struct Camera *camera, struct _Rotation *rotation, _Position *target, _Position *position)
{ // line 1928, offset 0x800177f0
	/* begin block 1 */
		// Start line: 1929
		// Start offset: 0x800177F0
		// Variables:
			struct _SVector sv; // stack offset -32
			struct _SVector onPlane; // stack offset -24
			struct _SVector sv2; // stack offset -16

		/* begin block 1.1 */
			// Start line: 1929
			// Start offset: 0x800177F0
			// Variables:
				short _x0; // $a1
				short _y0; // $v1
				short _z0; // $a0
				short _x1; // $v0
				short _y1; // $a3
				short _z1; // $a2
				struct _SVector *_v; // $v0
		/* end block 1.1 */
		// End offset: 0x800177F0
		// End Line: 1929

		/* begin block 1.2 */
			// Start line: 1929
			// Start offset: 0x800177F0
			// Variables:
				struct _SVector *_v0; // $v0
		/* end block 1.2 */
		// End offset: 0x800177F0
		// End Line: 1929
	/* end block 1 */
	// End offset: 0x800177F0
	// End Line: 1929

	/* begin block 2 */
		// Start line: 4430
	/* end block 2 */
	// End Line: 4431

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Relocate(struct Camera *camera /*$a0*/, struct _SVector *offset /*$a1*/, int streamSignalFlag /*$a2*/)
void CAMERA_Relocate(struct Camera *camera, struct _SVector *offset, int streamSignalFlag)
{ // line 1948, offset 0x8001789c
	/* begin block 1 */
		// Start line: 4474
	/* end block 1 */
	// End Line: 4475

	/* begin block 2 */
		// Start line: 4479
	/* end block 2 */
	// End Line: 4480

}


// autogenerated function stub: 
// struct _TFace * /*$ra*/ CAMERA_SphereToSphereWithLines(struct Camera *camera /*$s6*/, struct CameraCollisionInfo *colInfo /*stack 4*/, int secondcheck_flag /*stack 8*/)
struct _TFace * CAMERA_SphereToSphereWithLines(struct Camera *camera, struct CameraCollisionInfo *colInfo, int secondcheck_flag)
{ // line 2017, offset 0x800179e8
	///* begin block 1 */
	//	// Start line: 2018
	//	// Start offset: 0x800179E8
	//	// Variables:
	//		long minLength; // stack offset -68
	//		struct _SVector sv; // stack offset -344
	//		struct _SVector startPt[5]; // stack offset -336
	//		struct _SVector endPt[5]; // stack offset -296
	//		struct _SVector startLine; // stack offset -256
	//		struct _Vector adjStartLine; // stack offset -248
	//		struct _SVector endLine; // stack offset -232
	//		struct _Vector adjEndLine; // stack offset -224
	//		struct _Vector CamLineNormalized; // stack offset -208
	//		struct _Rotation rotation; // stack offset -192
	//		MATRIX matrix; // stack offset -184
	//		struct _TFace *result; // stack offset -64
	//		long i; // stack offset -60
	//		long init; // stack offset -56
	//		struct Level *level; // stack offset -52
	//		struct _Instance *focusInstance; // $v0
	//		struct _Vector ACE_vect; // stack offset -152
	//		struct _LCollideInfo lcol; // stack offset -136
	//		int ACE_force; // $s2
	//		int in_warpRoom; // stack offset -48

	//	/* begin block 1.1 */
	//		// Start line: 2133
	//		// Start offset: 0x80017CF4
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a0
	//			short _z0; // $v0
	//			short _x1; // $a1
	//			short _y1; // $a2
	//			short _z1; // $a3
	//			struct _SVector *_v; // $v1
	//			_Position *_v0; // $v0
	//	/* end block 1.1 */
	//	// End offset: 0x80017CF4
	//	// End Line: 2133

	//	/* begin block 1.2 */
	//		// Start line: 2133
	//		// Start offset: 0x80017CF4
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a0
	//			short _z0; // $v0
	//			short _x1; // $a1
	//			short _y1; // $a2
	//			short _z1; // $a3
	//			struct _SVector *_v; // $v1
	//			_Position *_v0; // $v0
	//	/* end block 1.2 */
	//	// End offset: 0x80017CF4
	//	// End Line: 2133

	//	/* begin block 1.3 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a0
	//			short _z0; // $v0
	//			short _x1; // $a1
	//			short _y1; // $a2
	//			short _z1; // $a3
	//			struct _SVector *_v; // $s3
	//			_Position *_v0; // $v0
	//	/* end block 1.3 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.4 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a1
	//			short _z0; // $v0
	//			short _x1; // $a2
	//			short _y1; // $a3
	//			short _z1; // $t0
	//			struct _SVector *_v; // $v1
	//			_Position *_v0; // $v0
	//	/* end block 1.4 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.5 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a1
	//			short _z0; // $a2
	//			short _x1; // $a3
	//			short _y1; // $t0
	//			short _z1; // $t1
	//			struct _SVector *_v; // $v0
	//			_Position *_v1; // $v0
	//	/* end block 1.5 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.6 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a1
	//			short _z0; // $a2
	//			short _x1; // $a3
	//			short _y1; // $t0
	//			short _z1; // $t1
	//			struct _SVector *_v; // $v0
	//			_Position *_v1; // $v0
	//	/* end block 1.6 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.7 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a2
	//			short _z0; // $v0
	//			short _x1; // $a3
	//			short _y1; // $t0
	//			short _z1; // $t1
	//			struct _SVector *_v; // $v1
	//			_Position *_v0; // $v0
	//	/* end block 1.7 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.8 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v1
	//			short _y0; // $a3
	//			short _z0; // $v0
	//			short _x1; // $t0
	//			short _y1; // $t1
	//			short _z1; // $t2
	//			struct _SVector *_v; // $v1
	//			_Position *_v0; // $v0
	//	/* end block 1.8 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.9 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $v1
	//			short _z0; // $a3
	//			short _x1; // $t0
	//			short _y1; // $t2
	//			short _z1; // $t3
	//			struct _SVector *_v; // $v0
	//			struct _SVector *_v0; // $a3
	//			struct _SVector *_v1; // $t1
	//	/* end block 1.9 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.10 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $v1
	//			short _z0; // $a3
	//			short _x1; // $t0
	//			short _y1; // $t2
	//			short _z1; // $t1
	//			struct _SVector *_v; // $v0
	//	/* end block 1.10 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.11 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $v0
	//			_Position *_v1; // $v0
	//	/* end block 1.11 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.12 */
	//		// Start line: 2146
	//		// Start offset: 0x80017E00
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $a2
	//			_Position *_v1; // $v0
	//	/* end block 1.12 */
	//	// End offset: 0x80017E00
	//	// End Line: 2146

	//	/* begin block 1.13 */
	//		// Start line: 2232
	//		// Start offset: 0x80018148
	//		// Variables:
	//			int clut; // $fp
	//			short backface_flag; // stack offset -72
	//			struct _PCollideInfo pCollideInfo; // stack offset -120

	//		/* begin block 1.13.1 */
	//			// Start line: 2257
	//			// Start offset: 0x800181A8
	//			// Variables:
	//				int n; // $s2

	//			/* begin block 1.13.1.1 */
	//				// Start line: 2262
	//				// Start offset: 0x800181B4
	//				// Variables:
	//					struct Level *thislevel; // $s1
	//			/* end block 1.13.1.1 */
	//			// End offset: 0x8001823C
	//			// End Line: 2279
	//		/* end block 1.13.1 */
	//		// End offset: 0x8001824C
	//		// End Line: 2280

	//		/* begin block 1.13.2 */
	//			// Start line: 2305
	//			// Start offset: 0x8001828C
	//			// Variables:
	//				short _x0; // $v0
	//				short _y0; // $v1
	//				short _z0; // $a0
	//				short _x1; // $a1
	//				short _y1; // $a2
	//				short _z1; // $a3
	//				struct _SVector *_v; // stack offset -44
	//		/* end block 1.13.2 */
	//		// End offset: 0x8001828C
	//		// End Line: 2305

	//		/* begin block 1.13.3 */
	//			// Start line: 2336
	//			// Start offset: 0x800183E0
	//			// Variables:
	//				short _x0; // $v0
	//				short _y0; // $v1
	//				short _z0; // $a0
	//				short _x1; // $a1
	//				short _y1; // $a2
	//				short _z1; // $a3
	//		/* end block 1.13.3 */
	//		// End offset: 0x800183E0
	//		// End Line: 2336
	//	/* end block 1.13 */
	//	// End offset: 0x80018460
	//	// End Line: 2361
	///* end block 1 */
	//// End offset: 0x800184F4
	//// End Line: 2380

	///* begin block 2 */
	//	// Start line: 4612
	///* end block 2 */
	//// End Line: 4613

	return null;
}


// autogenerated function stub: 
// long /*$ra*/ CAMERA_CalcTilt(struct _Normal *normal /*$s1*/, short zRot /*$a1*/)
long CAMERA_CalcTilt(struct _Normal *normal, short zRot)
{ // line 2382, offset 0x80018524
	/* begin block 1 */
		// Start line: 2383
		// Start offset: 0x80018524
		// Variables:
			//MATRIX matrix; // stack offset -64
			//VECTOR newNormal; // stack offset -32
	/* end block 1 */
	// End offset: 0x80018524
	// End Line: 2383

	/* begin block 2 */
		// Start line: 5838
	/* end block 2 */
	// End Line: 5839

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetLookFocusAndBase(struct _Instance *focusInstance /*$a0*/, _Position *focusPoint /*$a1*/)
void CAMERA_SetLookFocusAndBase(struct _Instance *focusInstance, _Position *focusPoint)
{ // line 2399, offset 0x80018598
	/* begin block 1 */
		// Start line: 2400
		// Start offset: 0x80018598
		// Variables:
			_Position lookFocus; // stack offset -8
	/* end block 1 */
	// End offset: 0x80018598
	// End Line: 2400

	/* begin block 2 */
		// Start line: 5873
	/* end block 2 */
	// End Line: 5874

	/* begin block 3 */
		// Start line: 5878
	/* end block 3 */
	// End Line: 5879

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetLookFocusAndDistance(struct Camera *camera /*$a0*/, VECTOR *focuspoint /*$a1*/, int distance /*$a2*/)
void CAMERA_SetLookFocusAndDistance(struct Camera *camera, VECTOR *focuspoint, int distance)
{ // line 2412, offset 0x800185e0
	/* begin block 1 */
		// Start line: 5904
	/* end block 1 */
	// End Line: 5905

	/* begin block 2 */
		// Start line: 5905
	/* end block 2 */
	// End Line: 5906

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_LookProcess(struct Camera *camera /*$s2*/)
void CAMERA_LookProcess(struct Camera *camera)
{ // line 2420, offset 0x80018608
	///* begin block 1 */
	//	// Start line: 2421
	//	// Start offset: 0x80018608
	//	// Variables:
	//		struct _Instance *focusInstance; // $s1
	//		int smooth; // $t0
	//		int distance; // $a3
	//		long dampMode; // $a0

	//	/* begin block 1.1 */
	//		// Start line: 2466
	//		// Start offset: 0x800186F8
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $a1
	//			_Position *_v0; // $v0
	//			_Position *_v1; // $v0
	//	/* end block 1.1 */
	//	// End offset: 0x800186F8
	//	// End Line: 2466

	//	/* begin block 1.2 */
	//		// Start line: 2487
	//		// Start offset: 0x80018760
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//	/* end block 1.2 */
	//	// End offset: 0x80018760
	//	// End Line: 2487

	//	/* begin block 1.3 */
	//		// Start line: 2487
	//		// Start offset: 0x80018760
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a1
	//			struct _Rotation *_v0; // $v0
	//	/* end block 1.3 */
	//	// End offset: 0x80018760
	//	// End Line: 2487

	//	/* begin block 1.4 */
	//		// Start line: 2487
	//		// Start offset: 0x80018760
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			struct _Rotation *_v0; // $v0
	//	/* end block 1.4 */
	//	// End offset: 0x80018760
	//	// End Line: 2487
	///* end block 1 */
	//// End offset: 0x80018760
	//// End Line: 2493

	///* begin block 2 */
	//	// Start line: 5917
	///* end block 2 */
	//// End Line: 5918

	///* begin block 3 */
	//	// Start line: 5921
	///* end block 3 */
	//// End Line: 5922

}

void CAMERA_Normalize(struct _SVector *svector)
{
	long len;

	len = CAMERA_LengthSVector(svector);

	if (len != 0)
	{
		svector->x = (svector->x << 12) / len;
		svector->y = (svector->y << 12) / len;
		svector->z = (svector->z << 12) / len;
	}
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_HandleTransitions(struct Camera *camera /*$s0*/)
void CAMERA_HandleTransitions(struct Camera *camera)
{ // line 2557, offset 0x800188d4
	/* begin block 1 */
		// Start line: 2558
		// Start offset: 0x800188D4
	/* end block 1 */
	// End offset: 0x80018A78
	// End Line: 2669

	/* begin block 2 */
		// Start line: 6240
	/* end block 2 */
	// End Line: 6241

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CalcFocusOffset(struct _SVector *offset /*$a2*/, struct Camera *camera /*$a1*/)
void CAMERA_CalcFocusOffset(struct _SVector *offset, struct Camera *camera)
{ // line 2673, offset 0x80018a88
	/* begin block 1 */
		// Start line: 2674
		// Start offset: 0x80018A88
		// Variables:
			struct _Vector adjustedOffset; // stack offset -24
			struct _SVector temp; // stack offset -8
			struct _Instance *focusInstance; // $a0

		/* begin block 1.1 */
			// Start line: 2698
			// Start offset: 0x80018AC8
			// Variables:
				short _x1; // $v0
				short _y1; // $v1
				short _z1; // $a0
		/* end block 1.1 */
		// End offset: 0x80018AC8
		// End Line: 2698
	/* end block 1 */
	// End offset: 0x80018AC8
	// End Line: 2698

	/* begin block 2 */
		// Start line: 6474
	/* end block 2 */
	// End Line: 6475

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CalcFocusOffsetForSwim(struct _SVector *offset /*$s0*/, struct Camera *camera /*$a1*/)
void CAMERA_CalcFocusOffsetForSwim(struct _SVector *offset, struct Camera *camera)
{ // line 2703, offset 0x80018b3c
	/* begin block 1 */
		// Start line: 2704
		// Start offset: 0x80018B3C
		// Variables:
			struct _Vector adjustedOffset; // stack offset -32
			struct _SVector temp; // stack offset -16
			struct _Instance *focusInstance; // $v1

		/* begin block 1.1 */
			// Start line: 2704
			// Start offset: 0x80018B3C
			// Variables:
				short _x1; // $v1
				short _y1; // $a0
				short _z1; // $v0
				struct _Vector *_v1; // $v0
		/* end block 1.1 */
		// End offset: 0x80018B3C
		// End Line: 2704
	/* end block 1 */
	// End offset: 0x80018B3C
	// End Line: 2704

	/* begin block 2 */
		// Start line: 6542
	/* end block 2 */
	// End Line: 6543

}


// autogenerated function stub: 
// short /*$ra*/ CAMERA_CalcIntersectAngle(struct _SVector *linept /*$s0*/, struct _SVector *vertex0 /*$a1*/, struct _SVector *vertex1 /*$a2*/, short *high /*$s2*/, short *low /*stack 16*/)
short CAMERA_CalcIntersectAngle(struct _SVector *linept, struct _SVector *vertex0, struct _SVector *vertex1, short *high, short *low)
{ // line 2727, offset 0x80018ba8
	/* begin block 1 */
		// Start line: 2728
		// Start offset: 0x80018BA8
		// Variables:
			struct _SVector point; // stack offset -24
			short zrot; // $a0
			long camera_plane_d; // $v0
	/* end block 1 */
	// End offset: 0x80018C80
	// End Line: 2747

	/* begin block 2 */
		// Start line: 6608
	/* end block 2 */
	// End Line: 6609

	/* begin block 3 */
		// Start line: 6613
	/* end block 3 */
	// End Line: 6614

	return 0;
}


// autogenerated function stub: 
// short /*$ra*/ CAMERA_GetLineAngle(struct Camera *camera /*$a0*/, struct CameraCollisionInfo *colInfo /*$a1*/, struct _SVector *linept /*$a2*/, int line /*$s5*/)
short CAMERA_GetLineAngle(struct Camera *camera, struct CameraCollisionInfo *colInfo, struct _SVector *linept, int line)
{ // line 2749, offset 0x80018c98
	/* begin block 1 */
		// Start line: 2750
		// Start offset: 0x80018C98
		// Variables:
			struct _Terrain *terrain; // $t1
			struct _SVector *vertex0; // $s1
			struct _SVector *vertex1; // $s0
			struct _SVector *vertex2; // $s3
			struct _SVector new_linept; // stack offset -48
			short high; // stack offset -40
			short low; // stack offset -38
	/* end block 1 */
	// End offset: 0x80018E3C
	// End Line: 2779

	/* begin block 2 */
		// Start line: 6675
	/* end block 2 */
	// End Line: 6676

	return 0;
}


// autogenerated function stub: 
// long /*$ra*/ CAMERA_ACForcedMovement(struct Camera *camera /*$s1*/, struct CameraCollisionInfo *colInfo /*$s0*/)
long CAMERA_ACForcedMovement(struct Camera *camera, struct CameraCollisionInfo *colInfo)
{ // line 2793, offset 0x80018e60
	/* begin block 1 */
		// Start line: 2794
		// Start offset: 0x80018E60
		// Variables:
			long dp; // $v0
			struct _Normal normal; // stack offset -32
			struct _SVector sv; // stack offset -24

		/* begin block 1.1 */
			// Start line: 2794
			// Start offset: 0x80018E60
			// Variables:
				short _x0; // $a1
				short _y0; // $a2
				short _z0; // $v0
				short _x1; // $a3
				short _y1; // $t0
				short _z1; // $v1
				struct _SVector *_v; // $a0
				_Position *_v0; // $v0
				_Position *_v1; // $v1
		/* end block 1.1 */
		// End offset: 0x80018E60
		// End Line: 2794
	/* end block 1 */
	// End offset: 0x80018F18
	// End Line: 2832

	/* begin block 2 */
		// Start line: 6883
	/* end block 2 */
	// End Line: 6884

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_update_dist_debounced(struct Camera *camera /*$a0*/, short dist /*$a2*/)
void CAMERA_update_dist_debounced(struct Camera *camera, short dist)
{ // line 2835, offset 0x80018f30
	/* begin block 1 */
		// Start line: 6974
	/* end block 1 */
	// End Line: 6975

	/* begin block 2 */
		// Start line: 6975
	/* end block 2 */
	// End Line: 6976

}


// autogenerated function stub: 
// short /*$ra*/ CAMERA_dampgetline(short angle /*$a0*/)
short CAMERA_dampgetline(short angle)
{ // line 2847, offset 0x80018fa0
	/* begin block 1 */
		// Start line: 2848
		// Start offset: 0x80018FA0
		// Variables:
			static short target_angle; // offset 0x50
			static short angle_vel; // offset 0x52
			static short angle_accl; // offset 0x54
	/* end block 1 */
	// End offset: 0x80019038
	// End Line: 2865

	/* begin block 2 */
		// Start line: 6999
	/* end block 2 */
	// End Line: 7000

	return 0;
}


// autogenerated function stub: 
// long /*$ra*/ CAMERA_ACNoForcedMovement(struct Camera *camera /*$s0*/, struct CameraCollisionInfo *colInfo /*$s1*/)
long CAMERA_ACNoForcedMovement(struct Camera *camera, struct CameraCollisionInfo *colInfo)
{ // line 2873, offset 0x8001904c
	/* begin block 1 */
		// Start line: 2874
		// Start offset: 0x8001904C
		// Variables:
			long hit; // $s2
			short playerSamePos; // $s3
			short angle; // $a0

		/* begin block 1.1 */
			// Start line: 2900
			// Start offset: 0x800190C4
			// Variables:
				int n; // $a0
				int flag; // $t1
				short dist; // $a1
		/* end block 1.1 */
		// End offset: 0x80019278
		// End Line: 2956
	/* end block 1 */
	// End offset: 0x80019534
	// End Line: 3124

	/* begin block 2 */
		// Start line: 7059
	/* end block 2 */
	// End Line: 7060

	return 0;
}


// autogenerated function stub: 
// long /*$ra*/ CAMERA_AbsoluteCollision(struct Camera *camera /*$a0*/, struct CameraCollisionInfo *colInfo /*$a1*/)
long CAMERA_AbsoluteCollision(struct Camera *camera, struct CameraCollisionInfo *colInfo)
{ // line 3130, offset 0x80019550
	/* begin block 1 */
		// Start line: 3131
		// Start offset: 0x80019550
		// Variables:
			long hit; // $a3
	/* end block 1 */
	// End offset: 0x80019668
	// End Line: 3200

	/* begin block 2 */
		// Start line: 7592
	/* end block 2 */
	// End Line: 7593

	return 0;
}


// autogenerated function stub: 
// short /*$ra*/ CAMERA_update_z_damped(struct Camera *camera /*$a0*/, short current /*$a3*/, short target /*$t0*/)
short CAMERA_update_z_damped(struct Camera *camera, short current, short target)
{ // line 3205, offset 0x80019678
	/* begin block 1 */
		// Start line: 3206
		// Start offset: 0x80019678
		// Variables:
			static short upvel; // offset 0x56
			static short upaccl; // offset 0x58
			static short upmaxVel; // offset 0x5a
			short current_tmp; // stack offset -16
	/* end block 1 */
	// End offset: 0x800198D8
	// End Line: 3250

	/* begin block 2 */
		// Start line: 7752
	/* end block 2 */
	// End Line: 7753

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CombatCamDist(struct Camera *camera /*$s0*/)
void CAMERA_CombatCamDist(struct Camera *camera)
{ // line 3310, offset 0x800198e8
	/* begin block 1 */
		// Start line: 3311
		// Start offset: 0x800198E8
		// Variables:
			DVECTOR xy; // stack offset -48
			DVECTOR xy2; // stack offset -40
			struct _SVector position; // stack offset -32
			long z; // stack offset -24
			struct _Instance *instance; // $s1
	/* end block 1 */
	// End offset: 0x80019B98
	// End Line: 3392

	/* begin block 2 */
		// Start line: 7966
	/* end block 2 */
	// End Line: 7967

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_GenericCameraProcess(struct Camera *camera /*$s0*/)
void CAMERA_GenericCameraProcess(struct Camera *camera)
{ // line 3395, offset 0x80019bac
	/* begin block 1 */
		// Start line: 3396
		// Start offset: 0x80019BAC
		// Variables:
			struct _Instance *focusInstance; // $s1
			_Position targetCamPos; // stack offset -32

		/* begin block 1.1 */
			// Start line: 3449
			// Start offset: 0x80019CD0
			// Variables:
				short angle; // $a0
				struct _Rotation test_rot; // stack offset -24
		/* end block 1.1 */
		// End offset: 0x80019D30
		// End Line: 3467

		/* begin block 1.2 */
			// Start line: 3475
			// Start offset: 0x80019D40
			// Variables:
				struct _Instance *warpInstance; // $v0
				int tmp; // $v0
		/* end block 1.2 */
		// End offset: 0x80019D50
		// End Line: 3481

		/* begin block 1.3 */
			// Start line: 3513
			// Start offset: 0x80019E00
			// Variables:
				int mod; // $v1
		/* end block 1.3 */
		// End offset: 0x80019E80
		// End Line: 3528

		/* begin block 1.4 */
			// Start line: 3536
			// Start offset: 0x80019E9C
			// Variables:
				int dist; // $a3
		/* end block 1.4 */
		// End offset: 0x80019EF0
		// End Line: 3554

		/* begin block 1.5 */
			// Start line: 3568
			// Start offset: 0x80019F30
			// Variables:
				short _x1; // $v1
				short _y1; // $a0
				short _z1; // $a1
				_Position *_v0; // $v0
				_Position *_v1; // $v0
		/* end block 1.5 */
		// End offset: 0x80019F30
		// End Line: 3568

		/* begin block 1.6 */
			// Start line: 3577
			// Start offset: 0x80019F74
			// Variables:
				_Position target; // stack offset -24
		/* end block 1.6 */
		// End offset: 0x80019FF4
		// End Line: 3597
	/* end block 1 */
	// End offset: 0x80019FF4
	// End Line: 3600

	/* begin block 2 */
		// Start line: 8137
	/* end block 2 */
	// End Line: 8138

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CinematicProcess(struct Camera *camera /*$s2*/)
void CAMERA_CinematicProcess(struct Camera *camera)
{ // line 3608, offset 0x8001a028
	///* begin block 1 */
	//	// Start line: 3609
	//	// Start offset: 0x8001A028
	//	// Variables:
	//		struct _SVector *camPos; // $s0
	//		struct _SVector *camTarget; // $s3
	//		struct MultiSpline *posSpline; // $s4
	//		struct MultiSpline *targetSpline; // $s1

	//	/* begin block 1.1 */
	//		// Start line: 3632
	//		// Start offset: 0x8001A0A0
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//	/* end block 1.1 */
	//	// End offset: 0x8001A0A0
	//	// End Line: 3632

	//	/* begin block 1.2 */
	//		// Start line: 3636
	//		// Start offset: 0x8001A0BC
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $v0
	//			struct _SVector *_v1; // $v0
	//	/* end block 1.2 */
	//	// End offset: 0x8001A0D4
	//	// End Line: 3636

	//	/* begin block 1.3 */
	//		// Start line: 3641
	//		// Start offset: 0x8001A0E4
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//			struct _SVector *_v0; // $v0
	//	/* end block 1.3 */
	//	// End offset: 0x8001A0E4
	//	// End Line: 3641

	//	/* begin block 1.4 */
	//		// Start line: 3649
	//		// Start offset: 0x8001A12C
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a2
	//			_Position *_v0; // $v0
	//	/* end block 1.4 */
	//	// End offset: 0x8001A12C
	//	// End Line: 3649

	//	/* begin block 1.5 */
	//		// Start line: 3662
	//		// Start offset: 0x8001A18C
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//			_Position *_v0; // $v0
	//	/* end block 1.5 */
	//	// End offset: 0x8001A18C
	//	// End Line: 3662

	//	/* begin block 1.6 */
	//		// Start line: 3710
	//		// Start offset: 0x8001A3E0
	//	/* end block 1.6 */
	//	// End offset: 0x8001A4DC
	//	// End Line: 3727

	//	/* begin block 1.7 */
	//		// Start line: 3730
	//		// Start offset: 0x8001A4DC
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//			struct _Rotation *_v0; // $v0
	//	/* end block 1.7 */
	//	// End offset: 0x8001A4DC
	//	// End Line: 3730
	///* end block 1 */
	//// End offset: 0x8001A4DC
	//// End Line: 3730

	///* begin block 2 */
	//	// Start line: 8584
	///* end block 2 */
	//// End Line: 8585

}


// autogenerated function stub: 
// int /*$ra*/ CAMERA_GetDistSq(struct _SVector *point1 /*$a0*/, struct _SVector *point2 /*$a1*/)
int CAMERA_GetDistSq(struct _SVector *point1, struct _SVector *point2)
{ // line 3744, offset 0x8001a544
	/* begin block 1 */
		// Start line: 3745
		// Start offset: 0x8001A544
		// Variables:
			struct _Vector d; // stack offset -16
	/* end block 1 */
	// End offset: 0x8001A544
	// End Line: 3745

	/* begin block 2 */
		// Start line: 8869
	/* end block 2 */
	// End Line: 8870

	/* begin block 3 */
		// Start line: 8873
	/* end block 3 */
	// End Line: 8874

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_NearestPointOnLineVec(struct _SVector *linePoint /*$s2*/, struct _SVector *start /*$s1*/, struct _SVector *line /*$s0*/, _Position *point /*$a3*/)
void CAMERA_NearestPointOnLineVec(struct _SVector *linePoint, struct _SVector *start, struct _SVector *line, _Position *point)
{ // line 3759, offset 0x8001a5c0
	/* begin block 1 */
		// Start line: 3760
		// Start offset: 0x8001A5C0
		// Variables:
			//MATRIX nmat; // stack offset -64
			struct _Vector dpv; // stack offset -32
			long t; // $a0
	/* end block 1 */
	// End offset: 0x8001A674
	// End Line: 3778

	/* begin block 2 */
		// Start line: 8903
	/* end block 2 */
	// End Line: 8904

}


// autogenerated function stub: 
// int /*$ra*/ CAMERA_CheckPoint(int linePoint /*$a0*/, int linept1 /*$a1*/, int linept2 /*$a2*/)
int CAMERA_CheckPoint(int linePoint, int linept1, int linept2)
{ // line 3784, offset 0x8001a6ec
	/* begin block 1 */
		// Start line: 8966
	/* end block 1 */
	// End Line: 8967

	/* begin block 2 */
		// Start line: 8967
	/* end block 2 */
	// End Line: 8968

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ CAMERA_CheckIfPointOnLine(struct _SVector *linePoint /*$s0*/, struct _SVector *linept1 /*$s1*/, struct _SVector *linept2 /*$s2*/)
int CAMERA_CheckIfPointOnLine(struct _SVector *linePoint, struct _SVector *linept1, struct _SVector *linept2)
{ // line 3790, offset 0x8001a730
	/* begin block 1 */
		// Start line: 8978
	/* end block 1 */
	// End Line: 8979

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ CAMERA_FindLinePoint(_Position *point /*$s0*/, struct _SVector *linept1 /*$s5*/, struct _SVector *linept2 /*$s6*/, int target_dist_sq /*$s1*/, struct _SVector *results /*stack 16*/)
int CAMERA_FindLinePoint(_Position *point, struct _SVector *linept1, struct _SVector *linept2, int target_dist_sq, struct _SVector *results)
{ // line 3798, offset 0x8001a7c0
	///* begin block 1 */
	//	// Start line: 3799
	//	// Start offset: 0x8001A7C0
	//	// Variables:
	//		struct _SVector outPoint; // stack offset -56
	//		struct _SVector line; // stack offset -48
	//		int calc; // $s1
	//		int hits; // $s4

	//	/* begin block 1.1 */
	//		// Start line: 3799
	//		// Start offset: 0x8001A7C0
	//		// Variables:
	//			short _x0; // $v0
	//			short _y0; // $v1
	//			short _z0; // $a3
	//			short _x1; // $t0
	//			short _y1; // $t1
	//			short _z1; // $t2
	//			struct _SVector *_v; // $s2
	//	/* end block 1.1 */
	//	// End offset: 0x8001A7C0
	//	// End Line: 3799

	//	/* begin block 1.2 */
	//		// Start line: 3813
	//		// Start offset: 0x8001A854
	//		// Variables:
	//			struct _SVector linePoint; // stack offset -40
	//			int n; // $s3

	//		/* begin block 1.2.1 */
	//			// Start line: 3827
	//			// Start offset: 0x8001A908
	//			// Variables:
	//				short _x1; // $v0
	//				short _y1; // $v1
	//				short _z1; // $a0
	//		/* end block 1.2.1 */
	//		// End offset: 0x8001A908
	//		// End Line: 3827
	//	/* end block 1.2 */
	//	// End offset: 0x8001A95C
	//	// End Line: 3833
	///* end block 1 */
	//// End offset: 0x8001A95C
	//// End Line: 3835

	///* begin block 2 */
	//	// Start line: 8994
	///* end block 2 */
	//// End Line: 8995

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SplineGetNearestPoint2(struct Camera *camera /*stack 0*/, struct Spline *spline /*stack 4*/, struct _SVector *point /*stack 8*/, int *currkey /*stack 12*/, struct _SVector *ret_dpoint /*stack 16*/)
void CAMERA_SplineGetNearestPoint2(struct Camera *camera, struct Spline *spline, struct _SVector *point, int *currkey, struct _SVector *ret_dpoint)
{ // line 3838, offset 0x8001a984
	///* begin block 1 */
	//	// Start line: 3839
	//	// Start offset: 0x8001A984
	//	// Variables:
	//		struct SplineKey *key; // stack offset -56
	//		int n; // $s2
	//		int target_dist_sq; // stack offset -52
	//		long dist; // $fp

	//	/* begin block 1.1 */
	//		// Start line: 3839
	//		// Start offset: 0x8001A984
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//	/* end block 1.1 */
	//	// End offset: 0x8001A984
	//	// End Line: 3839

	//	/* begin block 1.2 */
	//		// Start line: 3858
	//		// Start offset: 0x8001AA38
	//		// Variables:
	//			struct _SVector point1; // stack offset -88
	//			struct _SVector point2; // stack offset -80
	//			struct _SVector results[2]; // stack offset -72
	//			int i; // $s1
	//			int hits; // $s3

	//		/* begin block 1.2.1 */
	//			// Start line: 3862
	//			// Start offset: 0x8001AA54
	//			// Variables:
	//				short _x1; // $v1
	//				short _y1; // $a2
	//				short _z1; // $v0
	//				struct _SVector *_v0; // $s7
	//				struct vecS *_v1; // $v0
	//		/* end block 1.2.1 */
	//		// End offset: 0x8001AA54
	//		// End Line: 3862

	//		/* begin block 1.2.2 */
	//			// Start line: 3862
	//			// Start offset: 0x8001AA54
	//			// Variables:
	//				short _x1; // $v0
	//				short _y1; // $a2
	//				short _z1; // $v1
	//				struct _SVector *_v0; // $s6
	//				struct vecS *_v1; // $v1
	//		/* end block 1.2.2 */
	//		// End offset: 0x8001AA54
	//		// End Line: 3862

	//		/* begin block 1.2.3 */
	//			// Start line: 3869
	//			// Start offset: 0x8001AACC
	//			// Variables:
	//				int tmpdist; // $a1

	//			/* begin block 1.2.3.1 */
	//				// Start line: 3880
	//				// Start offset: 0x8001AAE8
	//				// Variables:
	//					short _x1; // $v0
	//					short _y1; // $v1
	//					short _z1; // $a0
	//			/* end block 1.2.3.1 */
	//			// End offset: 0x8001AAE8
	//			// End Line: 3880
	//		/* end block 1.2.3 */
	//		// End offset: 0x8001AB0C
	//		// End Line: 3884
	//	/* end block 1.2 */
	//	// End offset: 0x8001AB1C
	//	// End Line: 3892
	///* end block 1 */
	//// End offset: 0x8001AB3C
	//// End Line: 3893

	///* begin block 2 */
	//	// Start line: 9111
	///* end block 2 */
	//// End Line: 9112

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SplineGetNearestPoint(struct Spline *spline /*$s4*/, struct _SVector *point /*$s6*/, int *currkey /*$s7*/, struct _SVector *ret_dpoint /*stack 12*/)
void CAMERA_SplineGetNearestPoint(struct Spline *spline, struct _SVector *point, int *currkey, struct _SVector *ret_dpoint)
{ // line 3895, offset 0x8001ab6c
	///* begin block 1 */
	//	// Start line: 3896
	//	// Start offset: 0x8001AB6C
	//	// Variables:
	//		struct _SVector dpoint; // stack offset -96
	//		struct _SVector dpoint2; // stack offset -88
	//		struct _SVector dpoint3; // stack offset -80
	//		struct _SVector point0; // stack offset -72
	//		struct _SVector point1; // stack offset -64
	//		struct _SVector point2; // stack offset -56
	//		struct _SVector point3; // stack offset -48
	//		int current_keyframe; // $s0
	//		int dist; // $fp
	//		int ret; // $s5
	//		int ret2; // $s4
	//		int ret3; // $s0
	//		struct SplineKey *key; // $s1
	//		int circular_spline; // $s2
	//		int prev_key; // $s2
	//		int next_key; // $s3

	//	/* begin block 1.1 */
	//		// Start line: 3921
	//		// Start offset: 0x8001AC98
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $t0
	//			short _z1; // $a3
	//			struct _SVector *_v0; // $a1
	//			struct vecS *_v1; // $a3
	//	/* end block 1.1 */
	//	// End offset: 0x8001AC98
	//	// End Line: 3921

	//	/* begin block 1.2 */
	//		// Start line: 3921
	//		// Start offset: 0x8001AC98
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $t0
	//			short _z1; // $v1
	//			struct _SVector *_v0; // $a2
	//			struct vecS *_v1; // $v1
	//	/* end block 1.2 */
	//	// End offset: 0x8001AC98
	//	// End Line: 3921

	//	/* begin block 1.3 */
	//		// Start line: 3936
	//		// Start offset: 0x8001AD60
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $t0
	//			short _z1; // $v1
	//			struct _SVector *_v0; // $a2
	//			struct vecS *_v1; // $v1
	//	/* end block 1.3 */
	//	// End offset: 0x8001AD60
	//	// End Line: 3936

	//	/* begin block 1.4 */
	//		// Start line: 3949
	//		// Start offset: 0x8001ADC0
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $t0
	//			short _z1; // $v1
	//			struct _SVector *_v0; // $a1
	//			struct vecS *_v1; // $v1
	//	/* end block 1.4 */
	//	// End offset: 0x8001ADC0
	//	// End Line: 3949
	///* end block 1 */
	//// End offset: 0x8001AED4
	//// End Line: 3975

	///* begin block 2 */
	//	// Start line: 9304
	///* end block 2 */
	//// End Line: 9305

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SplineHelpMove(struct Camera *camera /*$s1*/)
void CAMERA_SplineHelpMove(struct Camera *camera)
{ // line 3981, offset 0x8001af04
	/* begin block 1 */
		// Start line: 3982
		// Start offset: 0x8001AF04
		// Variables:
			struct _SVector camPos; // stack offset -48
			_Position pos; // stack offset -40
			struct _Rotation rotation; // stack offset -32
			struct _Instance *focusInstance; // $s3
			struct MultiSpline *posSpline; // $s2
	/* end block 1 */
	// End offset: 0x8001B058
	// End Line: 4026

	/* begin block 2 */
		// Start line: 9489
	/* end block 2 */
	// End Line: 9490

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SplineProcess(struct Camera *camera /*$s1*/)
void CAMERA_SplineProcess(struct Camera *camera)
{ // line 4028, offset 0x8001b074
	/* begin block 1 */
		// Start line: 4029
		// Start offset: 0x8001B074
		// Variables:
			struct _SVector camPos; // stack offset -48
			struct _SVector sv; // stack offset -40
			short targetFocusDistance; // $s4
			struct MultiSpline *posSpline; // $s3
			short smooth; // $s0
			short dist_smooth; // $s2
			static short hold_flag; // offset 0x5c
			struct _Rotation targetFocusRotation; // stack offset -32

		/* begin block 1.1 */
			// Start line: 4114
			// Start offset: 0x8001B1C0
			// Variables:
				short _x0; // $v0
				short _y0; // $a1
				short _z0; // $a2
				short _x1; // $v1
				short _y1; // $v1
				short _z1; // $v0
				struct _SVector *_v; // $a0
				struct _SVector *_v1; // $v0
		/* end block 1.1 */
		// End offset: 0x8001B1C0
		// End Line: 4114
	/* end block 1 */
	// End offset: 0x8001B3A8
	// End Line: 4177

	/* begin block 2 */
		// Start line: 9602
	/* end block 2 */
	// End Line: 9603

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_ShakeCamera(struct Camera *camera /*$a2*/)
void CAMERA_ShakeCamera(struct Camera *camera)
{ // line 4201, offset 0x8001b3c8
	/* begin block 1 */
		// Start line: 9967
	/* end block 1 */
	// End Line: 9968

}

void CAMERA_Process(struct Camera* camera)
{
	struct _Instance* focusInstance;
	short _x0;
	short _y0;
	short _z0;
	short _x1;
	short _y1;
	short _z1;
	struct _SVector* _v;
	_Position* _v0;
	_Position* _v1;

	focusInstance = camera->focusInstance;
	
	camera->focuspoint_fallz -= camera->newFocusInstancePos.z - focusInstance->oldPos.z;

	camera->oldFocusInstancePos = camera->newFocusInstancePos;

	camera->newFocusInstancePos = focusInstance->position;

	camera->oldFocusInstanceRot = camera->newFocusInstanceRot;

	camera->newFocusInstanceRot = focusInstance->rotation;

	if (camera->signalPos.x == camera->core.position.x &&
		camera->signalPos.y == camera->core.position.y && 
		camera->signalPos.z == camera->core.position.z)
	{
		camera_still = 1;
	}
	else
	{
		camera_still = 0;
	}

	camera->signalPos.x = camera->core.position.x;
	camera->signalPos.y = camera->core.position.y;
	camera->signalPos.z = camera->core.position.z;
	
	camera->prev_instance_mode = camera->instance_mode;
	camera->x_rot_change = 0;

	camera->instance_mode = CAMERA_QueryMode(camera);

	_v0 = &camera->newFocusInstancePos;
	_v1 = &camera->oldFocusInstancePos;

	_x0 = _v0->x;
	_y0 = _v0->y;
	_z0 = _v0->z;

	_x1 = _v1->x;
	_y1 = _v1->y;
	_z1 = _v1->z;

	_v = &camera->focusInstanceVelVec;
	
	_v->x = _x0 - _x1;
	_v->y = _y0 - _y1;
	_v->z = _z0 - _z1;

	camera->instance_prev_xyvel = camera->instance_xyvel;

	camera->instance_xyvel = MATH3D_FastSqrt0((camera->focusInstanceVelVec.x * camera->focusInstanceVelVec.x) + (camera->focusInstanceVelVec.y * camera->focusInstanceVelVec.y));

	if (shorten_flag == 0)
	{
		shorten_count = 0;
	}

	shorten_flag = 0;

	if (camera->cuckooTimer > 0)
	{
		camera->cuckooTimer--;
	}

	if (camera->mode != 6)
	{
		CAMERA_HandleTransitions(camera);
	}

	switch (camera->mode)
	{
	case 0:
	case 12:
	case 13:
		CAMERA_GenericCameraProcess(camera);
		break;
	case 2:
	case 4:
		CAMERA_SplineProcess(camera);
		break;
	case 5:
		CAMERA_CinematicProcess(camera);
		break;
	case 6:
		CAMERA_LookProcess(camera);
		break;
	default:
		break;
	}

	camera->flags &= 0xFFFFF7FF;
	camera->flags &= 0xFFFFEFFF;

	CAMERA_ShakeCamera(camera);
}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CenterCamera(struct Camera *camera /*$s1*/)
void CAMERA_CenterCamera(struct Camera *camera)
{ // line 4404, offset 0x8001b6fc
	/* begin block 1 */
		// Start line: 4405
		// Start offset: 0x8001B6FC

		/* begin block 1.1 */
			// Start line: 4409
			// Start offset: 0x8001B724
			// Variables:
				int tmp1; // $s0
				int tmp2; // $v0
		/* end block 1.1 */
		// End offset: 0x8001B790
		// End Line: 4413
	/* end block 1 */
	// End offset: 0x8001B7BC
	// End Line: 4420

	/* begin block 2 */
		// Start line: 10388
	/* end block 2 */
	// End Line: 10389

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetLookRot(struct Camera *camera /*$a0*/, int x_rotation /*$a1*/, int z_rotation /*$a2*/)
void CAMERA_SetLookRot(struct Camera *camera, int x_rotation, int z_rotation)
{ // line 4436, offset 0x8001b7e4
	/* begin block 1 */
		// Start line: 8872
	/* end block 1 */
	// End Line: 8873

	/* begin block 2 */
		// Start line: 10441
	/* end block 2 */
	// End Line: 10442

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_StartLookaroundMode(struct Camera *camera /*$s0*/)
void CAMERA_StartLookaroundMode(struct Camera *camera)
{ // line 4442, offset 0x8001b7f0
	/* begin block 1 */
		// Start line: 10452
	/* end block 1 */
	// End Line: 10453

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_StartSwimThrowMode(struct Camera *camera /*$s0*/)
void CAMERA_StartSwimThrowMode(struct Camera *camera)
{ // line 4460, offset 0x8001b880
	/* begin block 1 */
		// Start line: 10498
	/* end block 1 */
	// End Line: 10499

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_EndSwimThrowMode(struct Camera *camera /*$a0*/)
void CAMERA_EndSwimThrowMode(struct Camera *camera)
{ // line 4468, offset 0x8001b8c0
	/* begin block 1 */
		// Start line: 10515
	/* end block 1 */
	// End Line: 10516

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_ForceEndLookaroundMode(struct Camera *camera /*$s0*/)
void CAMERA_ForceEndLookaroundMode(struct Camera *camera)
{ // line 4474, offset 0x8001b8e4
	/* begin block 1 */
		// Start line: 10527
	/* end block 1 */
	// End Line: 10528

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Control(struct Camera *camera /*$s0*/, struct _Instance *playerInstance /*$s5*/)
void CAMERA_Control(struct Camera *camera, struct _Instance *playerInstance)
{ // line 4483, offset 0x8001b920
	/* begin block 1 */
		// Start line: 4484
		// Start offset: 0x8001B920
		// Variables:
			long *controlCommand; // $s2
			int lookmode; // $s1
			struct _Instance *focusInstance; // $s4
	/* end block 1 */
	// End offset: 0x8001BE44
	// End Line: 4718

	/* begin block 2 */
		// Start line: 10545
	/* end block 2 */
	// End Line: 10546

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_EndLook(struct Camera *camera /*$s0*/)
void CAMERA_EndLook(struct Camera *camera)
{ // line 4721, offset 0x8001be68
	/* begin block 1 */
		// Start line: 4722
		// Start offset: 0x8001BE68
		// Variables:
			struct _Instance *focusInstance; // $s1
	/* end block 1 */
	// End offset: 0x8001BF44
	// End Line: 4782

	/* begin block 2 */
		// Start line: 11051
	/* end block 2 */
	// End Line: 11052

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_ChangeToUnderWater(struct Camera *camera /*$s0*/, struct _Instance *instance /*$a1*/)
void CAMERA_ChangeToUnderWater(struct Camera *camera, struct _Instance *instance)
{ // line 4786, offset 0x8001bf5c
	/* begin block 1 */
		// Start line: 11218
	/* end block 1 */
	// End Line: 11219

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_ChangeToOutOfWater(struct Camera *camera /*$s0*/, struct _Instance *instance /*$a1*/)
void CAMERA_ChangeToOutOfWater(struct Camera *camera, struct _Instance *instance)
{ // line 4813, offset 0x8001c008
	/* begin block 1 */
		// Start line: 11272
	/* end block 1 */
	// End Line: 11273

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_UpdateFocusDistance(struct Camera *camera /*$a3*/)
void CAMERA_UpdateFocusDistance(struct Camera *camera)
{ // line 4929, offset 0x8001c07c
	/* begin block 1 */
		// Start line: 4930
		// Start offset: 0x8001C07C
		// Variables:
			int smooth; // $v1
			long dampMode; // $a0
	/* end block 1 */
	// End offset: 0x8001C13C
	// End Line: 4977

	/* begin block 2 */
		// Start line: 9858
	/* end block 2 */
	// End Line: 9859

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_UpdateFocusTilt(struct Camera *camera /*$s0*/)
void CAMERA_UpdateFocusTilt(struct Camera *camera)
{ // line 4979, offset 0x8001c14c
	/* begin block 1 */
		// Start line: 11503
	/* end block 1 */
	// End Line: 11504

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_UpdateFocusRoll(struct Camera *camera /*$s1*/)
void CAMERA_UpdateFocusRoll(struct Camera *camera)
{ // line 5013, offset 0x8001c218
	/* begin block 1 */
		// Start line: 5014
		// Start offset: 0x8001C218
		// Variables:
			long tmp_inc; // $s0
	/* end block 1 */
	// End offset: 0x8001C318
	// End Line: 5031

	/* begin block 2 */
		// Start line: 11574
	/* end block 2 */
	// End Line: 11575

	/* begin block 3 */
		// Start line: 11577
	/* end block 3 */
	// End Line: 11578

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_UpdateFocusRotate(struct Camera *camera /*$s0*/)
void CAMERA_UpdateFocusRotate(struct Camera *camera)
{ // line 5037, offset 0x8001c334
	/* begin block 1 */
		// Start line: 5038
		// Start offset: 0x8001C334

		/* begin block 1.1 */
			// Start line: 5041
			// Start offset: 0x8001C368
			// Variables:
				int dampspeed; // $v1
				long dampmode; // $a0
		/* end block 1.1 */
		// End offset: 0x8001C3E8
		// End Line: 5066
	/* end block 1 */
	// End offset: 0x8001C410
	// End Line: 5073

	/* begin block 2 */
		// Start line: 11626
	/* end block 2 */
	// End Line: 11627

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_UpdateFocusRotationX(struct Camera *camera /*$s0*/, struct _Instance *focusInstance /*$a1*/)
void CAMERA_UpdateFocusRotationX(struct Camera *camera, struct _Instance *focusInstance)
{ // line 5079, offset 0x8001c420
	/* begin block 1 */
		// Start line: 5080
		// Start offset: 0x8001C420
		// Variables:
			short cameraPlayerRotX; // $a1
			short dist; // $s1
			short tfaceFlag; // $s2

		/* begin block 1.1 */
			// Start line: 5102
			// Start offset: 0x8001C4A0
			// Variables:
				struct _Normal normal; // stack offset -24
				int mult; // $v1
		/* end block 1.1 */
		// End offset: 0x8001C580
		// End Line: 5128

		/* begin block 1.2 */
			// Start line: 5132
			// Start offset: 0x8001C58C
			// Variables:
				int tmpsmooth; // $t0
		/* end block 1.2 */
		// End offset: 0x8001C5F8
		// End Line: 5147
	/* end block 1 */
	// End offset: 0x8001C688
	// End Line: 5173

	/* begin block 2 */
		// Start line: 11710
	/* end block 2 */
	// End Line: 11711

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_FollowPlayerTilt(struct Camera *camera /*$s1*/, struct _Instance *focusInstance /*$a1*/)
void CAMERA_FollowPlayerTilt(struct Camera *camera, struct _Instance *focusInstance)
{ // line 5178, offset 0x8001c6a0
	/* begin block 1 */
		// Start line: 5179
		// Start offset: 0x8001C6A0
		// Variables:
			int speed; // $s2
			int mode; // $s3
			long focusInstanceStatus; // $a0

		/* begin block 1.1 */
			// Start line: 5203
			// Start offset: 0x8001C724
			// Variables:
				struct _SVector offset; // stack offset -40
				struct _Normal normal; // stack offset -32

			/* begin block 1.1.1 */
				// Start line: 5227
				// Start offset: 0x8001C7DC
				// Variables:
					int waterZ; // $v0
					int target; // $v0
					int height; // $s0

				/* begin block 1.1.1.1 */
					// Start line: 5235
					// Start offset: 0x8001C81C
					// Variables:
						int fdsq; // $v0
				/* end block 1.1.1.1 */
				// End offset: 0x8001C85C
				// End Line: 5243
			/* end block 1.1.1 */
			// End offset: 0x8001C85C
			// End Line: 5244
		/* end block 1.1 */
		// End offset: 0x8001C85C
		// End Line: 5245
	/* end block 1 */
	// End offset: 0x8001C85C
	// End Line: 5250

	/* begin block 2 */
		// Start line: 11914
	/* end block 2 */
	// End Line: 11915

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_FollowGoBehindPlayerWithTimer(struct Camera *camera /*$s0*/)
void CAMERA_FollowGoBehindPlayerWithTimer(struct Camera *camera)
{ // line 5259, offset 0x8001c8b0
	/* begin block 1 */
		// Start line: 5260
		// Start offset: 0x8001C8B0
		// Variables:
			struct _Instance *focusInstance; // $s1
	/* end block 1 */
	// End offset: 0x8001C998
	// End Line: 5298

	/* begin block 2 */
		// Start line: 12087
	/* end block 2 */
	// End Line: 12088

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_FollowGoBehindPlayer(struct Camera *camera /*$v1*/)
void CAMERA_FollowGoBehindPlayer(struct Camera *camera)
{ // line 5301, offset 0x8001c9ac
	/* begin block 1 */
		// Start line: 5302
		// Start offset: 0x8001C9AC
		// Variables:
			struct _Instance *focusInstance; // $v0
	/* end block 1 */
	// End offset: 0x8001C9AC
	// End Line: 5302

	/* begin block 2 */
		// Start line: 12179
	/* end block 2 */
	// End Line: 12180

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CalculateLead(struct Camera *camera /*$s1*/)
void CAMERA_CalculateLead(struct Camera *camera)
{ // line 5313, offset 0x8001c9e8
	/* begin block 1 */
		// Start line: 5314
		// Start offset: 0x8001C9E8
		// Variables:
			short lead_target; // $s0
			short lead_smooth; // $v1

		/* begin block 1.1 */
			// Start line: 5320
			// Start offset: 0x8001CA34
			// Variables:
				int speedxy; // $s0
				short angle; // $a0

			/* begin block 1.1.1 */
				// Start line: 5332
				// Start offset: 0x8001CABC
				// Variables:
					int calc; // $v1
			/* end block 1.1.1 */
			// End offset: 0x8001CB2C
			// End Line: 5349
		/* end block 1.1 */
		// End offset: 0x8001CB34
		// End Line: 5354
	/* end block 1 */
	// End offset: 0x8001CB40
	// End Line: 5368

	/* begin block 2 */
		// Start line: 12203
	/* end block 2 */
	// End Line: 12204

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_CalcFollowPosition(struct Camera *camera /*$s1*/, struct _Rotation *rotation /*$s0*/)
void CAMERA_CalcFollowPosition(struct Camera *camera, struct _Rotation *rotation)
{ // line 5384, offset 0x8001cb90
	///* begin block 1 */
	//	// Start line: 5385
	//	// Start offset: 0x8001CB90
	//	// Variables:
	//		struct _Instance *focusInstance; // $s2

	//	/* begin block 1.1 */
	//		// Start line: 5385
	//		// Start offset: 0x8001CB90
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $v1
	//			short _z1; // $a0
	//			struct _Rotation *_v0; // $v0
	//	/* end block 1.1 */
	//	// End offset: 0x8001CB90
	//	// End Line: 5385

	//	/* begin block 1.2 */
	//		// Start line: 5404
	//		// Start offset: 0x8001CC10
	//		// Variables:
	//			short target_rotx; // $s0
	//			int hypotXY; // $s3
	//			int smooth; // $v1
	//			int diff; // $a0
	//			struct _Vector dpv; // stack offset -40
	//			int zdiff; // $a0

	//		/* begin block 1.2.1 */
	//			// Start line: 5426
	//			// Start offset: 0x8001CCAC
	//			// Variables:
	//				int velz; // $a1

	//			/* begin block 1.2.1.1 */
	//				// Start line: 5437
	//				// Start offset: 0x8001CCC8
	//				// Variables:
	//					int ground; // $a0
	//					int pos; // $v1
	//			/* end block 1.2.1.1 */
	//			// End offset: 0x8001CD40
	//			// End Line: 5452
	//		/* end block 1.2.1 */
	//		// End offset: 0x8001CD40
	//		// End Line: 5452
	//	/* end block 1.2 */
	//	// End offset: 0x8001CE4C
	//	// End Line: 5500
	///* end block 1 */
	//// End offset: 0x8001CE64
	//// End Line: 5505

	///* begin block 2 */
	//	// Start line: 12347
	///* end block 2 */
	//// End Line: 12348

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_SetupColInfo(struct Camera *camera /*$a3*/, struct CameraCollisionInfo *colInfo /*$t0*/, _Position *targetCamPos /*$a2*/)
void CAMERA_SetupColInfo(struct Camera *camera, struct CameraCollisionInfo *colInfo, _Position *targetCamPos)
{ // line 5509, offset 0x8001ce8c
	///* begin block 1 */
	//	// Start line: 5510
	//	// Start offset: 0x8001CE8C
	//	// Variables:
	//		static short toggle; // offset 0x60

	//	/* begin block 1.1 */
	//		// Start line: 5515
	//		// Start offset: 0x8001CEA0
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $a1
	//			_Position *_v0; // $v0
	//			_Position *_v1; // $v0
	//	/* end block 1.1 */
	//	// End offset: 0x8001CEA0
	//	// End Line: 5515

	//	/* begin block 1.2 */
	//		// Start line: 5519
	//		// Start offset: 0x8001CEAC
	//		// Variables:
	//			short _x1; // $v1
	//			short _y1; // $a0
	//			short _z1; // $a1
	//			_Position *_v0; // $v0
	//			_Position *_v1; // $v0
	//	/* end block 1.2 */
	//	// End offset: 0x8001CECC
	//	// End Line: 5519

	//	/* begin block 1.3 */
	//		// Start line: 5521
	//		// Start offset: 0x8001CECC
	//		// Variables:
	//			short _x1; // $v0
	//			short _y1; // $a0
	//			short _z1; // $a1
	//			_Position *_v0; // $v1
	//	/* end block 1.3 */
	//	// End offset: 0x8001CECC
	//	// End Line: 5521
	///* end block 1 */
	//// End offset: 0x8001CF44
	//// End Line: 5542

	///* begin block 2 */
	//	// Start line: 12616
	///* end block 2 */
	//// End Line: 12617

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_DoPanicCheck(struct Camera *camera /*$s0*/, struct CameraCollisionInfo *tmpcolInfo /*$s1*/, struct _Rotation *rotation /*$s3*/, short *best_z /*$s4*/, short *max_dist /*stack 16*/)
void CAMERA_DoPanicCheck(struct Camera *camera, struct CameraCollisionInfo *tmpcolInfo, struct _Rotation *rotation, short *best_z, short *max_dist)
{ // line 5550, offset 0x8001cf4c
	/* begin block 1 */
		// Start line: 5551
		// Start offset: 0x8001CF4C
		// Variables:
			_Position targetCamPos; // stack offset -32

		/* begin block 1.1 */
			// Start line: 5551
			// Start offset: 0x8001CF4C
			// Variables:
				short _x1; // $v1
				short _y1; // $a3
				short _z1; // $t0
				_Position *_v0; // $v0
				_Position *_v1; // $v0
		/* end block 1.1 */
		// End offset: 0x8001CF4C
		// End Line: 5551
	/* end block 1 */
	// End offset: 0x8001CFFC
	// End Line: 5563

	/* begin block 2 */
		// Start line: 12701
	/* end block 2 */
	// End Line: 12702

}


// autogenerated function stub: 
// void /*$ra*/ CAMERA_Panic(struct Camera *camera /*$s2*/, short min_dist /*$fp*/)
void CAMERA_Panic(struct Camera *camera, short min_dist)
{ // line 5565, offset 0x8001d01c
	/* begin block 1 */
		// Start line: 5566
		// Start offset: 0x8001D01C
		// Variables:
			_Position targetCamPos; // stack offset -160
			struct _Rotation rotation; // stack offset -152
			int n; // $s1
			short best_z; // stack offset -48
			short max_dist; // stack offset -46
			struct CameraCollisionInfo tmpcolInfo; // stack offset -144
			short free_count1; // $s7
			short free_count2; // $s6
	/* end block 1 */
	// End offset: 0x8001D19C
	// End Line: 5615

	/* begin block 2 */
		// Start line: 12739
	/* end block 2 */
	// End Line: 12740

}


// autogenerated function stub: 
// long /*$ra*/ CAMERA_DoCameraCollision2(struct Camera *camera /*$s1*/, _Position *targetCamPos /*$v0*/, int simpleflag /*$s3*/)
long CAMERA_DoCameraCollision2(struct Camera *camera, _Position *targetCamPos, int simpleflag)
{ // line 5619, offset 0x8001d1cc
	/* begin block 1 */
		// Start line: 5620
		// Start offset: 0x8001D1CC
		// Variables:
			int secondcheck_flag; // $s0
			long hit; // $s2
			struct CameraCollisionInfo colInfo; // stack offset -120
			static long collisiontimeDown; // offset 0x64

		/* begin block 1.1 */
			// Start line: 5710
			// Start offset: 0x8001D40C
			// Variables:
				short _x1; // $v1
				short _y1; // $a3
				short _z1; // $t0
				_Position *_v0; // $v0
				_Position *_v1; // $v0
		/* end block 1.1 */
		// End offset: 0x8001D40C
		// End Line: 5710

		/* begin block 1.2 */
			// Start line: 5766
			// Start offset: 0x8001D558
			// Variables:
				int speed; // $s0
		/* end block 1.2 */
		// End offset: 0x8001D620
		// End Line: 5786

		/* begin block 1.3 */
			// Start line: 5816
			// Start offset: 0x8001D6A8
			// Variables:
				int angle1; // $s0
				int angle2; // $v0
		/* end block 1.3 */
		// End offset: 0x8001D754
		// End Line: 5832
	/* end block 1 */
	// End offset: 0x8001D7B4
	// End Line: 5871

	/* begin block 2 */
		// Start line: 12897
	/* end block 2 */
	// End Line: 12898

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ CAMERA_FocusInstanceMoved(struct Camera *camera /*$a0*/)
int CAMERA_FocusInstanceMoved(struct Camera *camera)
{ // line 5876, offset 0x8001d7d0
	return camera->newFocusInstancePos.x != camera->oldFocusInstancePos.x
		|| camera->newFocusInstancePos.y != camera->oldFocusInstancePos.y
		|| camera->newFocusInstancePos.z != camera->oldFocusInstancePos.z
		|| camera->newFocusInstanceRot.x != camera->oldFocusInstanceRot.x
		|| camera->newFocusInstanceRot.y != camera->oldFocusInstanceRot.y
		|| camera->newFocusInstanceRot.z != camera->oldFocusInstanceRot.z;
}
