#include "CORE.H"
#include "GENERIC.H"
#include "Game/STATE.H"
#include "Game/G2/ANMG2ILF.H"
#include "SCRIPT.H"

void GenericInit(struct _Instance* instance, struct GameTracker* gameTracker)//Matching - 86.44%
{
	struct Object* object; // $s1
	struct Spline* spline; // $v1
	static struct _G2AnimInterpInfo_Type crap;

	object = instance->object;
	spline = NULL;

	if (instance->intro != NULL)
	{
		if (instance->intro->multiSpline != NULL)
		{
			spline = instance->intro->multiSpline->positional;
		}
	}

	if (spline == NULL)
	{
		instance->zAccl = -10;
		instance->maxXVel = 100;
		instance->maxYVel = 100;
		instance->maxZVel = 100;
	}

	if (object != NULL)
	{
		if (object->numAnims != 0)
		{
			if (!(object->oflags2 & 0x40000000))
			{
				G2EmulationInstanceSetTotalSections(instance, 1);
				
				G2EmulationInstanceSetStartAndEndSegment(instance, 0,0,(short)((unsigned short)object->modelList[instance->currentModel]->numSegments - 1));
				
				G2EmulationInstanceSetAnimation(instance, 0, 0, 0, 0);
				
				G2EmulationInstanceSetMode(instance, 0, 0);

				if (((unsigned int*)object->name)[0] == 0x65697261 && ((unsigned int*)object->name)[1] == 0x5F5F5F6C)
				{
					G2AnimSection_SetInterpInfo(&instance->anim.section[0], &crap);
				}
			}
		}
	}
}

void GenericCollide(struct _Instance* instance, struct GameTracker* gameTracker)
{
}

void GenericProcess(struct _Instance* instance, struct GameTracker* gameTracker)//Matching - 99.76%
{
	struct Object* object;

	object = instance->object;

	if (object && object->numAnims && !(object->oflags2 & 0x40000000))
	{
		G2EmulationInstancePlayAnimation(instance);
	}
}


// autogenerated function stub: 
// unsigned long /*$ra*/ GenericQuery(struct _Instance *instance /*$s0*/, unsigned long query /*$a1*/)
unsigned long GenericQuery(struct _Instance *instance, unsigned long query)
{ // line 149, offset 0x8003e32c
	/* begin block 1 */
		// Start line: 150
		// Start offset: 0x8003E32C
		// Variables:
			long ret; // $a0

		/* begin block 1.1 */
			// Start line: 181
			// Start offset: 0x8003E400
			// Variables:
				struct evControlSaveDataData *pdata; // $v0
		/* end block 1.1 */
		// End offset: 0x8003E440
		// End Line: 191

		/* begin block 1.2 */
			// Start line: 195
			// Start offset: 0x8003E440
			// Variables:
				struct Object *object; // $a0
		/* end block 1.2 */
		// End offset: 0x8003E484
		// End Line: 203
	/* end block 1 */
	// End offset: 0x8003E490
	// End Line: 216

	/* begin block 2 */
		// Start line: 301
	/* end block 2 */
	// End Line: 302
				UNIMPLEMENTED();
	return 0;
}


void GenericMessage(struct _Instance* instance, unsigned long message, unsigned long data)  // Matching - 100%
{
	struct evAnimationInstanceSwitchData* Ptr;

	switch (message)
	{
	case 0x8000008:
		Ptr = (struct evAnimationInstanceSwitchData*)data;
		if (instance->anim.section[0].interpInfo != NULL)
		{
			G2EmulationInstanceSetAnimation(instance, 0, Ptr->anim, Ptr->frame, Ptr->frames);
		}
		else
		{
			G2EmulationInstanceSetAnimation(instance, 0, Ptr->anim, Ptr->frame, 0);
		}
		G2EmulationInstanceSetMode(instance, 0, Ptr->mode);
		break;
	case 0x4000A:
		STREAM_SetInstancePosition(instance, (struct evPositionData*)data);
		break;
	case 0x4000B:
		instance->rotation.x = ((struct evPositionData*)data)->x;
		instance->rotation.y = ((struct evPositionData*)data)->y;
		instance->rotation.z = ((struct evPositionData*)data)->z;
		break;
	case 0x8000010:
		G2EmulationInstanceSetMode(instance, 0, data);
		break;
	case 0x40002:
		ScriptKillInstance(instance, data);
		break;
	case 0x100007:
		instance->flags = (int)((struct _Instance*)data)->node.next[0].prev;
		instance->flags2 = (int)((struct _Instance*)data)->node.next[0].next;
		break;
	}
}

void GenericRelocateTune(struct Object* object, long offset)
{
	struct GenericTune* tune;

	tune = (struct GenericTune*)object->modelList;

	if (tune != NULL && tune->shatterData != NULL)
	{
		tune->shatterData = (char*)tune->shatterData + offset;
	}
}