#include "CORE.H"
#include "GLYPH.H"
#include "MEMPACK.H"
#include "STATE.H"
#include "FX.H"

short glyph_time;
short glyph_trigger;
short glyph_cost;

void GlyphInit(struct _Instance* instance, struct GameTracker* gameTracker)
{
	struct __GlyphData* data;

	if ((instance->flags & 0x20000))
	{
		MEMPACK_Free((char*)instance->extraData);
	}
	else
	{
		data = (struct __GlyphData*)MEMPACK_Malloc(sizeof(__GlyphData), 0x1D);

		instance->extraData = data;
		InitMessageQueue(&data->messages);
		EnMessageQueueData(&data->messages, 0x100001, 0);

		data->process = &_GlyphOffProcess;
		data->selectedGlyph = 7;
		data->target_glyph_rotation = 3510;
		data->glyph_time = 0;
		
		glyph_time = 0;
		
		data->glyph_radius = 0;
		data->glyph_scale = 0;
		data->glyph_movement = 1;
		data->glyph_open = 0;

		glyph_trigger = 0;
	
		fx_blastring = NULL;

		data->glyph_rotation = (data->selectedGlyph - 1) * 585;

		glyph_cost = 0xFFFFFFFF;

		instance->flags |= 0x10800;

	}

	HUD_Init();
}


// autogenerated function stub: 
// void /*$ra*/ GlyphCollide(struct _Instance *instance /*$a0*/, struct GameTracker *gameTracker /*$a1*/)
void GlyphCollide(struct _Instance *instance, struct GameTracker *gameTracker)
{ // line 179, offset 0x8007a9d8
}


// autogenerated function stub: 
// void /*$ra*/ GlyphProcess(struct _Instance *instance /*$s0*/, struct GameTracker *gameTracker /*$a1*/)
void GlyphProcess(struct _Instance *instance, struct GameTracker *gameTracker)
{ // line 186, offset 0x8007a9e0
#if defined(PC_VERSION)
	struct _Instance* parent; // ecx
	int flags; // eax

	(*(void(__cdecl**)(struct _Instance*, DWORD, DWORD))instance->extraData)(instance, 0, 0);
	parent = instance->parent;
	instance->oldPos = parent->position;
	instance->position = parent->position;
	flags = instance->flags;
	flags |= 0xC00;
	instance->currentStreamUnitID = parent->currentStreamUnitID;
	instance->flags = flags;
#endif
}


// autogenerated function stub: 
// unsigned long /*$ra*/ GlyphQuery(struct _Instance *instance /*$a0*/, unsigned long query /*$a1*/)
unsigned long GlyphQuery(struct _Instance *instance, unsigned long query)
{ // line 216, offset 0x8007aa68
	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ GlyphPost(struct _Instance *instance /*$a0*/, unsigned long message /*$a1*/, unsigned long messageData /*$a2*/)
void GlyphPost(struct _Instance *instance, unsigned long message, unsigned long messageData)
{ // line 233, offset 0x8007aa88
	/* begin block 1 */
		// Start line: 234
		// Start offset: 0x8007AA88
		// Variables:
			struct __GlyphData *data; // $a0
	/* end block 1 */
	// End offset: 0x8007AAAC
	// End Line: 251

	/* begin block 2 */
		// Start line: 509
	/* end block 2 */
	// End Line: 510

}


// autogenerated function stub: 
// void /*$ra*/ _GlyphSwitchProcess(struct _Instance *instance /*$s1*/, TDRFuncPtr__GlyphSwitchProcess1process process /*$s3*/)
void _GlyphSwitchProcess(struct _Instance *instance, TDRFuncPtr__GlyphSwitchProcess1process process)
{ // line 261, offset 0x8007aabc
	/* begin block 1 */
		// Start line: 262
		// Start offset: 0x8007AABC
		// Variables:
			struct __GlyphData *data; // $s2
	/* end block 1 */
	// End offset: 0x8007AABC
	// End Line: 262

	/* begin block 2 */
		// Start line: 574
	/* end block 2 */
	// End Line: 575

}


// autogenerated function stub: 
// int /*$ra*/ GlyphIsGlyphOpen(struct _Instance *instance /*$a0*/)
int GlyphIsGlyphOpen(struct _Instance *instance)
{ // line 282, offset 0x8007ab5c
#if defined(PC_VERSION)
	return *((__int16*)instance->extraData + 71);
#else
	return 0;
#endif
}


// autogenerated function stub: 
// int /*$ra*/ _GlyphIsGlyphSet(int glyph /*$s0*/)
int _GlyphIsGlyphSet(int glyph)
{ // line 295, offset 0x8007ab70
	/* begin block 1 */
		// Start line: 296
		// Start offset: 0x8007AB70
		// Variables:
			unsigned long abilities; // $v1
	/* end block 1 */
	// End offset: 0x8007AB70
	// End Line: 296

	/* begin block 2 */
		// Start line: 646
	/* end block 2 */
	// End Line: 647

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ _GlyphIsGlyphUsable(int glyph /*$s0*/)
int _GlyphIsGlyphUsable(int glyph)
{ // line 304, offset 0x8007abb4
	/* begin block 1 */
		// Start line: 673
	/* end block 1 */
	// End Line: 674

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ _GlyphIsAnyGlyphSet()
int _GlyphIsAnyGlyphSet()
{ // line 308, offset 0x8007abf0
	/* begin block 1 */
		// Start line: 309
		// Start offset: 0x8007ABF0
		// Variables:
			unsigned long abilities; // $v0
	/* end block 1 */
	// End offset: 0x8007ABF0
	// End Line: 309

	/* begin block 2 */
		// Start line: 682
	/* end block 2 */
	// End Line: 683

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ _GlyphCost(struct _GlyphTuneData *glyphtunedata /*$a0*/, int glyphNum /*$a1*/)
int _GlyphCost(struct _GlyphTuneData *glyphtunedata, int glyphNum)
{ // line 318, offset 0x8007ac20
	/* begin block 1 */
		// Start line: 708
	/* end block 1 */
	// End Line: 709

	/* begin block 2 */
		// Start line: 709
	/* end block 2 */
	// End Line: 710

	return 0;
}


// autogenerated function stub: 
// int /*$ra*/ GlyphIsPuppetShowModeOn()
int GlyphIsPuppetShowModeOn()
{ // line 324, offset 0x8007ac30
	/* begin block 1 */
		// Start line: 720
	/* end block 1 */
	// End Line: 721

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ _GlyphDefaultProcess(struct _Instance *instance /*$s1*/, int data1 /*$a1*/, int data2 /*$a2*/)
void _GlyphDefaultProcess(struct _Instance *instance, int data1, int data2)
{ // line 336, offset 0x8007ac54
	/* begin block 1 */
		// Start line: 337
		// Start offset: 0x8007AC54
		// Variables:
			struct __Event *Ptr; // $v0
			struct __GlyphData *data; // $s0
	/* end block 1 */
	// End offset: 0x8007ACE0
	// End Line: 360

	/* begin block 2 */
		// Start line: 745
	/* end block 2 */
	// End Line: 746

}


// autogenerated function stub: 
// void /*$ra*/ HUD_GetPlayerScreenPt(struct DVECTOR *center /*$s0*/)
void HUD_GetPlayerScreenPt(DVECTOR *center)
{ // line 362, offset 0x8007acf8
	/* begin block 1 */
		// Start line: 363
		// Start offset: 0x8007ACF8
		// Variables:
			_Position position; // stack offset -16
	/* end block 1 */
	// End offset: 0x8007ACF8
	// End Line: 363

	/* begin block 2 */
		// Start line: 805
	/* end block 2 */
	// End Line: 806

}


// autogenerated function stub: 
// void /*$ra*/ GlyphDrawMenu(struct _Instance *instance /*stack 0*/)
void GlyphDrawMenu(struct _Instance *instance)
{ // line 380, offset 0x8007ad88
#if defined(PC_VERSION)
	__int16* extraData; // ebp
	signed int v2; // esi
	int(__cdecl * v3)(int, int); // eax
	__int16 v4; // cx
	__int16 v5; // ax
	int v6; // eax
	int v7; // esi
	__int16 v8; // di
	int v9; // ebx
	__int16 v10; // di
	int v11; // ecx
	int v12; // eax
	__int64 v13; // rax
	int v14; // ebp
	int v15; // esi
	int v16; // eax
	int v17; // [esp+10h] [ebp-2Ch]
	__int16* data; // [esp+14h] [ebp-28h]
	__int16* v19; // [esp+18h] [ebp-24h]
	int v20; // [esp+1Ch] [ebp-20h]
	int(__cdecl * v21)(int, int); // [esp+20h] [ebp-1Ch]
	SVECTOR v22; // [esp+24h] [ebp-18h] BYREF
	__int16 v23[3]; // [esp+2Ch] [ebp-10h] BYREF
	__int16 v24[4]; // [esp+34h] [ebp-8h] BYREF

	extraData = (__int16*)instance->extraData;
	v19 = extraData;
	data = (__int16*)instance->object->data;
	v2 = gameTrackerX.timeMult << 6 >> 12;
	v3 = INSTANCE_Query(gameTrackerX.playerInstance, 32);
	v4 = extraData[75];
	v21 = v3;
	v5 = extraData[76];
	if (v5 != v4)
	{
		v6 = AngleDiff(v5, v4);
		if ((v6 & 0x8000u) != 0)
			v6 = -(__int16)v6;
		if (v6 > v2)
		{
			if (extraData[77] <= 0)
				extraData[75] = (extraData[75] - v2) & 0xFFF;
			else
				extraData[75] = (extraData[75] + v2) & 0xFFF;
		}
		else
		{
			extraData[75] = extraData[76];
		}
	}
	PushMatrix();
	SetRotMatrix(theCamera.core.wcTransform);
	SetTransMatrix(theCamera.core.wcTransform);
	*(DWORD*)&v22.vx = *(DWORD*)&gameTrackerX.playerInstance->position.x;
	v22.vz = gameTrackerX.playerInstance->position.z + 448;
	gte_ldv0(&v22);
	gte_RTPS();
	gte_stsxy(v23);
	PopMatrix();
	if (v23[1] < 72)
		v23[1] = 72;
	v7 = extraData[73];
	v8 = extraData[75] + 3072;
	v20 = v7;
	v9 = 0;
	while (1)
	{
		v10 = v8 & 0xFFF;
		v11 = AngleDiff(v10, 3072) < 0 ? -AngleDiff(v10, 3072) : AngleDiff(v10, 3072);
		v12 = 2 * (2048 - v11);
		if (v12 < 1536)
			v12 = 1536;
		v13 = extraData[74] * v12;
		v14 = ((WORD2(v13) & 0xFFF) + (int)v13) >> 12;
		v24[0] = v23[0] + ((v7 * rcos(v10)) >> 12);
		v24[1] = v23[1] - ((v7 * rsin(v10)) >> 12) / 8;
		v15 = 1 << (v9 + 18);
		if (((debugRazielFlags3 | (unsigned int)INSTANCE_Query(gameTrackerX.playerInstance, 36)) & v15) != 0)
		{
			v17 = v9;
			*(DWORD*)&v22.vx = v15 & (unsigned int)INSTANCE_Query(gameTrackerX.playerInstance, 19);
			if (*(DWORD*)&v22.vx)
			{
				v16 = *((char*)data + v9 + 4) <= (int)v21;
				goto LABEL_25;
			}
		}
		else
		{
			if (v9 != 6)
			{
				v17 = 7;
				v16 = 1;
				goto LABEL_25;
			}
			v17 = 6;
		}
		v16 = 0;
	LABEL_25:
		FX_MakeGlyphIcon(v24, instance->object, v14 * *data / 4096 / 2, v17, v16);
		v8 = v10 - 585;
		if (++v9 >= 7)
			break;
		extraData = v19;
		v7 = v20;
	}
#endif
}


// autogenerated function stub: 
// long /*$ra*/ GlyphTime(int time /*$a0*/)
long GlyphTime(int time)
{ // line 510, offset 0x8007b0ec
	/* begin block 1 */
		// Start line: 1238
	/* end block 1 */
	// End Line: 1239

	/* begin block 2 */
		// Start line: 1239
	/* end block 2 */
	// End Line: 1240

	return 0;
}


// autogenerated function stub: 
// void /*$ra*/ ShrinkGlyphMenu(struct _Instance *instance /*$s1*/)
void ShrinkGlyphMenu(struct _Instance *instance)
{ // line 517, offset 0x8007b108
	/* begin block 1 */
		// Start line: 518
		// Start offset: 0x8007B108
		// Variables:
			struct __GlyphData *data; // $s0
			int time; // $a0
			short accl; // stack offset -24
	/* end block 1 */
	// End offset: 0x8007B214
	// End Line: 556

	/* begin block 2 */
		// Start line: 1252
	/* end block 2 */
	// End Line: 1253

}


// autogenerated function stub: 
// void /*$ra*/ EnlargeGlyphMenu(struct _Instance *instance /*$s1*/)
void EnlargeGlyphMenu(struct _Instance *instance)
{ // line 559, offset 0x8007b22c
	/* begin block 1 */
		// Start line: 560
		// Start offset: 0x8007B22C
		// Variables:
			struct __GlyphData *data; // $s0
			int time; // $a1
			short accl; // stack offset -24
	/* end block 1 */
	// End offset: 0x8007B2D4
	// End Line: 583

	/* begin block 2 */
		// Start line: 1351
	/* end block 2 */
	// End Line: 1352

}


// autogenerated function stub: 
// void /*$ra*/ _GlyphOffProcess(struct _Instance *instance /*$s1*/, int data1 /*$s4*/, int data2 /*$s5*/)
void _GlyphOffProcess(struct _Instance *instance, int data1, int data2)
{ // line 596, offset 0x8007b328
	/* begin block 1 */
		// Start line: 597
		// Start offset: 0x8007B328
		// Variables:
			struct __Event *Ptr; // $v0
			struct __GlyphData *data; // $s0
	/* end block 1 */
	// End offset: 0x8007B444
	// End Line: 634

	/* begin block 2 */
		// Start line: 1438
	/* end block 2 */
	// End Line: 1439

}


// autogenerated function stub: 
// void /*$ra*/ _GlyphSelectProcess(struct _Instance *instance /*$s3*/, int data1 /*$s6*/, int data2 /*$s7*/)
void _GlyphSelectProcess(struct _Instance *instance, int data1, int data2)
{ // line 639, offset 0x8007b470
	/* begin block 1 */
		// Start line: 640
		// Start offset: 0x8007B470
		// Variables:
			struct __Event *Ptr; // $v0
			struct __GlyphData *data; // $s1
			struct _GlyphTuneData *glyphtunedata; // $s4
			int dontdraw_flag; // $s2

		/* begin block 1.1 */
			// Start line: 712
			// Start offset: 0x8007B85C
			// Variables:
				int MANNA_Count; // $s0
		/* end block 1.1 */
		// End offset: 0x8007B8B0
		// End Line: 721
	/* end block 1 */
	// End offset: 0x8007B93C
	// End Line: 751

	/* begin block 2 */
		// Start line: 1524
	/* end block 2 */
	// End Line: 1525

}


// autogenerated function stub: 
// void /*$ra*/ Glyph_StartSpell(struct _Instance *instance /*$a0*/, int glyphnum /*$a1*/)
void Glyph_StartSpell(struct _Instance *instance, int glyphnum)
{ // line 757, offset 0x8007b970
	/* begin block 1 */
		// Start line: 758
		// Start offset: 0x8007B970
		// Variables:
			int message; // $a2
	/* end block 1 */
	// End offset: 0x8007B9F8
	// End Line: 791

	/* begin block 2 */
		// Start line: 1791
	/* end block 2 */
	// End Line: 1792

}


// autogenerated function stub: 
// void /*$ra*/ Glyph_Broadcast(struct _Instance *sender /*$s6*/, int glyphnum /*$a1*/)
void Glyph_Broadcast(struct _Instance *sender, int glyphnum)
{ // line 794, offset 0x8007ba18
	/* begin block 1 */
		// Start line: 795
		// Start offset: 0x8007BA18
		// Variables:
			struct _Instance *instance; // $s2
			int plane; // $s7
			long whatAmIMask; // $s4
			int Message; // $s3
			int radius; // stack offset -48
			int radius_old; // $fp
			int range; // $s5

		/* begin block 1.1 */
			// Start line: 847
			// Start offset: 0x8007BB28
			// Variables:
				int dist; // $s0
				int old_dist; // $v0
				int old_x; // $s0
				int old_y; // $s1
				int new_x; // $v0
				int new_y; // $v1
				long whatAmI; // $s0
		/* end block 1.1 */
		// End offset: 0x8007BC30
		// End Line: 878
	/* end block 1 */
	// End offset: 0x8007BC40
	// End Line: 879

	/* begin block 2 */
		// Start line: 1865
	/* end block 2 */
	// End Line: 1866

	/* begin block 3 */
		// Start line: 1875
	/* end block 3 */
	// End Line: 1876

}


// autogenerated function stub: 
// void /*$ra*/ Glyph_DoSpell(struct _Instance *instance /*stack 0*/, int glyphnum /*$s1*/)
void Glyph_DoSpell(struct _Instance *instance, int glyphnum)
{ // line 881, offset 0x8007bc70
	/* begin block 1 */
		// Start line: 882
		// Start offset: 0x8007BC70
		// Variables:
			int fx_radius; // $fp
			int fx_accl; // $v0
			int fx_vel; // $s5
			long fx_color; // $a3
			int fx_height1; // $s7
			int fx_height2; // $s6
			int fx_height3; // $s4
			int fx_rad2; // $s3
			int fx_rad3; // $s2
			int pred_offset; // $s0
			int color_change_radius; // $s1
			//MATRIX mat; // stack offset -80
			struct _GlyphTuneData *glyphtunedata; // $s0
	/* end block 1 */
	// End offset: 0x8007BED8
	// End Line: 981

	/* begin block 2 */
		// Start line: 2104
	/* end block 2 */
	// End Line: 2105

}


// autogenerated function stub: 
// void /*$ra*/ Glyph_EndFX()
void Glyph_EndFX()
{ // line 984, offset 0x8007bf14
	/* begin block 1 */
		// Start line: 2346
	/* end block 1 */
	// End Line: 2347

	/* begin block 2 */
		// Start line: 2347
	/* end block 2 */
	// End Line: 2348

}


// autogenerated function stub: 
// void /*$ra*/ Glyph_DoFX(struct _Instance *instance /*$a0*/)
void Glyph_DoFX(struct _Instance *instance)
{ // line 991, offset 0x8007bf28
	/* begin block 1 */
		// Start line: 2358
	/* end block 1 */
	// End Line: 2359

	/* begin block 2 */
		// Start line: 2362
	/* end block 2 */
	// End Line: 2363

}


// autogenerated function stub: 
// void /*$ra*/ _GlyphGenericProcess(struct _Instance *instance /*$s2*/, int data1 /*$s3*/, int data2 /*$s4*/)
void _GlyphGenericProcess(struct _Instance *instance, int data1, int data2)
{ // line 1024, offset 0x8007bfd8
	/* begin block 1 */
		// Start line: 1025
		// Start offset: 0x8007BFD8
		// Variables:
			struct __Event *Ptr; // $v0
			struct __GlyphData *data; // $s1

		/* begin block 1.1 */
			// Start line: 1056
			// Start offset: 0x8007C0B0
			// Variables:
				struct _GlyphTuneData *glyphtunedata; // $s0
		/* end block 1.1 */
		// End offset: 0x8007C0E8
		// End Line: 1062
	/* end block 1 */
	// End offset: 0x8007C0E8
	// End Line: 1064

	/* begin block 2 */
		// Start line: 2432
	/* end block 2 */
	// End Line: 2433

}


// autogenerated function stub: 
// void /*$ra*/ GlyphTrigger()
void GlyphTrigger()
{ // line 1067, offset 0x8007c110
	/* begin block 1 */
		// Start line: 2520
	/* end block 1 */
	// End Line: 2521

	/* begin block 2 */
		// Start line: 2521
	/* end block 2 */
	// End Line: 2522

}


// autogenerated function stub: 
// void /*$ra*/ MANNA_Pickup()
void MANNA_Pickup()
{ // line 1084, offset 0x8007c12c
#if defined(PC_VERSION)
	dword_C55068 = 0x1E000;
	LOWORD(dword_C5508C) = 24;
#endif
}


// autogenerated function stub: 
// void /*$ra*/ HEALTHU_Pickup(struct _Instance *instance /*$s0*/)
void HEALTHU_Pickup(struct _Instance *instance)
{ // line 1090, offset 0x8007c148
	/* begin block 1 */
		// Start line: 2566
	/* end block 1 */
	// End Line: 2567

}


// autogenerated function stub: 
// void /*$ra*/ HUD_Damp(short *val /*$v1*/, short target /*$a1*/, short *vel /*$a3*/, short max /*$a3*/)
void HUD_Damp(short *val, short target, short *vel, short max)
{ // line 1106, offset 0x8007c1d4
	/* begin block 1 */
		// Start line: 1107
		// Start offset: 0x8007C1D4
		// Variables:
			short accl; // stack offset -16
	/* end block 1 */
	// End offset: 0x8007C1D4
	// End Line: 1107

	/* begin block 2 */
		// Start line: 2601
	/* end block 2 */
	// End Line: 2602

}


// autogenerated function stub: 
// void /*$ra*/ HUD_Init()
void HUD_Init()
{ // line 1113, offset 0x8007c21c
	/* begin block 1 */
		// Start line: 2621
	/* end block 1 */
	// End Line: 2622

	/* begin block 2 */
		// Start line: 2627
	/* end block 2 */
	// End Line: 2628

}


// autogenerated function stub: 
// void /*$ra*/ HUD_Setup_Chit_Count(int chits /*$a0*/)
void HUD_Setup_Chit_Count(int chits)
{ // line 1128, offset 0x8007c254
	/* begin block 1 */
		// Start line: 2656
	/* end block 1 */
	// End Line: 2657

	/* begin block 2 */
		// Start line: 2658
	/* end block 2 */
	// End Line: 2659

}


// autogenerated function stub: 
// void /*$ra*/ HUD_Update()
void HUD_Update()
{ // line 1134, offset 0x8007c28c
	/* begin block 1 */
		// Start line: 1135
		// Start offset: 0x8007C28C
		// Variables:
			short accl; // stack offset -16
	/* end block 1 */
	// End offset: 0x8007C4B0
	// End Line: 1220

	/* begin block 2 */
		// Start line: 2669
	/* end block 2 */
	// End Line: 2670

}


// autogenerated function stub: 
// void /*$ra*/ HUD_Draw()
void HUD_Draw()
{ // line 1231, offset 0x8007c4c0
	/* begin block 1 */
		// Start line: 1232
		// Start offset: 0x8007C4C0
		// Variables:
			struct _SVector Rotation; // stack offset -80
			struct _SVector Pos; // stack offset -72
			struct _SVector offset; // stack offset -64
			int n; // $s0

		/* begin block 1.1 */
			// Start line: 1238
			// Start offset: 0x8007C4F8
			// Variables:
				//struct DVECTOR center; // stack offset -56
				int glow; // $a1
				int left; // $t0
				int right; // $s0
		/* end block 1.1 */
		// End offset: 0x8007C66C
		// End Line: 1276

		/* begin block 1.2 */
			// Start line: 1284
			// Start offset: 0x8007C690
			// Variables:
				int oldx; // $s2
				int oldy; // $s3
				int MANNA_Count; // $s1
				int MANNA_Max; // $s0
		/* end block 1.2 */
		// End offset: 0x8007C750
		// End Line: 1307

		/* begin block 1.3 */
			// Start line: 1313
			// Start offset: 0x8007C784
			// Variables:
				struct _SVector targetPos; // stack offset -48
				struct _SVector accl; // stack offset -40
				struct _SVector HUD_Cap_Rot; // stack offset -32
		/* end block 1.3 */
		// End offset: 0x8007C85C
		// End Line: 1334

		/* begin block 1.4 */
			// Start line: 1345
			// Start offset: 0x8007C8C0
		/* end block 1.4 */
		// End offset: 0x8007C904
		// End Line: 1355
	/* end block 1 */
	// End offset: 0x8007C958
	// End Line: 1364

	/* begin block 2 */
		// Start line: 2880
	/* end block 2 */
	// End Line: 2881

}




