#include "SCRIPT2.H"

// PROTOTYPE CODE
// this is on pc but doesn't exist on psx at all

void UpdraftInit(struct _Instance* a1)
{
	UNIMPLEMENTED();
}

void UpdraftProcess(struct _Instance* a1)
{
	UNIMPLEMENTED();
}

void UpdraftCollide(struct _Instance* a1, struct GameTracker* a2)
{
	UNIMPLEMENTED();
}

// autogenerated function stub: 
// short /*$ra*/ LitShaft_GetFadeValue(struct _Instance *instance /*$a0*/)
short LitShaft_GetFadeValue(struct _Instance *instance)
{ // line 149, offset 0x8005ef70
	UNIMPLEMENTED();
	return 0;
}
